import type { ExerciseDefinition } from "./exerciseData";

export const COGNITIVE_SOMATIC_EXERCISES: ExerciseDefinition[] = [
  // ═══════════════════════════════════════════
  // COGNITIVE EXERCISES (1–50)
  // ═══════════════════════════════════════════

  {
    id: "seven-levels",
    name: "Seven Levels of Effectiveness",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "zonedSpectrum",
    whyNow: "Your journal reflected frustration about feeling stuck in reactive mode — mapping where you are on the seven levels can show you the next available shift.",
    science: "The seven levels model maps to measurable changes in prefrontal cortex activation and default mode network coherence. Lower levels correlate with increased amygdala dominance and cortisol output, while higher levels show greater ventromedial PFC engagement and increased heart rate variability, indicating parasympathetic recovery.",
    instruction: "The spectrum shows seven distinct zones from coping to transforming. Tap the zone that best matches your current state — the description and body sensations listed will help you confirm your placement. Once set, you will see micro-practices calibrated to move one level up from where you are.",
  },
  {
    id: "red-blue-lines",
    name: "Red Lines / Blue Lines",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "splitAnnotator",
    whyNow: "You wrote about a situation where you felt conflicted about what to do — separating your red-line assumptions from blue-line possibilities can open new options.",
    science: "Red-line thinking activates threat-detection circuits centered on the amygdala and anterior insula, narrowing attentional focus. Blue-line thinking engages the ventromedial prefrontal cortex and broadens the perceptual field, consistent with Fredrickson's broaden-and-build theory of positive emotions.",
    instruction: "In the left column, write your red-line thoughts — the limiting, fear-based, or assumption-heavy statements about the situation. In the right column, rewrite each one as a blue-line alternative — curious, possibility-oriented, and grounded. The split view lets you see the contrast directly.",
  },
  {
    id: "seven-keys-neuroplasticity",
    name: "Seven Keys to Neuroplasticity",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "wheelChart",
    whyNow: "You mentioned wanting to build a new habit but struggling with consistency — understanding which neuroplasticity levers you are already using (and which you are missing) can accelerate the change.",
    science: "Neuroplasticity requires specific conditions: attention, novelty, repetition, emotional engagement, adequate sleep, aerobic exercise, and social connection. Each factor modulates BDNF expression, long-term potentiation in the hippocampus, and synaptic pruning efficiency in distinct but complementary ways.",
    instruction: "The wheel displays seven segments, each representing a key driver of neuroplasticity. Rate your current engagement with each by dragging the fill level from center to edge. The resulting shape reveals which keys are strong and which need attention — tap any segment for targeted suggestions.",
  },
  {
    id: "prediction-process",
    name: "Prediction Process",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "splitAnnotator",
    whyNow: "Your entry described anxiety about an upcoming event — making your predictions explicit lets you test them against reality instead of letting them run in the background.",
    science: "The brain is a prediction machine: the prefrontal cortex generates expectations and the anterior cingulate cortex flags prediction errors. By making implicit predictions conscious, you engage metacognitive monitoring networks that reduce the emotional charge of uncertainty and improve calibration over time.",
    instruction: "In the left column, write your specific predictions about what will happen — be as concrete as possible. In the right column, after the event, return to annotate each prediction with what actually occurred. The gap between prediction and reality is where learning lives.",
  },
  {
    id: "pfc-sweet-spot",
    name: "PFC Sweet Spot",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "spectrumSlider",
    whyNow: "You described feeling either overwhelmed or underwhelmed at work — finding the sweet spot of optimal prefrontal engagement could help you perform at your best.",
    science: "Prefrontal cortex function follows an inverted-U curve with respect to arousal: too little dopamine/norepinephrine leads to distractibility, too much leads to rigidity and anxiety. The Yerkes-Dodson law, confirmed by neuroimaging, shows peak cognitive performance in a narrow band of moderate arousal.",
    instruction: "Drag the slider to where you feel your current arousal level sits — from disengaged on the left to overwhelmed on the right. The colored zones indicate under-arousal, optimal, and over-arousal states. Guidance for adjusting toward the sweet spot will appear based on your placement.",
  },
  {
    id: "hemisphere-integration",
    name: "100/100 Hemisphere Integration",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "dotGrid",
    whyNow: "Your journal showed a tension between logical analysis and intuitive knowing — this exercise helps you access both hemispheres at full capacity instead of choosing one over the other.",
    science: "Optimal cognitive performance requires interhemispheric integration via the corpus callosum. Left-hemisphere sequential processing and right-hemisphere holistic pattern recognition are not competing resources — they are complementary systems. EEG coherence studies show peak performance when both hemispheres are highly active and synchronized.",
    instruction: "The dot grid represents a matrix of both analytical (left-brain) and intuitive (right-brain) perspectives on your challenge. Place dots for each insight you have — analytical ones on the left side, intuitive ones on the right. Then look for connections that bridge both sides to find integrated solutions.",
  },
  {
    id: "bring-in-minions",
    name: "Bring in the Minions",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "dotGrid",
    whyNow: "You described trying to solve a complex problem alone — recruiting different internal 'advisors' can give you access to perspectives your dominant thinking style misses.",
    science: "The brain contains multiple semi-independent processing systems — what IFS calls 'parts' and neuroscience maps to distinct neural networks. Deliberately activating underused networks (e.g., the imaginative default mode network when you are stuck in task-positive mode) increases creative problem-solving by up to 40%.",
    instruction: "Each dot on the grid represents a different internal advisor — the analyst, the dreamer, the protector, the rebel, and others. Place dots to map which advisors are currently active in your thinking and which are silent. Tap any advisor dot to hear their perspective on your current challenge.",
  },
  {
    id: "tpn-dmn-crossing",
    name: "Crossing the River: TPN/DMN",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "spectrumSlider",
    whyNow: "You wrote about difficulty switching between focused work and creative thinking — understanding your TPN/DMN balance can help you navigate between them intentionally.",
    science: "The Task Positive Network (TPN) and Default Mode Network (DMN) are anticorrelated — when one activates, the other suppresses. However, creative insight requires brief simultaneous co-activation. The ability to fluidly transition between these networks, mediated by the salience network (anterior insula, dACC), predicts creative output.",
    instruction: "Drag the slider between Task Focus (TPN) on the left and Open Wandering (DMN) on the right. The exercise will guide you through deliberate transitions — spending time at each end before finding the creative crossing point in the middle where both networks briefly co-activate.",
  },
  {
    id: "valugration",
    name: "Valugration",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "vennOverlap",
    whyNow: "Your entry revealed a values conflict — you want two things that seem incompatible. This exercise finds the integration point where both values can coexist.",
    science: "Values conflicts activate the ventromedial prefrontal cortex and anterior cingulate cortex simultaneously, creating cognitive dissonance. Resolution comes not from choosing one value but from finding a higher-order integration — a process that engages the rostrolateral PFC, the brain region responsible for relational reasoning and abstraction.",
    instruction: "Place one value in the left circle and the competing value in the right circle. In each circle, list what that value gives you and what it costs. Then drag items into the overlap zone where both values are honored. The overlap is your valugration — the integrated expression of both.",
  },
  {
    id: "abc-model",
    name: "ABC Model",
    modality: "cognitive",
    originator: "REBT / Albert Ellis",
    primitive: "splitAnnotator",
    whyNow: "You described a strong emotional reaction to something that happened — the ABC model can help you see the belief between the event and the emotion that is driving the intensity.",
    science: "Ellis's ABC model maps directly to appraisal theory in affective neuroscience: the activating event (A) triggers a belief (B) in the medial prefrontal cortex, which generates the consequence (C) via amygdala-cortical feedback loops. Modifying B changes C because beliefs literally shape the neural prediction that determines emotional output.",
    instruction: "In the left column, describe the Activating event — just the facts. In the right column, identify the Belief you held about the event and the emotional/behavioral Consequence that followed. The split view helps you see that the same event with a different belief would produce a different consequence.",
  },
  {
    id: "dibs",
    name: "DIBs: Disputing Irrational Beliefs",
    modality: "cognitive",
    originator: "REBT / Albert Ellis",
    primitive: "hierarchicalBranch",
    whyNow: "Your journal contained some absolute statements — 'always,' 'never,' 'must' — that may be irrational beliefs worth examining and disputing.",
    science: "Irrational beliefs (demandingness, catastrophizing, low frustration tolerance, global evaluation) activate rigid cognitive schemas in the dorsolateral PFC. Disputation forces re-evaluation through the ventrolateral PFC, weakening the automatic association between the belief and its emotional consequence through a process neuroscience calls 'memory reconsolidation.'",
    instruction: "The hierarchical tree starts with your irrational belief at the top. Branch downward through four disputation questions: Is it logical? Is it realistic? Is it helpful? What is a more effective belief? Each branch deepens the challenge until you arrive at a rational alternative at the bottom.",
  },
  {
    id: "check-the-facts",
    name: "Check the Facts",
    modality: "cognitive",
    originator: "DBT / Marsha Linehan",
    primitive: "splitAnnotator",
    whyNow: "You wrote about a situation with strong emotional charge — checking the facts can help you separate what actually happened from the interpretations your threat system added.",
    science: "Emotions are generated by appraisals, not events. The amygdala responds to perceived threat faster than the cortex can verify accuracy. DBT's Check the Facts protocol engages the dorsolateral prefrontal cortex to re-evaluate the appraisal, reducing emotional intensity when the facts do not support the initial threat assessment.",
    instruction: "In the left column, write the prompting event and your initial emotional reaction. In the right column, answer each fact-checking question: What emotion am I feeling? What triggered it? What are my interpretations? What are the actual facts? Does my emotion fit the facts? The contrast between columns reveals where interpretation diverged from reality.",
  },
  {
    id: "signal-and-story",
    name: "Signal and Story",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "splitAnnotator",
    whyNow: "Your entry blended what happened with what it meant to you — teasing apart the signal (data) from the story (interpretation) can reduce emotional reactivity and reveal new choices.",
    science: "The brain automatically constructs narratives from sensory data via the left-hemisphere interpreter (Gazzaniga). This process is so fast that we experience our stories as facts. Deliberately separating signal from story engages the right dorsolateral PFC, interrupting confabulation and allowing more accurate reality testing.",
    instruction: "In the left column, write only the raw signals — what you saw, heard, or sensed without any interpretation. In the right column, write the stories your mind created about those signals. Seeing them side by side makes it easier to hold the story lightly and respond to the signal directly.",
  },
  {
    id: "cognitive-defusion",
    name: "Cognitive Defusion",
    modality: "cognitive",
    originator: "ACT",
    primitive: "guided",
    whyNow: "You wrote about a thought that feels absolutely true and is causing you pain — defusion techniques can help you see it as a thought rather than a fact, which loosens its grip.",
    science: "Cognitive fusion occurs when the literal content of thoughts dominates behavior, mediated by overactivation of the language network (Broca's and Wernicke's areas). Defusion techniques reduce the behavioral influence of thoughts without changing their content, measurably decreasing activity in the default mode network's self-referential processing regions.",
    instruction: "Follow the guided prompts to take a sticky thought and practice seeing it from a distance. You will be asked to restate the thought in different formats — prefixing it with 'I notice I am having the thought that...', singing it, or saying it in a funny voice. Notice how the thought's grip changes even though the words stay the same.",
  },
  {
    id: "creative-hopelessness",
    name: "Creative Hopelessness",
    modality: "cognitive",
    originator: "ACT",
    primitive: "forceField",
    whyNow: "Your journal described continuing to try strategies that are not working — this exercise helps you honestly inventory what you have tried so you can stop doing more of what does not work.",
    science: "Experiential avoidance — trying to control or eliminate unwanted internal experiences — is maintained by intermittent reinforcement and short-term relief that masks long-term costs. Creative hopelessness leverages the anterior cingulate cortex's conflict-detection function to make the futility of the control agenda consciously visible.",
    instruction: "On the left side of the force field, list everything you have tried to fix, control, or eliminate the difficult experience. On the right side, note the long-term result of each attempt. The pattern that emerges — trying harder at strategies that do not work — is the creative hopelessness that opens the door to a fundamentally different approach.",
  },
  {
    id: "both-and-reset",
    name: "Both/And Reset",
    modality: "cognitive",
    originator: "Integration",
    primitive: "vennOverlap",
    whyNow: "Your entry framed a situation as either/or — this exercise helps you hold two seemingly contradictory truths at the same time, which often reveals a more complete picture.",
    science: "Binary thinking is a cognitive shortcut mediated by the left hemisphere's categorization bias. Holding paradox requires bilateral prefrontal activation and increased connectivity between the default mode and frontoparietal networks. Tolerance for ambiguity, trainable through exercises like this, correlates with greater psychological flexibility and reduced anxiety.",
    instruction: "Place one side of the dilemma in the left circle and the other in the right. List the truth in each perspective. Then explore the overlap — what becomes possible when both are true simultaneously? The integration zone is where both/and thinking lives.",
  },
  {
    id: "three-truths",
    name: "Three Truths",
    modality: "cognitive",
    originator: "Integration",
    primitive: "narrativeTriptych",
    whyNow: "You described a situation where you feel certain about your interpretation — exploring two alternative truths alongside yours can reveal blind spots your certainty is hiding.",
    science: "Cognitive certainty correlates with reduced exploratory behavior and decreased dorsolateral PFC activation. Generating alternative explanations forces the brain into hypothesis-testing mode, activating the rostrolateral prefrontal cortex and increasing epistemic humility — a state associated with better decision-making and reduced confirmation bias.",
    instruction: "The triptych shows three panels. In the first, write the truth as you currently see it. In the second, write an alternative truth that someone who disagrees with you might hold. In the third, write a truth that transcends or integrates both. Reading all three side by side expands your perspective.",
  },
  {
    id: "pattern-name",
    name: "Pattern Name",
    modality: "cognitive",
    originator: "Neuroscience",
    primitive: "saboteurCard",
    whyNow: "Your journal revealed a recurring pattern — the same kind of situation keeps producing the same reaction. Naming the pattern gives you power over it.",
    science: "Naming activates the ventrolateral prefrontal cortex, which dampens amygdala reactivity by approximately 50% through a process called affect labeling. When a pattern has a name, the brain can detect it earlier in future instances, shifting from automatic reaction to conscious recognition — the first step in changing any habit loop.",
    instruction: "The card presents a framework for identifying and naming your pattern. Give it a vivid, memorable name — something that makes you smile or wince with recognition. Describe its trigger, its moves, and its usual outcome. Once named, this pattern becomes something you can spot in real time instead of only in hindsight.",
  },
  {
    id: "priority-language",
    name: "Priority Language Reframe",
    modality: "cognitive",
    originator: "Cognitive",
    primitive: "splitAnnotator",
    whyNow: "You used the phrase 'I have to' several times in your journal — shifting from obligation language to priority language can restore your sense of agency.",
    science: "Language shapes neural processing through the Sapir-Whorf pathway: obligation framing ('I have to') activates threat and compliance circuits, while choice framing ('I choose to') engages the ventromedial PFC and increases intrinsic motivation. Self-determination theory research confirms that perceived autonomy is a fundamental psychological need that directly impacts well-being.",
    instruction: "In the left column, write statements using obligation language — 'I have to,' 'I should,' 'I must.' In the right column, reframe each one using priority language — 'I choose to,' 'I want to,' 'It is important to me to.' Notice which reframes feel true and which reveal that something is not actually your priority.",
  },
  {
    id: "not-yet",
    name: "\"Not Yet\"",
    modality: "cognitive",
    originator: "Carol Dweck",
    primitive: "guided",
    whyNow: "Your entry contained statements about what you cannot do — adding 'yet' to each one activates a growth mindset that keeps the door open to learning.",
    science: "Dweck's research shows that a single word — 'yet' — shifts neural processing from fixed-trait evaluation (medial PFC self-referential network) to learning-oriented processing (dorsolateral PFC, hippocampus). ERP studies reveal that growth-mindset framing increases the error positivity signal, meaning the brain treats mistakes as learning opportunities rather than threats.",
    instruction: "Follow the guided prompts to identify statements about your abilities that feel fixed and final. For each one, you will practice adding 'not yet' and noticing how the felt sense changes. The exercise closes by identifying one concrete next step for each 'not yet' statement.",
  },
  {
    id: "scientists-lab",
    name: "Scientist's Lab",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "guided",
    whyNow: "You described a situation where you are unsure what to do next — approaching it as a scientist running experiments removes the pressure to get it right and replaces it with curiosity.",
    science: "Adopting an experimental mindset shifts processing from the evaluative medial PFC (which triggers rumination) to the exploratory dorsolateral PFC and anterior cingulate (which support hypothesis testing). This reframe reduces performance anxiety by recategorizing outcomes from 'success/failure' to 'data,' lowering cortisol and increasing cognitive flexibility.",
    instruction: "Follow the guided prompts to design a small experiment about your current challenge. You will define your hypothesis, your test conditions, what you will observe, and how long you will run it. The goal is not to find the answer but to generate useful data through action.",
  },
  {
    id: "heal-encoding",
    name: "HEAL: Encoding Positive Experiences",
    modality: "cognitive",
    originator: "Rick Hanson",
    primitive: "emotionalArc",
    whyNow: "Your journal focused heavily on what went wrong — HEAL helps you deliberately encode the positive experiences that your negativity bias is filtering out.",
    science: "The brain's negativity bias means negative experiences are encoded in one trial while positive experiences need 15-30 seconds of sustained attention to transfer from short-term to long-term memory via hippocampal consolidation. Hanson's HEAL steps (Have, Enrich, Absorb, Link) systematically ensure positive experiences get the encoding time they need.",
    instruction: "The emotional arc walks you through four stages. First, Have a positive experience by noticing or recalling something good. Then Enrich it by staying with it, feeling it in your body, and expanding its dimensions. Absorb it by sensing it sinking into you. Finally, Link it by holding it alongside something difficult to create new positive associations.",
  },
  {
    id: "neuroplasticity-mapping",
    name: "Neuroplasticity Mapping",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "splitAnnotator",
    whyNow: "You mentioned wanting to change a deep-seated pattern — mapping the old neural pathway alongside the new one you are building helps you see the rewiring in progress.",
    science: "Neuroplasticity follows Hebb's rule: neurons that fire together wire together. Existing patterns have strong synaptic connections due to long-term potentiation. New patterns require repeated activation, emotional engagement, and adequate sleep for consolidation. Explicitly mapping both pathways engages metacognitive circuits that accelerate the rewiring process.",
    instruction: "In the left column, map the old pathway — trigger, automatic thought, habitual behavior, usual result. In the right column, map the new pathway you are building — same trigger, chosen thought, intentional behavior, desired result. Seeing both side by side helps you notice when you are on the old path and consciously switch to the new one.",
  },
  {
    id: "three-circles",
    name: "Three Circles of Influence",
    modality: "cognitive",
    originator: "Stephen Covey",
    primitive: "cardSort",
    whyNow: "Your entry revealed stress about things outside your control — sorting your concerns into circles of control, influence, and concern can redirect your energy to where it actually works.",
    science: "Perceived lack of control activates the hypothalamic-pituitary-adrenal axis, flooding the system with cortisol. Covey's model maps to learned helplessness research: focusing on what you can control restores dorsolateral PFC engagement and reduces amygdala activation, breaking the helplessness cycle and restoring self-efficacy.",
    instruction: "Sort the cards representing your current concerns into three categories: Control (you can directly act on these), Influence (you can affect these through relationships or effort), and Concern (these matter to you but are outside your power). Once sorted, you will focus energy on the first two categories and practice releasing the third.",
  },
  {
    id: "hov",
    name: "HOV: Hierarchy of Values",
    modality: "cognitive",
    originator: "Values Work",
    primitive: "bubbleSort",
    whyNow: "Your journal mentioned feeling pulled in too many directions — clarifying which values sit highest in your hierarchy can simplify complex decisions.",
    science: "Values act as top-down priors in the ventromedial prefrontal cortex, biasing attention and decision-making toward valued outcomes. When values are unclear or conflicting, the anterior cingulate cortex generates distress signals. Explicit hierarchy reduces decisional conflict and increases the speed and confidence of value-congruent choices.",
    instruction: "You will see pairs of values appear one at a time. For each pair, choose the one that matters more to you right now — not in theory, but in practice. The bubble sort algorithm will use your choices to build a ranked hierarchy. Your top values will rise to the surface naturally through repeated comparison.",
  },
  {
    id: "values-clarification",
    name: "Values Clarification",
    modality: "cognitive",
    originator: "Co-Active / CTI",
    primitive: "wordCloud",
    whyNow: "You wrote about feeling disconnected from what matters to you — a values clarification exercise can reconnect you to the principles that give your life meaning and direction.",
    science: "Self-affirmation theory shows that reflecting on core values activates the ventromedial prefrontal cortex and reduces defensive processing in the amygdala. Values clarity is one of the strongest predictors of psychological well-being, correlating with lower depression scores and greater resilience in longitudinal studies.",
    instruction: "Tap words from the cloud that resonate with you — values that light up when you read them. You can add your own words too. As you select, the cloud will reorganize to highlight your choices. Narrow down to your top five, then rank them. Your values cloud becomes a visual anchor you can return to when making difficult decisions.",
  },
  {
    id: "values-decision",
    name: "Values-Based Decision Making",
    modality: "cognitive",
    originator: "ACT",
    primitive: "forcedChoice",
    whyNow: "You described being stuck on a decision — running each option through your values filter can reveal which choice moves you toward the life you actually want.",
    science: "Decision-making under uncertainty engages a tug-of-war between the habitual system (dorsal striatum) and the goal-directed system (ventromedial PFC). Values-based decision-making tips the balance toward the goal-directed system, improving long-term outcome quality even when the habitual choice feels easier in the moment.",
    instruction: "You will be presented with your decision and two or more options. For each option, you must choose whether it aligns with or moves away from each of your core values. The forced-choice format prevents fence-sitting — you must commit to a direction for each value, and the overall pattern will reveal which option is most values-congruent.",
  },
  {
    id: "success-habit-audit",
    name: "Success Habit Audit",
    modality: "cognitive",
    originator: "Marshall Goldsmith",
    primitive: "cardSort",
    whyNow: "You mentioned habits that got you to where you are — Goldsmith's insight is that what got you here may not get you there. An audit can reveal which habits to keep, modify, or release.",
    science: "Habitual behaviors are encoded in the basal ganglia and execute automatically, freeing prefrontal resources. However, context-dependent habits can become maladaptive when contexts change. The audit process engages the dorsolateral PFC to evaluate habits that the basal ganglia runs without conscious review, enabling intentional updates.",
    instruction: "Sort your current success habits into three categories: Keep (still serving you), Modify (partially useful but needs updating), and Release (once helpful but now holding you back). Be honest about habits that feel like identity — sometimes the hardest ones to release are the ones that defined an earlier version of you.",
  },
  {
    id: "miracle-question",
    name: "Miracle Question",
    modality: "cognitive",
    originator: "SFBT",
    primitive: "guided",
    whyNow: "Your journal expressed feeling overwhelmed by the complexity of your situation — the miracle question bypasses the problem entirely and helps you envision the solution state directly.",
    science: "The miracle question activates prospective memory circuits in the hippocampus and the brain's simulation network (default mode network) to construct a detailed future scenario. This 'mental time travel' engages the same neural substrates as actual experience, creating new goal representations that the brain can work backward from to identify action steps.",
    instruction: "Follow the guided prompt: Imagine you go to sleep tonight and a miracle happens — the problem is completely solved. You do not know it happened because you were asleep. What is the first thing you notice when you wake up that tells you things are different? Describe the details of this miracle morning in vivid, specific terms.",
  },
  {
    id: "scaling-questions",
    name: "Scaling Questions",
    modality: "cognitive",
    originator: "SFBT",
    primitive: "spectrumSlider",
    whyNow: "You wrote about progress feeling invisible — scaling makes even small shifts visible by giving them a number and anchoring what is already working.",
    science: "Scaling questions leverage the brain's magnitude estimation system (intraparietal sulcus) to convert subjective experience into a quantifiable metric. This numerical anchoring activates the dorsolateral PFC's working memory and comparison functions, making progress tangible and reducing the all-or-nothing thinking associated with amygdala-driven evaluation.",
    instruction: "Drag the slider to rate where you are right now on a scale of 1 to 10, where 10 is the problem fully resolved. Then answer: What makes it that number and not lower? What would one point higher look like? The first question reveals existing resources; the second reveals the next small step.",
  },
  {
    id: "exception-finding",
    name: "Exception Finding",
    modality: "cognitive",
    originator: "SFBT",
    primitive: "guided",
    whyNow: "Your entry described a problem as if it is always present — finding exceptions, times when the problem was absent or less intense, reveals solutions you are already using without realizing it.",
    science: "The brain's negativity bias and attentional narrowing during stress cause 'always/never' thinking by suppressing retrieval of counter-examples from episodic memory. Exception-finding directly counters this by cuing the hippocampus to search for disconfirming instances, reactivating solution-focused neural pathways that stress had suppressed.",
    instruction: "Follow the guided prompts to recall times when the problem was not happening or was less severe. What was different about those times? What were you doing, thinking, or feeling? Who was around? The exceptions contain the seeds of your solution — they reveal your existing competence.",
  },
  {
    id: "saboteur-check",
    name: "Saboteur Check",
    modality: "cognitive",
    originator: "Positive Intelligence / Shirzad Chamine",
    primitive: "saboteurCard",
    whyNow: "Your journal entry had the voice of an inner critic — identifying which saboteur is speaking helps you see it as a pattern rather than the truth about you.",
    science: "Chamine's saboteurs map to survival-brain circuits: the Judge activates the dorsal anterior cingulate (self-criticism), the Controller activates the lateral PFC (rigidity), the Avoider suppresses the anterior insula (emotional numbing). Naming the saboteur engages metacognitive networks that create separation between the pattern and the self.",
    instruction: "The card presents the ten saboteur archetypes. Read through each and identify the one (or two) that showed up in your recent thinking. Once identified, the card flips to reveal the saboteur's lie, its origin story, and the sage power that can counter it. Name it to tame it.",
  },
  {
    id: "saboteur-inner-leader",
    name: "Saboteur & Inner Leader",
    modality: "cognitive",
    originator: "Co-Active / CTI",
    primitive: "dialogueSequence",
    whyNow: "You described an internal battle between the part of you that holds back and the part that wants to step forward — giving both a voice can resolve the stalemate.",
    science: "Internal dialogue between competing self-aspects activates the medial prefrontal cortex (self-referential processing) and temporoparietal junction (perspective-taking). Making the dialogue explicit, rather than letting it run implicitly, engages the dorsolateral PFC as a mediator, enabling integration rather than suppression of the less-dominant voice.",
    instruction: "A guided dialogue will alternate between your saboteur and your inner leader. First, give the saboteur full voice — let it say everything it wants to say. Then let the inner leader respond from a place of wisdom, not dismissal. Each round deepens the conversation until both voices feel heard and a way forward emerges.",
  },
  {
    id: "cba",
    name: "CBA: Cost-Benefit Analysis",
    modality: "cognitive",
    originator: "CBT",
    primitive: "forceField",
    whyNow: "You are weighing a difficult decision — a structured cost-benefit analysis can bypass the emotional noise and show you where the actual weight of evidence falls.",
    science: "Decision-making involves competition between the emotional valuation system (ventromedial PFC, amygdala) and the analytical evaluation system (dorsolateral PFC). A formal CBA externalizes the process, reducing working memory load and allowing more thorough evaluation by preventing the emotional system from dominating through salience bias.",
    instruction: "On the left side, list all the costs — what you lose, risk, or sacrifice. On the right side, list all the benefits — what you gain, preserve, or create. Then weight each item by importance. The force field visualization makes the balance of forces visible so you can make a decision grounded in evidence rather than anxiety.",
  },
  {
    id: "five-questions",
    name: "Five Questions Reality Testing",
    modality: "cognitive",
    originator: "CBT",
    primitive: "forcedChoice",
    whyNow: "You expressed a strong belief about a situation — running it through five reality-testing questions can reveal whether the belief is serving you or distorting your perception.",
    science: "Core beliefs operate as cognitive schemas in the medial prefrontal cortex, filtering perception to confirm existing models. Reality testing engages the dorsolateral PFC to evaluate evidence for and against the belief, weakening schema-driven processing. Studies show that structured Socratic questioning reduces belief conviction ratings and associated emotional distress.",
    instruction: "You will be presented with five questions about your belief, one at a time. For each, you must choose the response that is most honest, not most comfortable. The questions are: What is the evidence for this belief? What is the evidence against it? Is there an alternative explanation? What is the worst that could happen — and could I cope? What would I tell a friend?",
  },
  {
    id: "workability",
    name: "Workability Assessment",
    modality: "cognitive",
    originator: "ACT",
    primitive: "forcedChoice",
    whyNow: "Your journal described continuing a behavior even though it is not producing the results you want — assessing workability helps you ask 'is this working?' instead of 'is this right?'",
    science: "ACT replaces the truth criterion with the workability criterion: rather than debating whether a thought is true, it asks whether acting on it moves you toward your values. This shift bypasses the rumination loop in the default mode network and engages the ventromedial PFC's outcome evaluation function, focusing on behavioral consequences rather than logical truth.",
    instruction: "For each behavior or strategy you are currently using, you must make a forced choice: Is this working — moving me toward who and what I want to be? Or is this not working — keeping me stuck or moving me away? There is no middle ground in this exercise. The pattern of your choices reveals where change is most needed.",
  },
  {
    id: "authentic-living",
    name: "Authentic Living Practice",
    modality: "cognitive",
    originator: "ACT",
    primitive: "forcedChoice",
    whyNow: "You wrote about feeling like you are performing a role rather than being yourself — this exercise identifies where the gap between your public behavior and private values is widest.",
    science: "Authenticity correlates with increased medial prefrontal cortex coherence and decreased cognitive load, because maintaining a false self requires constant prefrontal monitoring and suppression. The gap between authentic and performed self activates the anterior cingulate cortex conflict signal, producing the chronic low-grade stress described as 'inauthenticity.'",
    instruction: "For each life domain presented, make a forced choice: Am I living authentically here — in alignment with my values and true self? Or am I performing — doing what I think I should, what others expect, or what feels safe? The domains where you are performing are where the biggest gains in well-being and energy are available.",
  },
  {
    id: "metaphor",
    name: "Metaphor & Meta-Metaphor",
    modality: "cognitive",
    originator: "BEabove Leadership",
    primitive: "guided",
    whyNow: "Your journal used vivid imagery to describe your situation — following that metaphor deeper can reveal insights your analytical mind has been missing.",
    science: "Metaphors are not merely linguistic — they are cognitive structures that shape perception and reasoning (Lakoff & Johnson). Metaphorical processing engages the right hemisphere's pattern-recognition and the angular gyrus's cross-modal mapping. A meta-metaphor (a metaphor about the metaphor) activates recursive processing in the rostrolateral PFC, enabling insight at a higher level of abstraction.",
    instruction: "Follow the guided prompts to explore a metaphor for your current situation. First, name the metaphor — what is your situation like? Then, enter the metaphor fully — explore its landscape, characters, and rules. Finally, step into the meta-metaphor: what is the metaphor itself telling you? What does the fact that you chose this particular image reveal?",
  },
  {
    id: "meta-view",
    name: "Meta-View",
    modality: "cognitive",
    originator: "Co-Active / CTI",
    primitive: "guided",
    whyNow: "You seem deeply embedded in the details of your situation — stepping back to the meta-view can reveal the larger pattern or theme that the details are an expression of.",
    science: "The meta-view engages the brain's capacity for hierarchical abstraction, mediated by the rostrolateral prefrontal cortex. This region supports relational reasoning — the ability to see relationships between relationships. Accessing the meta-view deactivates the detail-focused dorsal attention network and activates the big-picture default mode network's scene-construction function.",
    instruction: "Follow the guided prompts to zoom out from your current concern. What is the bigger picture here? If this situation is a chapter, what is the book about? What theme or lesson keeps appearing in different forms? The meta-view does not solve the problem — it reframes it in a way that often makes the solution obvious.",
  },
  {
    id: "living-question",
    name: "Inquiry: Living Question",
    modality: "cognitive",
    originator: "Co-Active / CTI",
    primitive: "guided",
    whyNow: "Your entry circled around the same topic without resolving it — a living question gives you something powerful to carry without needing to answer it immediately.",
    science: "Open questions activate the brain's default mode network in a productive way — priming the hippocampus and association cortices to unconsciously search for connections. This is the mechanism behind 'sleeping on it': an unresolved question continues to be processed during DMN activity, including sleep, often producing insight during seemingly unrelated moments.",
    instruction: "Follow the guided prompts to craft a question you are willing to live with for a while. It should be open, genuine, and slightly uncomfortable. Not 'How do I fix this?' but something like 'What am I not seeing?' or 'What would it mean to let this be enough?' Carry this question with you and notice what answers emerge organically.",
  },
  {
    id: "crucial-conversation",
    name: "Crucial Conversation Prep",
    modality: "cognitive",
    originator: "Patterson et al.",
    primitive: "narrativeTriptych",
    whyNow: "You mentioned a conversation you are dreading — preparing for it using the crucial conversation framework can help you show up grounded instead of reactive.",
    science: "Crucial conversations trigger the fight-or-flight response because high stakes, differing opinions, and strong emotions activate the amygdala simultaneously. Preparation engages prospective memory (hippocampus) and pre-commits the dorsolateral PFC to specific behavioral scripts, reducing the likelihood of amygdala hijack during the actual conversation.",
    instruction: "The triptych has three panels. In the first, write your story — your perspective, feelings, and what you want. In the second, write their story — your best guess at their perspective, feelings, and goals. In the third, write the shared story — the mutual purpose and mutual respect that you want to establish. Preparing all three reduces the chance of getting locked into just your own narrative.",
  },
  {
    id: "one-thing",
    name: "The ONE Thing",
    modality: "cognitive",
    originator: "Gary Keller",
    primitive: "bubbleSort",
    whyNow: "Your journal listed multiple priorities competing for your attention — finding the ONE thing that makes everything else easier or unnecessary can cut through the overwhelm.",
    science: "Multitasking is a myth — the prefrontal cortex task-switches, it does not parallel-process. Each switch costs approximately 20 minutes of deep focus (cognitive switching penalty). Identifying a single priority reduces anterior cingulate conflict signals and allows the dorsolateral PFC to apply sustained attention, which is where the highest-quality cognitive work happens.",
    instruction: "You will see your current priorities paired against each other. For each pair, choose the one that is more important — the one that, if accomplished, would make the other easier or unnecessary. The bubble sort will progressively surface your ONE thing to the top through forced comparisons.",
  },
  {
    id: "essentialism",
    name: "Essentialism Filter",
    modality: "cognitive",
    originator: "Greg McKeown",
    primitive: "cardSort",
    whyNow: "You described saying yes to too many things — the essentialism filter helps you identify the vital few from the trivial many so you can contribute at your highest level.",
    science: "Decision fatigue depletes prefrontal glucose reserves, progressively shifting control to the impulsive basal ganglia. McKeown's filter reduces decision load by pre-committing to clear criteria. Research on choice architecture shows that constraining options paradoxically increases satisfaction and performance by reducing the cognitive overhead of maintaining too many commitments.",
    instruction: "Sort your current commitments into three categories: Hell Yes (deeply aligned with your purpose and you are uniquely positioned to contribute), Neutral (good but not essential — someone else could do this), and No (not aligned, draining, or performative). The goal is a ruthless edit — if it is not a Hell Yes, it is a No.",
  },
  {
    id: "agreement-certainty",
    name: "Agreement-Certainty Matrix",
    modality: "cognitive",
    originator: "Liberating Structures / Cynefin",
    primitive: "dotGrid",
    whyNow: "You are facing a complex situation and trying to apply simple solutions — mapping where it actually falls on the agreement-certainty matrix can match your response to the real nature of the challenge.",
    science: "The Cynefin framework maps to distinct neural processing modes: simple domains use cached basal ganglia routines, complicated domains engage dorsolateral PFC analytical reasoning, complex domains require the default mode network's pattern detection, and chaotic domains activate the salience network's rapid triage function. Mismatching strategy to domain produces consistently poor outcomes.",
    instruction: "The dot grid has two axes: agreement (do stakeholders agree on what to do?) and certainty (can we predict the outcome?). Place a dot where your current challenge sits. The quadrant it falls in — simple, complicated, complex, or chaotic — determines the right approach. You will receive strategy guidance matched to the correct domain.",
  },
  {
    id: "thought-record",
    name: "CBT Seven-Column Thought Record",
    modality: "cognitive",
    originator: "Aaron Beck",
    primitive: "splitAnnotator",
    whyNow: "You described a distressing emotional reaction — a thought record can help you trace it back to the specific automatic thought driving it and test that thought against evidence.",
    science: "Beck's cognitive model posits that automatic thoughts mediate between events and emotions via core beliefs. The seven-column record systematically engages the dorsolateral PFC to evaluate evidence, identify distortions, and generate balanced alternatives — a process that weakens maladaptive neural pathways through cognitive restructuring and Hebbian unlearning.",
    instruction: "In the columns from left to right, record: the situation, the automatic thought, the emotion and its intensity, evidence supporting the thought, evidence against it, a balanced alternative thought, and your emotion re-rating. The split view helps you see the full chain from trigger to reappraisal and track whether the balanced thought actually shifts the emotion.",
  },
  {
    id: "distortions-checklist",
    name: "Cognitive Distortions Checklist",
    modality: "cognitive",
    originator: "David Burns",
    primitive: "splitAnnotator",
    whyNow: "Your journal contained thinking patterns that may be distortions — checking them against Burns's list can help you catch the specific biases your mind tends to favor.",
    science: "Cognitive distortions are systematic errors in information processing maintained by confirmation bias and schema-driven attention. Each distortion maps to a specific neural shortcut: catastrophizing amplifies amygdala threat signals, personalization overactivates the medial PFC self-referential network, and all-or-nothing thinking reflects left-hemisphere categorization dominance.",
    instruction: "In the left column, write the thought that is bothering you. In the right column, check it against the ten distortions: all-or-nothing thinking, overgeneralization, mental filter, disqualifying the positive, jumping to conclusions, magnification, emotional reasoning, should statements, labeling, and personalization. Identifying the distortion type immediately loosens its grip.",
  },
  {
    id: "behavioral-experiment",
    name: "Behavioral Experiment",
    modality: "cognitive",
    originator: "CBT",
    primitive: "beforeAfter",
    whyNow: "You hold a belief about what would happen if you acted differently — rather than debating it internally, a behavioral experiment lets reality provide the answer.",
    science: "Behavioral experiments are more effective than verbal disputation at changing core beliefs because they provide experiential evidence that bypasses the cognitive defense mechanisms protecting the schema. New experiential data is encoded through the hippocampus and amygdala simultaneously, creating emotional learning that updates the belief at a deeper level than intellectual argument alone.",
    instruction: "In the Before section, state your prediction: what you believe will happen, how confident you are (0-100%), and what you will do to test it. After running the experiment, fill in the After section: what actually happened, your new confidence rating, and what you learned. The gap between prediction and outcome is where belief change occurs.",
  },
  {
    id: "worry-time",
    name: "Worry Time Protocol",
    modality: "cognitive",
    originator: "CBT",
    primitive: "guided",
    whyNow: "You described worry intruding throughout your day — the worry time protocol contains it in a specific window so the rest of your day is freed up.",
    science: "Worry is maintained by negative reinforcement: worrying temporarily reduces anxiety (via the illusion of control), which reinforces the worrying behavior. Scheduled worry time works by stimulus control — breaking the association between random cues and worry responses. Research shows this reduces total worry time by 35-50% within two weeks by containing the behavior within a defined context.",
    instruction: "Follow the guided prompts to set up your worry time practice. Choose a specific 15-minute window each day. During that window, worry deliberately and thoroughly. Outside the window, when worry arises, note it and postpone it to your worry time. This is not suppression — it is scheduling. You will find that by the time worry time arrives, many worries have dissolved on their own.",
  },
  {
    id: "decatastrophizing",
    name: "Decatastrophizing Ladder",
    modality: "cognitive",
    originator: "CBT",
    primitive: "hierarchicalBranch",
    whyNow: "Your entry jumped to the worst-case scenario — the decatastrophizing ladder brings you back down to earth by mapping the full range of possible outcomes.",
    science: "Catastrophizing activates the amygdala's threat magnification circuit and suppresses the ventromedial PFC's probability estimation function. The ladder technique re-engages probabilistic reasoning by forcing the brain to generate best-case and most-likely scenarios alongside the worst case, restoring the dorsolateral PFC's balanced evaluation of outcome likelihood.",
    instruction: "The hierarchical tree starts with your catastrophic prediction at the top. Branch downward through three levels: What is the worst that could happen? What is the best that could happen? What is most likely to happen? For each level, rate probability and copeability. The tree structure makes it visually clear that the catastrophe is one low-probability branch among many.",
  },
  {
    id: "stars-diagnosis",
    name: "STARS Situational Diagnosis",
    modality: "cognitive",
    originator: "Michael Watkins",
    primitive: "multiSpectrum",
    whyNow: "You are navigating a transition at work — correctly diagnosing what type of situation you have landed in determines which leadership strategies will actually work.",
    science: "Watkins's STARS framework (Start-up, Turnaround, Accelerated growth, Realignment, Sustaining success) maps to different cognitive demands. Start-ups require divergent thinking (right PFC), turnarounds need rapid threat assessment (amygdala + dACC), and realignment demands persuasion circuits (temporoparietal junction). Misdiagnosing the situation activates the wrong neural toolkit.",
    instruction: "The multi-spectrum display shows five dimensions of the STARS model. Rate where your current situation falls on each spectrum. The resulting profile reveals whether you are in a start-up, turnaround, accelerated growth, realignment, or sustaining success scenario — and the guidance that follows is calibrated to the specific demands of your situation type.",
  },

  // ═══════════════════════════════════════════
  // SOMATIC EXERCISES (51–75)
  // ═══════════════════════════════════════════

  {
    id: "window-of-tolerance",
    name: "Window of Tolerance Tracking",
    modality: "somatic",
    originator: "Polyvagal / Dan Siegel",
    primitive: "zonedSpectrum",
    whyNow: "You described swinging between shutdown and overwhelm — tracking your window of tolerance helps you notice where you are before you hit the edge.",
    science: "Siegel's window of tolerance maps to the polyvagal hierarchy: the ventral vagal zone (social engagement) is the window, sympathetic activation (fight/flight) is hyperarousal above it, and dorsal vagal (freeze/collapse) is hypoarousal below it. Tracking builds interoceptive awareness via the insula, which is the neural prerequisite for regulation.",
    instruction: "The spectrum shows three zones: hyperarousal at the top, the window of tolerance in the middle, and hypoarousal at the bottom. Tap where you are right now. The colored zones help you identify your current nervous system state, and the guidance that appears is specific to bringing you back toward the window from wherever you are.",
  },
  {
    id: "nervous-system-titration",
    name: "Nervous System Titration",
    modality: "somatic",
    originator: "Somatic Experiencing",
    primitive: "zonedSpectrum",
    whyNow: "Your journal described intense emotional material — titration helps you approach it in small, manageable doses instead of being overwhelmed by the full charge.",
    science: "Titration prevents retraumatization by keeping the nervous system within its window of tolerance during processing. Peter Levine's approach uses the principle of pendulation — moving between activation and resource — to gradually discharge trapped survival energy. This engages the ventral vagal complex to maintain social engagement while processing sympathetic arousal.",
    instruction: "The spectrum shows your current activation level from calm to overwhelmed. Drag the slider to where you are now. The exercise will guide you to approach the difficult material just enough to feel a small increase in activation, then pull back to your resource state. This back-and-forth gradually processes the charge without overwhelming your system.",
  },
  {
    id: "tipp",
    name: "TIPP",
    modality: "somatic",
    originator: "DBT / Marsha Linehan",
    primitive: "guided",
    whyNow: "You described intense emotional distress — TIPP is an emergency regulation tool that changes your body chemistry fast when thinking your way through it is not working.",
    science: "TIPP (Temperature, Intense exercise, Paced breathing, Progressive relaxation) works through direct physiological pathways that bypass cognitive processing. Cold temperature triggers the mammalian dive reflex via the trigeminal nerve, rapidly lowering heart rate. Intense exercise metabolizes stress hormones. Paced breathing activates the vagus nerve. Each component provides a bottom-up reset of the autonomic nervous system.",
    instruction: "Follow the guided steps in order: First, apply cold to your face (ice pack or cold water) for 30 seconds to trigger the dive reflex. Second, engage in intense physical activity for 5-10 minutes. Third, practice paced breathing — exhale longer than you inhale. Fourth, progressively relax each muscle group. Each step is timed and guided.",
  },
  {
    id: "stop-practice",
    name: "STOP Practice",
    modality: "somatic",
    originator: "DBT / Marsha Linehan",
    primitive: "guided",
    whyNow: "You wrote about reacting impulsively in a heated moment — STOP is a rapid-deployment skill for creating a gap between stimulus and response.",
    science: "The 200-millisecond window between stimulus detection (amygdala) and conscious awareness (prefrontal cortex) is where impulsive actions originate. STOP (Stop, Take a breath, Observe, Proceed mindfully) extends this window by engaging the anterior cingulate cortex's inhibition function, giving the prefrontal cortex time to come online before behavior is selected.",
    instruction: "Follow the four guided steps: Stop — physically freeze. Take a breath — one slow, deep breath. Observe — notice what you are feeling, thinking, and sensing. Proceed mindfully — choose your next action deliberately. Practice this sequence now with a recent triggering situation so it becomes automatic when you need it most.",
  },
  {
    id: "polyvagal-reset",
    name: "Polyvagal Reset",
    modality: "somatic",
    originator: "Stephen Porges",
    primitive: "guided",
    whyNow: "Your entry suggested your nervous system is stuck in a defensive state — this reset sequence moves you through the polyvagal ladder back toward ventral vagal safety.",
    science: "Porges's polyvagal theory describes three hierarchical states: ventral vagal (safe/social), sympathetic (fight/flight), and dorsal vagal (freeze/shutdown). The vagus nerve is the primary pathway for shifting states. Specific exercises — vocal toning, orienting, social engagement gestures — stimulate ventral vagal tone, measurably increasing heart rate variability and restoring the social engagement system.",
    instruction: "Follow the guided sequence: First, orient by slowly looking around the room, letting your eyes settle on things that feel neutral or pleasant. Second, hum or vocalize to stimulate the vagus nerve through the laryngeal muscles. Third, make a gentle social gesture — smile, soften your eyes. Notice how each step shifts your felt sense of safety.",
  },
  {
    id: "three-two-one",
    name: "3-2-1-1-2-3 Process",
    modality: "somatic",
    originator: "BEabove Leadership",
    primitive: "emotionalArc",
    whyNow: "You described a difficult emotional experience that you have not fully processed — this structured arc helps you move through it safely from activation to integration.",
    science: "The 3-2-1-1-2-3 process mirrors the natural arc of emotional processing: approach (3-2-1) deepens contact with the experience, and return (1-2-3) consolidates and integrates. This follows the somatic experiencing principle that incomplete emotional cycles get stored as implicit body memory. Completing the cycle allows the hippocampus to reconsolidate the memory with a new, resolved ending.",
    instruction: "The emotional arc guides you through six stages. First three (3-2-1): describe the experience in third person, then second person, then first person — each step brings you closer to the felt sense. Last three (1-2-3): reverse the process, moving from first person back to third person, creating distance and integration. Trust the process and move at the pace that feels manageable.",
  },
  {
    id: "somatic-grounding",
    name: "Somatic Grounding",
    modality: "somatic",
    originator: "Somatic Experiencing",
    primitive: "bodyMap",
    whyNow: "You wrote about feeling disconnected from your body or floating in your head — somatic grounding reconnects you to your physical foundation and the present moment.",
    science: "Grounding activates the somatosensory cortex and posterior insula, increasing interoceptive awareness and pulling attention away from the default mode network's rumination loops. Physical contact with the ground stimulates proprioceptive and mechanoreceptive pathways that signal safety to the nervous system, increasing ventral vagal tone.",
    instruction: "On the body map, tap the areas where you currently feel the most sensation — tingling, warmth, pressure, numbness, or anything else. Then follow the grounding prompts: feel your feet on the floor, your body in the chair, the weight of gravity. Tap the body map again to notice what shifted after grounding.",
  },
  {
    id: "five-four-three",
    name: "5-4-3-2-1 Grounding",
    modality: "somatic",
    originator: "DBT",
    primitive: "guided",
    whyNow: "You described anxiety pulling you into catastrophic futures — the 5-4-3-2-1 technique anchors you to the present moment through your senses.",
    science: "The 5-4-3-2-1 technique works by flooding the brain with current sensory input, which competes with and overrides anxiety-driven future simulation in the default mode network. Engaging all five senses activates the primary sensory cortices bilaterally, pulling processing resources away from the prefrontal worry loop and into present-moment exteroceptive awareness.",
    instruction: "Follow the guided prompts: Name 5 things you can see. 4 things you can touch (and touch them). 3 things you can hear. 2 things you can smell. 1 thing you can taste. Take your time with each sense — the goal is to fully arrive in the present moment through your sensory experience.",
  },
  {
    id: "box-breathing",
    name: "Box Breathing",
    modality: "somatic",
    originator: "Military / Clinical",
    primitive: "guided",
    whyNow: "Your entry described racing thoughts or difficulty calming down — box breathing is a fast, reliable way to shift your nervous system from sympathetic arousal to parasympathetic recovery.",
    science: "Box breathing (4-4-4-4 pattern) optimizes the respiratory-cardiac coupling that drives heart rate variability. The prolonged exhale and breath holds stimulate the vagus nerve, increasing parasympathetic output. Navy SEAL research shows this technique reduces cortisol within 90 seconds and improves cognitive performance under stress by restoring prefrontal cortex blood flow.",
    instruction: "Follow the guided breathing pattern: Inhale for 4 counts. Hold for 4 counts. Exhale for 4 counts. Hold for 4 counts. Repeat for 4-6 cycles. The visual guide will pace you. Focus on making each phase smooth and equal in duration. Notice the growing stillness between each cycle.",
  },
  {
    id: "body-scan",
    name: "Body Scan",
    modality: "somatic",
    originator: "Jon Kabat-Zinn",
    primitive: "bodyMap",
    whyNow: "You wrote about stress but could not pinpoint where it lives in your body — a body scan builds the mind-body connection that makes regulation possible.",
    science: "Body scanning increases posterior insular cortex activation, which is the primary hub for interoceptive awareness. Kabat-Zinn's MBSR research shows that regular body scanning increases gray matter density in the insula and somatosensory cortex, improving the resolution of body-state detection — you literally become better at knowing what you feel and where you feel it.",
    instruction: "On the body map, you will be guided through each region from feet to head. As attention moves to each area, tap the map to mark what you notice — tension, ease, warmth, cold, numbness, tingling. There is no right answer — the practice is pure noticing. The completed map gives you a snapshot of your body's current landscape.",
  },
  {
    id: "three-by-three",
    name: "3×3 Process",
    modality: "somatic",
    originator: "BEabove Leadership",
    primitive: "bodyMap",
    whyNow: "You are processing something emotionally complex — the 3×3 process gives you three different body-based entry points to understand what is happening beneath the surface.",
    science: "The 3×3 process leverages the fact that emotional information is distributed across multiple body systems: musculoskeletal tension (proprioception), visceral sensation (interoception), and energetic quality (autonomic tone). Accessing all three channels provides a more complete picture than any single channel alone, engaging a wider network of insular, somatosensory, and cingulate processing.",
    instruction: "On the body map, complete three passes. First pass: mark where you feel physical tension or holding. Second pass: mark where you feel emotional sensation — the gut feeling, the heart-heaviness, the throat-tightness. Third pass: mark the energy quality — where feels alive and where feels dead or numb. The three layers together reveal the full somatic picture.",
  },
  {
    id: "somatic-boundary",
    name: "Somatic Boundary Awareness",
    modality: "somatic",
    originator: "Somatic Experiencing",
    primitive: "bodyMap",
    whyNow: "Your journal described feeling invaded or overwhelmed by someone else's energy — this exercise helps you feel where your boundaries are in your body so you can hold them in relationship.",
    science: "Boundaries are not just psychological — they are somatically encoded. The peripersonal space network (a body-centered spatial mapping system in the parietal cortex) defines the felt sense of personal space. Trauma and attachment disruption can shrink or dissolve this boundary. Somatic boundary work rebuilds it by pairing interoceptive awareness with motor imagery of containment.",
    instruction: "On the body map, mark the areas that feel most permeable — where other people's emotions, opinions, or energy tend to seep in. Then mark the areas that feel solid and boundaried. The exercise will guide you through imagining a protective edge around the permeable areas, strengthening the somatic sense of where you end and others begin.",
  },
  {
    id: "whats-mine",
    name: "\"What's Mine?\" Emotional Sorting",
    modality: "somatic",
    originator: "Somatic / HSP",
    primitive: "bodyMap",
    whyNow: "You described carrying heavy emotions after an interaction — this exercise helps you distinguish between emotions that originate in you and those you absorbed from someone else.",
    science: "Mirror neurons and the empathy network (anterior insula, anterior cingulate cortex) can generate 'emotional contagion' — literally feeling others' emotions in your own body. Highly sensitive people show stronger mirror neuron activation and more permeable self-other boundaries in the temporoparietal junction. Sorting 'mine' from 'theirs' strengthens the self-other distinction circuit.",
    instruction: "On the body map, locate every sensation and emotion you are carrying right now. For each one, ask: Is this mine, or did I pick it up from someone else? Mark emotions that are yours in one color and absorbed emotions in another. For the absorbed ones, the exercise will guide you through a somatic release to return them to their owner.",
  },
  {
    id: "somatic-discharge",
    name: "Somatic Discharge",
    modality: "somatic",
    originator: "Peter Levine",
    primitive: "guided",
    whyNow: "You described pent-up energy or tension that will not release — Levine's somatic discharge process helps your body complete the survival response it was interrupted from finishing.",
    science: "Levine observed that animals discharge survival energy through involuntary movements — shaking, trembling, deep breathing — after a threat passes. In humans, this discharge is often suppressed by cortical override, trapping the survival energy in the body as chronic tension, pain, or hyperarousal. Guided discharge reactivates the subcortical completion cycle, restoring autonomic equilibrium.",
    instruction: "Follow the guided prompts to tune into the trapped activation in your body. Notice where the energy wants to move — a push, a pull, a shake, a curl. Give it permission to move, starting slowly and gently. The key is to let the body lead rather than the mind directing. Stay with the movement until you feel a natural settling — a deep breath, a sigh, or a sense of completion.",
  },
  {
    id: "emotion-wave",
    name: "Emotion Wave",
    modality: "somatic",
    originator: "DBT / Marsha Linehan",
    primitive: "emotionalArc",
    whyNow: "You described an emotion that feels permanent and overwhelming — the wave model shows that all emotions have a natural rise, peak, and fall if you do not amplify or suppress them.",
    science: "Emotions have a natural half-life of approximately 90 seconds (Jill Bolte Taylor) when the triggering stimulus is removed. What extends emotional duration is cognitive reactivation — replaying the trigger in the mind. Surfing the emotion wave trains the insula to track the emotion's trajectory, building confidence that intensity is temporary and survivable.",
    instruction: "The emotional arc charts the wave of your emotion from onset to resolution. Mark where you are now — rising, peaking, or descending. Then follow the prompts to breathe and observe as the wave moves. The visualization shows the wave's natural shape: it always comes down. Your job is to stay on the board, not stop the ocean.",
  },
  {
    id: "impulse-surfing",
    name: "Impulse Surfing",
    modality: "somatic",
    originator: "DBT / Marsha Linehan",
    primitive: "emotionalArc",
    whyNow: "You described a strong urge to do something you know is not in your best interest — impulse surfing helps you ride the wave of the urge without being pulled under by it.",
    science: "Urges are generated by the ventral striatum and amplified by the orbitofrontal cortex's reward prediction system. Like waves, they peak and subside — typically within 15-20 minutes. Impulse surfing trains the dorsolateral PFC's inhibition circuits while building distress tolerance. Each surfed urge weakens the habitual stimulus-response link through extinction learning.",
    instruction: "The emotional arc represents the trajectory of your impulse. Notice the urge arising and mark its current intensity. Then observe it without acting — like watching a wave from the shore. Track as it peaks and naturally subsides. The exercise provides grounding cues at the peak to help you hold steady through the most intense moments.",
  },
  {
    id: "clearing-exercise",
    name: "Clearing Exercise",
    modality: "somatic",
    originator: "Co-Active / CTI",
    primitive: "wordCloud",
    whyNow: "You seem cluttered with accumulated thoughts and feelings — a clearing empties the buffer so you can show up fresh and present to what matters.",
    science: "Working memory has a limited capacity (approximately 4 chunks in the dorsolateral PFC). When it is full of unprocessed material, new information cannot enter and cognitive performance degrades. The clearing exercise functions like a cognitive dump — externalizing the contents of working memory frees up processing capacity and reduces the anterior cingulate's 'unfinished business' signal.",
    instruction: "Tap out every word or phrase that is occupying your mind right now — worries, tasks, feelings, random fragments. Do not organize or judge, just dump. As the word cloud fills, notice the relief of externalizing what was taking up internal bandwidth. When the cloud feels complete, look at it from the outside and notice what has the most weight.",
  },
  {
    id: "grief-ritual",
    name: "Grief Ritual Creation",
    modality: "somatic",
    originator: "Somatic / Ritual",
    primitive: "emotionalArc",
    whyNow: "Your journal carried unprocessed grief — creating a ritual gives the grief a container and a pathway for expression that is safer than letting it leak out sideways.",
    science: "Rituals engage the cerebellum's procedural memory system and the basal ganglia's habit circuits, creating predictable somatic sequences that contain overwhelming affect. Anthropological and neuroscience research shows that ritualized mourning reduces cortisol, increases oxytocin, and activates the endogenous opioid system, providing natural pain relief during grief processing.",
    instruction: "The emotional arc walks you through designing your grief ritual. First, name what you are grieving. Then choose the elements: a physical gesture (lighting a candle, placing a stone), words you need to say, and a closing act that marks the transition from grieving to carrying forward. The arc ensures the ritual has a beginning, middle, and end — containment for what might otherwise feel boundless.",
  },
  {
    id: "future-self",
    name: "Future Self",
    modality: "somatic",
    originator: "Neuroscience / Visualization",
    primitive: "guided",
    whyNow: "You wrote about uncertainty about who you are becoming — connecting with your future self can provide clarity and motivation that your present self cannot generate alone.",
    science: "fMRI studies show that when people imagine their future self, many show neural patterns similar to imagining a stranger (rostral medial PFC, temporoparietal junction). Those who show greater self-continuity — more overlap between present-self and future-self neural representations — make better long-term decisions, save more money, and exhibit greater emotional regulation.",
    instruction: "Follow the guided visualization to meet your future self — the version of you who has navigated through the current challenge. What do they look like? How do they carry themselves? What do they want you to know right now? Listen for the specific advice or reassurance they offer. The vividness of this connection is what makes it neurologically real.",
  },
  {
    id: "energy-accounting",
    name: "Energy Accounting",
    modality: "somatic",
    originator: "Burnout Prevention",
    primitive: "heatmap",
    whyNow: "You described exhaustion that rest is not fixing — energy accounting reveals where your energy is actually going so you can find the hidden drains and protect the sources.",
    science: "Burnout is not just about time management — it is about energy management across physical, emotional, mental, and social channels. Each channel depletes different neurochemical systems: physical (ATP, cortisol), emotional (serotonin, oxytocin), mental (prefrontal glucose), social (dopamine). Accounting for all four channels prevents the common pattern of optimizing one while neglecting the others.",
    instruction: "The heatmap shows your week divided by time block and energy channel (physical, emotional, mental, social). For each block, rate the energy transaction: did it give energy (green), cost energy (red), or break even (yellow)? The completed heatmap reveals your energy landscape — where the drains cluster and where the sources are that you might be underleveraging.",
  },
  {
    id: "rain",
    name: "RAIN Practice",
    modality: "somatic",
    originator: "Tara Brach",
    primitive: "emotionalArc",
    whyNow: "You described a difficult emotion you are struggling to be with — RAIN offers a compassionate, structured way to turn toward it instead of fighting it or drowning in it.",
    science: "RAIN (Recognize, Allow, Investigate, Nurture) follows the sequence of adaptive emotion processing: recognition engages the ventrolateral PFC (affect labeling), allowing deactivates the behavioral inhibition system (reducing resistance), investigation activates the anterior insula (interoceptive inquiry), and nurturing activates the care-giving system (oxytocin, ventral vagal tone).",
    instruction: "The emotional arc guides you through four stages. Recognize: name what is happening inside you. Allow: let it be here without trying to fix or push it away. Investigate: get curious about where it lives in your body and what it needs. Nurture: offer yourself the kindness you would give a dear friend. Each stage builds on the previous one.",
  },
  {
    id: "self-compassion",
    name: "Self-Compassion",
    modality: "somatic",
    originator: "Kristin Neff",
    primitive: "guided",
    whyNow: "Your journal was harsh toward yourself — self-compassion is not self-indulgence, it is the practice of treating yourself the way you would treat someone you care about.",
    science: "Neff's research shows self-compassion activates the mammalian care-giving system (ventral vagal, oxytocin release) rather than the self-evaluation system (medial PFC, cortisol). Self-criticism activates the amygdala and increases inflammation markers. Self-compassion reduces both, while also improving motivation — contrary to the belief that being hard on yourself drives performance.",
    instruction: "Follow the guided prompts through Neff's three components: Mindfulness (acknowledging pain without over-identifying), Common Humanity (recognizing that suffering is shared, not isolating), and Self-Kindness (actively soothing yourself through words and touch). You will be guided to place a hand on your heart and speak to yourself as you would to a close friend in pain.",
  },
  {
    id: "opposite-action",
    name: "Opposite Action",
    modality: "somatic",
    originator: "DBT / Marsha Linehan",
    primitive: "guided",
    whyNow: "You described an emotion that is driving a behavior that is not serving you — opposite action is one of the most powerful emotion regulation tools when the emotion does not fit the facts.",
    science: "Opposite action works through extinction learning: by performing the behavioral opposite of what the emotion urges (approach instead of avoid, engage instead of withdraw), you send disconfirming sensory data to the amygdala. Over repeated trials, this weakens the conditioned association between the stimulus and the maladaptive emotional response through the same mechanism that underlies exposure therapy.",
    instruction: "Follow the guided prompts to identify the emotion, its action urge, and whether the emotion fits the facts. If it does not fit, the exercise will help you identify and commit to the opposite action — all the way, not half-heartedly. Acting opposite to an unjustified emotion is how you change it from the outside in.",
  },
  {
    id: "build-mastery",
    name: "Emotion Regulation: Build Mastery",
    modality: "somatic",
    originator: "DBT / Marsha Linehan",
    primitive: "guided",
    whyNow: "You described feeling powerless or incompetent — building mastery in one area creates a positive spiral of self-efficacy that transfers to the areas where you feel stuck.",
    science: "Mastery experiences are the strongest source of self-efficacy (Bandura). Successfully completing a challenging task triggers dopamine release in the striatum and strengthens the prefrontal-striatal confidence circuit. This neural pathway generalizes — mastery in one domain increases perceived capability across domains through the ventromedial PFC's self-concept updating mechanism.",
    instruction: "Follow the guided prompts to identify one activity you can do today that is challenging but achievable — something that requires effort and produces a tangible result. Plan when and how you will do it. After completion, return to rate your sense of mastery and notice how it affected your overall emotional state. Small wins compound.",
  },
  {
    id: "current-emotion",
    name: "Mindfulness of Current Emotion",
    modality: "somatic",
    originator: "DBT / Marsha Linehan",
    primitive: "emotionWheel",
    whyNow: "You wrote about feeling overwhelmed by emotions without being able to name them — this practice helps you observe your current emotional state with precision and without judgment.",
    science: "Mindful observation of emotion engages the anterior insula (interoception) and ventrolateral PFC (affect labeling) simultaneously, creating what Linehan calls 'experiencing without being controlled by.' This dual activation allows emotional information to be processed without triggering the behavioral urgency that emotions typically demand, training the capacity to feel without reacting.",
    instruction: "Explore the emotion wheel to identify what you are feeling right now. Start from the broad categories at the center and narrow down to the specific emotion at the outer rings. Once you land on it, observe it with curiosity — where do you feel it in your body? What is its texture, temperature, and movement? Practice watching it change without trying to change it.",
  },
];
