import type { ExerciseDefinition } from "./exerciseData";

export const MISSING_SOMATIC_EXERCISES: ExerciseDefinition[] = [
  // ═══════════════════════════════════════════
  // MISSING SOMATIC EXERCISES
  // These exist in the full frameworks library
  // but are not yet in exerciseDataCognitiveSomatic.ts
  // ═══════════════════════════════════════════

  {
    id: "polyvagal-three-states",
    name: "Polyvagal Theory: Three States",
    modality: "somatic",
    originator: "Stephen Porges",
    primitive: "zonedSpectrum",
    whyNow: "Your journal suggested your nervous system is toggling between states without your awareness — mapping the three polyvagal states helps you read your own autonomic cues before they drive your behavior.",
    science: "Porges's polyvagal theory identifies three phylogenetically ordered autonomic states: ventral vagal (safe, social), sympathetic (mobilized, fight/flight), and dorsal vagal (immobilized, shutdown). Heart rate variability, facial expressiveness, and vocal prosody shift measurably across these states. Recognizing which state you are in is the prerequisite for intentional state-shifting.",
    instruction: "The spectrum displays three color-coded zones representing the polyvagal states: ventral vagal (green/safe), sympathetic (yellow-orange/mobilized), and dorsal vagal (blue-grey/shutdown). Tap the zone that best matches where your nervous system is right now. Use the body cues listed in each zone — heart rate, muscle tension, eye contact comfort, vocal tone — to confirm your placement. Guidance for moving toward ventral vagal will appear based on your current state.",
    tags: ["journal-matched"],
  },
  {
    id: "stress-management-effectiveness",
    name: "Stress Management by Effectiveness",
    modality: "somatic",
    originator: "Integration",
    primitive: "guided",
    whyNow: "You described using strategies to manage stress that may not be working — this exercise helps you audit which approaches actually reduce stress versus those that just feel productive.",
    science: "Not all stress management strategies are equal. Research distinguishes between problem-focused coping (effective when the stressor is controllable) and emotion-focused coping (effective when it is not). Mismatching strategy to stressor type increases cortisol rather than reducing it. Effectiveness auditing engages the dorsolateral PFC's evaluation circuits to override the mere-exposure bias toward familiar but ineffective strategies.",
    instruction: "Follow the guided prompts to list every stress management strategy you currently use. For each one, rate its actual effectiveness on a scale from 1 to 10 — not how much you like doing it, but how much it actually reduces your stress. Then categorize each as problem-focused or emotion-focused and match it against whether the stressor is controllable or not. The mismatch patterns reveal where to redirect your efforts.",
    tags: ["journal-matched"],
  },
  {
    id: "signal-and-story-somatic",
    name: "Signal and Story (Somatic)",
    modality: "somatic",
    originator: "BEabove Leadership",
    primitive: "splitAnnotator",
    whyNow: "Your body is sending signals but your mind is writing stories about them — separating raw sensation from narrative interpretation can stop the amplification loop that turns tension into panic.",
    science: "The insula detects raw interoceptive signals (heartbeat, gut sensation, muscle tension) and the default mode network immediately wraps them in narrative. A racing heart becomes 'I am having a heart attack' or 'something is terribly wrong.' Somatic signal-story separation interrupts the insula-to-DMN escalation chain by keeping attention on the signal before the cortex elaborates it into threat.",
    instruction: "In the left column, write only the raw body signals you notice right now — heart rate, temperature, tension location, breathing depth. No interpretation, just sensation data. In the right column, write the stories your mind is telling about each signal. Seeing the gap between 'my chest is tight' (signal) and 'I am going to lose everything' (story) loosens the story's grip on your nervous system.",
    tags: ["journal-matched"],
  },
  {
    id: "literal-coaching",
    name: "Literal Coaching",
    modality: "somatic",
    originator: "Co-Active / CTI",
    primitive: "guided",
    whyNow: "You used powerful metaphors in your journal — literal coaching takes those metaphors seriously and lets your body explore them as if they were physically real.",
    science: "Metaphors are not just linguistic — they are embodied cognition. Lakoff and Johnson's research shows that abstract concepts are neurally grounded in sensorimotor experience. When someone says 'I feel stuck,' the motor cortex activates as if physically immobilized. Literal coaching leverages this embodied grounding by having the body enact the metaphor, accessing implicit knowledge that verbal processing cannot reach.",
    instruction: "Follow the guided prompts to identify a metaphor from your current experience — 'I feel like I am drowning,' 'I am carrying the weight of the world,' 'I am walking on eggshells.' Then explore it literally: What does the water feel like? Where is the weight sitting? How do the eggshells feel underfoot? Let your body respond. Then explore: What would it feel like to put the weight down? To find solid ground? The body often knows the solution before the mind does.",
    tags: ["journal-matched"],
  },
  {
    id: "mountain-meditation",
    name: "Mountain Meditation",
    modality: "somatic",
    originator: "Jon Kabat-Zinn",
    primitive: "guided",
    whyNow: "You described feeling shaken by external events — the mountain meditation cultivates an inner stability that weathers storms without being moved from its foundation.",
    science: "Visualization of stable, grounded imagery activates the posterior cingulate cortex and precuneus — regions involved in self-referential spatial processing. Imagining yourself as a mountain engages the vestibular-proprioceptive integration pathway, strengthening the felt sense of stability. MBSR research shows this meditation reduces reactivity to emotional stimuli and increases equanimity scores on standardized measures.",
    instruction: "Follow the guided meditation to visualize yourself as a mountain. Feel your base wide and grounded. Notice how weather passes over the mountain — rain, wind, snow, sun — and the mountain remains. Seasons change: spring flowers, summer heat, autumn winds, winter cold. Through it all the mountain sits. You are the mountain. External circumstances are the weather. Let them move through without moving you.",
    tags: ["journal-matched"],
  },
  {
    id: "mbsr-body-scan",
    name: "MBSR Body Scan",
    modality: "somatic",
    originator: "Jon Kabat-Zinn / MBSR",
    primitive: "bodyMap",
    whyNow: "You described disconnection between what you think and what you feel — the MBSR body scan systematically rebuilds the mind-body bridge that stress erodes.",
    science: "The MBSR body scan is the most-studied somatic awareness practice in clinical research. It increases insular cortex thickness, improves interoceptive accuracy, and reduces alexithymia (difficulty identifying emotions). Unlike a quick check-in, the MBSR version moves slowly through each body region, spending 2-3 minutes per area, which is the minimum time needed for the somatosensory cortex to recalibrate its sensitivity.",
    instruction: "On the body map, follow the guided sequence from the toes of your left foot up through the left leg, then the right side, through the torso, arms, and up to the crown of the head. For each region, bring full attention to whatever sensations are present — or the absence of sensation. Mark areas of particular intensity, numbness, or holding on the map. The completed scan gives you a detailed picture of where your body is today.",
    tags: ["journal-matched"],
  },
  {
    id: "mbsr-sitting-meditation",
    name: "MBSR Sitting Meditation",
    modality: "somatic",
    originator: "Jon Kabat-Zinn / MBSR",
    primitive: "guided",
    whyNow: "Your mind has been busy producing worry and analysis — sitting meditation offers a formal practice of returning to the present moment, training the muscle of attention itself.",
    science: "MBSR sitting meditation strengthens the dorsal attention network while dampening default mode network rumination. Eight weeks of regular practice increases cortical thickness in the prefrontal cortex and insula, and decreases amygdala gray matter density. The practice of returning attention to the breath after distraction is itself the exercise — each return strengthens the anterior cingulate cortex's attentional control circuit.",
    instruction: "Follow the guided instructions to settle into a comfortable seated position with a straight but relaxed spine. Begin with attention on the breath — not changing it, just observing. When the mind wanders (and it will), gently note where it went and return to the breath. Expand awareness to include body sensations, then sounds, then thoughts themselves as objects of attention. Each return to the present moment is a successful repetition.",
    tags: ["journal-matched"],
  },
  {
    id: "mbsr-mindful-movement",
    name: "MBSR Mindful Movement",
    modality: "somatic",
    originator: "Jon Kabat-Zinn / MBSR",
    primitive: "guided",
    whyNow: "You have been living in your head — mindful movement brings awareness back into the body through gentle, intentional physical engagement.",
    science: "Mindful movement integrates the motor cortex, cerebellum, and somatosensory cortex with the prefrontal attention networks. Unlike exercise for fitness, the goal is awareness of movement rather than performance. Research shows mindful movement reduces cortisol more effectively than equivalent non-mindful exercise because the attentional component engages the parasympathetic brake via the ventral vagal complex.",
    instruction: "Follow the guided movement sequence of gentle stretches and postures drawn from yoga and tai chi. For each movement, the focus is not on how far you can stretch but on what you notice as you move — where do you feel resistance? Where does movement flow easily? Breathe into tight areas. Move slowly enough that you can track sensation in real time. There is no goal except awareness.",
    tags: ["journal-matched"],
  },
  {
    id: "three-minute-breathing-space",
    name: "Three-Minute Breathing Space",
    modality: "somatic",
    originator: "MBCT / Segal, Williams, Teasdale",
    primitive: "guided",
    whyNow: "You described feeling swept away by the day's momentum — the three-minute breathing space is a micro-practice that creates a pause in autopilot mode, reconnecting you to the present.",
    science: "The three-minute breathing space is the portable core practice of MBCT. Its three steps — awareness of current experience, gathering attention to breath, expanding awareness to the body — map to deactivation of default mode network, engagement of the dorsal attention network, and reintegration of somatosensory awareness. Studies show it reduces rumination and prevents depressive relapse when practiced regularly as a mid-day interruption.",
    instruction: "Follow the three guided steps, each lasting about one minute. Step 1: Acknowledge — what thoughts, feelings, and body sensations are present right now? Just notice. Step 2: Gather — narrow your attention to the breath at the belly, following each inhale and exhale. Step 3: Expand — widen awareness from the breath to include the whole body, posture, and facial expression. You arrive back in the present, grounded and aware.",
    tags: ["journal-matched"],
  },
  {
    id: "thoughts-are-not-facts",
    name: "Thoughts Are Not Facts",
    modality: "somatic",
    originator: "MBCT / Segal, Williams, Teasdale",
    primitive: "guided",
    whyNow: "Your journal contained thoughts presented as certainties — this MBCT practice helps you experience thoughts as mental events rather than truths, which changes your relationship to them entirely.",
    science: "MBCT's central insight is that thoughts are mental events, not facts — a shift from content to process that engages metacognitive awareness circuits in the rostrolateral prefrontal cortex. In depressive relapse, negative thoughts are fused with mood, creating a self-reinforcing loop. Decentering from thoughts breaks this loop by activating the 'observing self' network, reducing the correlation between negative thought frequency and emotional distress.",
    instruction: "Follow the guided exercise to notice the thoughts moving through your mind right now. Instead of engaging with their content, practice labeling each one: 'There is a planning thought,' 'There is a worry thought,' 'There is a judgment.' Notice that you can observe the thought without being inside it. Thoughts arrive uninvited, stay for a while, and leave. You are the sky; thoughts are the weather.",
    tags: ["journal-matched"],
  },
  {
    id: "mbct-decentering",
    name: "MBCT Decentering",
    modality: "somatic",
    originator: "MBCT / Segal, Williams, Teasdale",
    primitive: "guided",
    whyNow: "You described being caught inside a painful narrative — decentering helps you step back from the story and see it as a story, which is different from believing it is the full truth.",
    science: "Decentering is the metacognitive ability to observe one's own mental processes from a detached perspective. Neuroimaging shows it activates the dorsomedial prefrontal cortex and reduces connectivity between the amygdala and the medial PFC's self-referential processing. This decoupling is the mechanism by which MBCT prevents depressive relapse — the negative content may still arise but it no longer triggers the full emotional cascade.",
    instruction: "Follow the guided prompts to identify a current thought or narrative that has a strong emotional pull. Now practice seeing it from a slight distance — as if watching a movie rather than being inside it. Notice: 'I am having the thought that...' rather than simply thinking the thought. Observe its emotional charge rise and fall without adding to it. This is decentering — you are here, the thought is there, and there is space between you.",
    tags: ["journal-matched"],
  },
  {
    id: "mbct-events-calendar",
    name: "MBCT Pleasant/Unpleasant Events Calendar",
    modality: "somatic",
    originator: "MBCT / Segal, Williams, Teasdale",
    primitive: "heatmap",
    whyNow: "You may be filtering your experience through a negativity lens without realizing it — tracking pleasant and unpleasant events builds awareness of the full range of your daily experience.",
    science: "Depressive and anxious cognition narrows attention to threat and loss. The pleasant/unpleasant events calendar counteracts this attentional bias by requiring systematic noticing of positive experiences. Encoding pleasant events strengthens the hippocampal-ventral striatal memory pathway for positive experiences, while tracking unpleasant events with equanimity builds distress tolerance via the anterior insula's interoceptive monitoring.",
    instruction: "The heatmap displays your week. For each time block, log whether the dominant experience was pleasant (green), unpleasant (red), or neutral (yellow). For each entry, briefly note: What happened? What body sensations were present? What thoughts accompanied it? What mood were you in? The completed map reveals patterns — when pleasant events cluster, when unpleasant ones repeat, and how much neutral experience you were previously ignoring.",
    tags: ["journal-matched"],
  },
  {
    id: "emdr-safe-place",
    name: "EMDR Safe/Calm Place",
    modality: "somatic",
    originator: "Francine Shapiro / EMDR",
    primitive: "guided",
    whyNow: "You described feeling unsafe or unsettled — creating a vivid internal safe place gives your nervous system a reliable refuge it can return to during moments of activation.",
    science: "The safe/calm place visualization creates a conditioned association between a mental image and parasympathetic activation. When practiced repeatedly, the image becomes a cue that triggers the ventral vagal response — lowered heart rate, relaxed muscles, slowed breathing — through classical conditioning. Neuroimaging shows that vividly imagined safe environments activate the same reward and safety circuits (ventral striatum, ventromedial PFC) as real safe environments.",
    instruction: "Follow the guided prompts to identify a place — real or imagined — where you feel completely safe and calm. Build the image in rich sensory detail: What do you see? Hear? Smell? Feel on your skin? Notice the body sensations that arise as the image becomes vivid. Anchor the image with a cue word (like 'calm' or 'safe'). Practice bringing up the image and feeling the shift in your body. This becomes a portable resource you can access anytime.",
    tags: ["journal-matched"],
  },
  {
    id: "emdr-container",
    name: "EMDR Container Exercise",
    modality: "somatic",
    originator: "Francine Shapiro / EMDR",
    primitive: "guided",
    whyNow: "You described intrusive thoughts or memories that keep breaking into your day — the container exercise gives you a way to store them safely until you are ready to process them.",
    science: "The container exercise uses mental imagery to create a symbolic boundary around distressing material. This engages the dorsolateral PFC's cognitive control circuits to inhibit involuntary retrieval from the amygdala-hippocampal memory system. The key mechanism is not suppression (which backfires) but containment — the material is acknowledged, not denied, but placed in a boundaried space that the person controls. This reduces intrusive frequency without creating rebound effects.",
    instruction: "Follow the guided prompts to imagine a container — a vault, a chest, a box, or anything sturdy and lockable. See it in detail: its material, size, color, and lock mechanism. Now place the distressing thought, image, or feeling into the container. Watch yourself close and lock it. You can open it when you choose to — in therapy, during journaling, or when you feel resourced. The container holds it so your mind does not have to.",
    tags: ["journal-matched"],
  },
  {
    id: "emdr-butterfly-hug",
    name: "EMDR Butterfly Hug",
    modality: "somatic",
    originator: "Lucina Artigas / EMDR",
    primitive: "guided",
    whyNow: "You described feeling activated and needing to self-soothe — the butterfly hug provides bilateral stimulation you can do anywhere, calming your nervous system through alternating touch.",
    science: "The butterfly hug provides bilateral stimulation (BLS) through alternating taps on the upper arms. BLS activates interhemispheric communication via the corpus callosum and mimics the saccadic eye movements of REM sleep, which is the brain's natural memory-processing state. Research shows BLS reduces the vividness and emotional charge of distressing memories by engaging the thalamic gating mechanism that modulates sensory-emotional integration.",
    instruction: "Follow the guided steps: Cross your arms over your chest so each hand rests on the opposite upper arm or shoulder — like giving yourself a hug. Now alternately tap left-right, left-right at a comfortable pace. Keep your eyes closed or look downward. Breathe naturally. Continue for 1-2 minutes. Notice what comes up — images, thoughts, body sensations — without holding on to any of them. Let the bilateral rhythm soothe your nervous system.",
    tags: ["journal-matched"],
  },
  {
    id: "vagal-tone-building",
    name: "Vagal Tone Building",
    modality: "somatic",
    originator: "Stephen Porges / Polyvagal",
    primitive: "guided",
    whyNow: "Your journal suggested chronic low-level activation — building vagal tone is like strength training for your parasympathetic nervous system, increasing your capacity to recover from stress.",
    science: "Vagal tone, measured by respiratory sinus arrhythmia (the heart rate variation linked to breathing), is a biomarker of emotional regulation capacity. Higher vagal tone predicts better stress recovery, greater social engagement, and reduced inflammation. Specific practices — slow exhalation, cold water face immersion, humming, and singing — directly stimulate the vagus nerve through its pharyngeal and auricular branches, trainably increasing tone over weeks.",
    instruction: "Follow the guided sequence of vagal tone exercises. First, practice extended exhale breathing — inhale for 4 counts, exhale for 8 counts — for 2 minutes. Second, hum deeply for 1 minute, feeling the vibration in your chest and throat. Third, splash cold water on your face or hold a cold cloth to your forehead for 30 seconds. Fourth, engage your social engagement system by softening your facial muscles and eyes. Track the shift from tense to settled.",
    tags: ["journal-matched"],
  },
  {
    id: "progressive-muscle-relaxation",
    name: "Progressive Muscle Relaxation",
    modality: "somatic",
    originator: "Edmund Jacobson",
    primitive: "guided",
    whyNow: "You described chronic tension that you cannot seem to release — progressive muscle relaxation teaches your body the contrast between tension and relaxation so it can find its way back to ease.",
    science: "Jacobson's progressive muscle relaxation works through the principle of reciprocal inhibition: deliberately tensing a muscle group and then releasing it activates the Golgi tendon organ reflex, which triggers a deeper relaxation than the muscle could achieve without the preceding tension. The practice systematically reduces resting muscle tone and decreases sympathetic nervous system output, measurably lowering blood pressure, cortisol, and subjective anxiety within a single session.",
    instruction: "Follow the guided sequence through each muscle group. For each one, tense the muscles firmly (but not painfully) for 5-7 seconds, then release and rest for 15-20 seconds, noticing the contrast. Move through: feet, calves, thighs, glutes, abdomen, chest, hands, forearms, biceps, shoulders, neck, and face. The key is paying attention to the feeling of release — that is what relaxation actually feels like. Let each release deepen the one before it.",
    tags: ["journal-matched"],
  },
  {
    id: "bilateral-stimulation",
    name: "Bilateral Stimulation",
    modality: "somatic",
    originator: "EMDR / Francine Shapiro",
    primitive: "guided",
    whyNow: "You described emotional material that feels stuck or looping — bilateral stimulation can help the brain process it by activating the same cross-hemisphere communication used during REM sleep.",
    science: "Bilateral stimulation (alternating left-right sensory input) enhances interhemispheric connectivity and mimics the neural processing that occurs during REM sleep. Research shows it reduces the vividness and emotional intensity of distressing memories by desynchronizing the amygdala's threat signal from the hippocampus's episodic replay. It also increases parasympathetic activation, as measured by decreased skin conductance and increased heart rate variability.",
    instruction: "Follow the guided bilateral stimulation practice. Choose your modality: alternating taps on your knees, alternating toe raises, or following a visual target moving left to right. Maintain a steady left-right-left-right rhythm at approximately one cycle per second. As you do, bring to mind the material you want to process — lightly, without forcing. Continue for 1-2 minutes, then pause and notice what shifted. Repeat as needed.",
    tags: ["journal-matched"],
  },
  {
    id: "somatic-pendulation",
    name: "Somatic Pendulation",
    modality: "somatic",
    originator: "Peter Levine / Somatic Experiencing",
    primitive: "bodyMap",
    whyNow: "You described being stuck in a painful sensation — pendulation teaches your nervous system that it can move between distress and resource, which is the foundation of all regulation.",
    science: "Pendulation is Levine's core somatic technique: gently oscillating attention between a place of activation (discomfort) and a place of resource (comfort) in the body. This mimics the nervous system's natural regulatory rhythm and prevents the overwhelm that comes from staying in activation too long. Each swing between states strengthens the autonomic flexibility that trauma disrupts, gradually widening the window of tolerance.",
    instruction: "On the body map, first locate a place in your body that feels comfortable, warm, or neutral — this is your resource. Tap it. Then locate a place of tension, discomfort, or activation — tap it. Now practice pendulating: spend 10-15 seconds with attention on the resource, then shift to the activation for 5-10 seconds, then back to the resource. Notice how the activation changes with each cycle. The body map tracks the shifts in sensation across pendulation cycles.",
    tags: ["journal-matched"],
  },
  {
    id: "the-river",
    name: "The River: Emotional Flow",
    modality: "somatic",
    originator: "Somatic / Integration",
    primitive: "emotionalArc",
    whyNow: "You described emotions that feel dammed up or flooding — the river metaphor helps you find the natural current between suppression and overwhelm.",
    science: "Emotional regulation is best understood as flow management rather than content management. Suppression (damming) increases amygdala activation and physiological arousal despite reducing outward expression. Flooding (bursting the dam) overwhelms the prefrontal cortex's processing capacity. Healthy regulation allows emotions to flow at a rate the system can process — the anterior cingulate cortex adjusts this flow rate in real time using feedback from the insula.",
    instruction: "The emotional arc represents the river of your emotional experience. Map its current state — is it dammed up (suppressed, numb, controlled), flooding (overwhelming, out of control), or flowing (felt but manageable)? Then follow the guided exploration: if dammed, practice gently opening the gates by softening your body and letting one feeling through. If flooding, practice containment by grounding and narrowing focus. The goal is steady flow, not still water.",
    tags: ["journal-matched"],
  },
  {
    id: "sense-and-savor-walk",
    name: "Sense and Savor Walk",
    modality: "somatic",
    originator: "Positive Psychology / Mindfulness",
    primitive: "guided",
    whyNow: "You have been living inside problems — a sense-and-savor walk reconnects you to the simple pleasures your nervous system needs to recover.",
    science: "Savoring engages the ventral striatum and orbitofrontal cortex's reward circuitry during positive experiences, strengthening the encoding of positive memories that the negativity bias typically filters out. Combining savoring with walking adds bilateral motor stimulation (which enhances interhemispheric processing) and environmental novelty (which stimulates hippocampal encoding). The result is a neurochemical cocktail of serotonin, dopamine, and endorphins that directly counters the stress hormone profile.",
    instruction: "Follow the guided instructions for a 10-15 minute walk. The first third: focus entirely on what you see — colors, light, movement, details. The second third: focus on what you hear — near sounds, far sounds, layered sounds. The final third: focus on physical sensation — air on skin, feet on ground, temperature, wind. For each sense, when you notice something pleasant, pause and deliberately savor it for 10-20 seconds. Let the good land.",
    tags: ["journal-matched"],
  },
  {
    id: "gibberish-expression",
    name: "Gibberish Expression",
    modality: "somatic",
    originator: "Osho / Expressive Arts",
    primitive: "guided",
    whyNow: "You seem to be overthinking everything — gibberish bypasses the cognitive filters entirely and lets your body express what words cannot capture.",
    science: "Speaking in gibberish (meaningless sounds with full emotional expression) deactivates the language production centers (Broca's area) while keeping the limbic-motor emotional expression system fully active. This separation allows emotional discharge without the cognitive processing that typically edits, judges, and suppresses expression. Research on cathartic vocalization shows it reduces cortisol and muscle tension while increasing vagal tone.",
    instruction: "Follow the guided instructions: for 2-3 minutes, speak in complete gibberish — nonsense sounds with full emotional expression. Use your hands, your face, your whole body. Let the sounds match your internal state — angry gibberish, sad gibberish, anxious gibberish. Do not try to make sense. After the gibberish phase, sit in 1 minute of complete silence and notice what your body feels like when the noise stops. The contrast is the teaching.",
    tags: ["journal-matched"],
  },
  {
    id: "spontaneity-practice",
    name: "Spontaneity Practice",
    modality: "somatic",
    originator: "J.L. Moreno / Psychodrama",
    primitive: "guided",
    whyNow: "Your journal suggested rigidity or over-planning — spontaneity practice loosens the grip of control and reconnects you with your improvisational capacity.",
    science: "Moreno defined spontaneity as the capacity to respond to new situations with adequacy or to old situations with novelty. Neuroscience maps this to the interplay between the prefrontal cortex's planning circuits and the basal ganglia's improvisation circuits. Over-reliance on planning suppresses the ventral striatum's reward prediction signal for novelty. Spontaneity exercises rebalance this by deliberately engaging improv-mode neural networks.",
    instruction: "Follow the guided prompts to practice small acts of spontaneity. Begin with physical improvisation: move your body in a way that has no plan — let each movement arise from the one before it. Then verbal improvisation: speak aloud for one minute without planning your next sentence. Finally, action improvisation: commit to one small unplanned action today. Notice where spontaneity feels liberating and where it triggers anxiety — the anxiety edges are where the practice matters most.",
    tags: ["journal-matched"],
  },
  {
    id: "eight-year-old-test",
    name: "8-Year-Old Test",
    modality: "somatic",
    originator: "Co-Active / Integration",
    primitive: "guided",
    whyNow: "You are taking life very seriously right now — the 8-year-old test reconnects you with the part of you that knows how to play, which is exactly what your overloaded adult brain needs.",
    science: "The prefrontal cortex matures last and dominates adult cognition with planning, evaluation, and worry. The play circuitry (subcortical, centered on the ventral tegmental area and periaqueductal gray) is present from childhood but becomes suppressed by cortical override in adulthood. Deliberately accessing the 'inner child' perspective reactivates these circuits, increasing dopamine, reducing cortisol, and improving creative problem-solving through what Jaak Panksepp called the PLAY system.",
    instruction: "Follow the guided prompts to consult your 8-year-old self about your current situation. What would 8-year-old you think about this problem? What would they want to do right now? What would they say to the adult version of you who is worrying so much? Let their perspective — unfiltered, playful, and honest — offer a counterbalance to your adult seriousness. Often the simplest truth comes from the youngest voice.",
    tags: ["journal-matched"],
  },
  {
    id: "mirror-practice",
    name: "Mirror Practice",
    modality: "somatic",
    originator: "Self-Compassion / Integration",
    primitive: "guided",
    whyNow: "You have been harsh with yourself — mirror practice builds the capacity to look at yourself with the same kindness you would offer a friend.",
    science: "Mirror gazing activates the fusiform face area and the social cognition network (medial PFC, temporoparietal junction) directed at the self, which is usually reserved for processing others. This self-other crossover can activate the compassion circuits (anterior insula, ventral vagal complex) toward oneself. Studies show that mirror practice reduces self-criticism scores and increases self-compassion within two weeks of daily practice.",
    instruction: "Follow the guided exercise to look at yourself in a mirror (or imagine doing so) for 2-3 minutes. Begin by simply looking — without evaluating, fixing, or criticizing. Notice the impulse to judge and let it pass. Then speak to your reflection as you would to someone you love: 'I see you. You are having a hard time. That is okay.' Let the words land. Notice what happens in your body when you receive your own kindness. This is not narcissism — it is the foundation of resilience.",
    tags: ["journal-matched"],
  },
  {
    id: "loving-kindness-metta",
    name: "Loving Kindness / Metta",
    modality: "somatic",
    originator: "Buddhist Psychology",
    primitive: "guided",
    whyNow: "Your journal carried frustration or resentment — loving kindness practice softens the heart not by forcing forgiveness but by reconnecting you with your capacity for warmth.",
    science: "Loving kindness meditation increases activation in the insula and temporal-parietal junction (empathy circuits), the ventral striatum (positive affect), and the medial prefrontal cortex (self-other processing). Regular practice increases positive emotions, social connectedness, and vagal tone. Critically, it reduces the implicit bias toward outgroup members and increases prosocial behavior — effects that persist for months after the practice period ends.",
    instruction: "Follow the guided meditation to generate wishes of well-being in expanding circles. Start with yourself: 'May I be safe. May I be healthy. May I be happy. May I live with ease.' Then extend to someone you love, then to a neutral person, then to a difficult person, and finally to all beings. For each round, feel the wishes in your body — particularly the area around your heart. The practice is not about meaning the words perfectly; it is about inclining the mind toward kindness.",
    tags: ["journal-matched"],
  },
  {
    id: "forgiveness-meditation",
    name: "Forgiveness Meditation",
    modality: "somatic",
    originator: "Jack Kornfield / Buddhist Psychology",
    primitive: "guided",
    whyNow: "You are carrying resentment that is costing you energy — forgiveness meditation does not mean condoning what happened but releasing its hold on your nervous system.",
    science: "Holding resentment maintains chronic activation of the threat detection circuit (amygdala, anterior insula) and the ruminative loop (default mode network). Forgiveness deactivates these circuits by engaging the ventromedial PFC's reappraisal function and the anterior cingulate's conflict resolution process. Research shows forgiveness practices reduce cortisol, blood pressure, and depression scores while increasing heart rate variability and life satisfaction.",
    instruction: "Follow the guided meditation through three phases. First, ask forgiveness from those you have harmed: 'For the ways I have hurt you, knowingly or unknowingly, I ask your forgiveness.' Second, offer forgiveness to those who have hurt you: 'For the ways you have hurt me, knowingly or unknowingly, I offer you forgiveness — as much as I can in this moment.' Third, forgive yourself: 'For the ways I have hurt myself, I offer forgiveness.' There is no rush. Offer only what is genuine.",
    tags: ["journal-matched"],
  },
  {
    id: "what-is-asking-for-attention",
    name: "\"What Is Asking for Attention?\"",
    modality: "somatic",
    originator: "Co-Active / CTI",
    primitive: "guided",
    whyNow: "You seem to be focused on the surface-level problem — this inquiry drops beneath the presenting issue to find what is actually asking for your attention right now.",
    science: "The question 'What is asking for attention?' bypasses the dorsolateral PFC's problem-solving mode and activates the insula's interoceptive monitoring and the default mode network's broader associative processing. This allows preconscious, body-based knowing — what Damasio calls somatic markers — to surface. The information that 'asks for attention' is often already known by the body but filtered out by the mind's focus on the presenting problem.",
    instruction: "Follow the guided inquiry: Close your eyes. Take three breaths. Then ask yourself, 'What is asking for my attention right now?' Do not think your way to an answer — listen for it. Notice what arises in your body first: a tightness, an image, a word, a memory. Whatever comes, let it come. Then ask again: 'And what is underneath that?' Go one layer deeper. The thing asking for attention is rarely the first thing that shows up — keep listening.",
    tags: ["journal-matched"],
  },
  {
    id: "failure-bow",
    name: "Failure Bow",
    modality: "somatic",
    originator: "Matt Smith / Improv",
    primitive: "guided",
    whyNow: "You described a mistake or failure that is sitting heavy — the failure bow transforms your relationship with failure from shame to learning through a physical practice.",
    science: "Shame activates the anterior insula and anterior cingulate cortex, creating the visceral 'sinking' feeling and urge to hide. The failure bow works through embodied cognition: physically standing tall, raising your arms, and declaring the failure publicly (or to yourself) activates the motor cortex's power-posture circuits and the ventral striatum's reward system, neurochemically counteracting the shame response. The somatic override interrupts the shame-withdrawal loop.",
    instruction: "Follow the guided practice: Think of a recent failure or mistake. Now physically stand up, raise your arms wide, and say aloud 'I failed at [specific thing]!' with energy and even a smile. Take a bow. Notice what happens in your body — the awkwardness, then often the relief or even laughter. Repeat with 2-3 more failures. The practice teaches your nervous system that failure is survivable — and even something you can celebrate as evidence of trying.",
    tags: ["journal-matched"],
  },
  {
    id: "abc-please",
    name: "ABC PLEASE",
    modality: "somatic",
    originator: "DBT / Marsha Linehan",
    primitive: "guided",
    whyNow: "Your emotional reactivity may be amplified by physical vulnerability — ABC PLEASE builds the biological foundation that makes emotional regulation possible.",
    science: "DBT's ABC PLEASE skill addresses the biological vulnerability factors that lower the threshold for emotional reactivity. Accumulating positive experiences rebuilds hedonic tone (ventral striatal function). Building mastery increases self-efficacy (prefrontal-striatal circuit). Coping ahead prepares response plans (dorsolateral PFC). PLEASE (Physical iLlness, Eating, Avoid substances, Sleep, Exercise) targets the basic physiological systems that modulate emotional set-point. Neglecting any one factor can undermine all other regulation efforts.",
    instruction: "Follow the guided assessment of your biological foundation. Rate each PLEASE factor: Are you treating physical illness? Eating regularly and balanced? Avoiding mood-altering substances? Getting adequate sleep? Exercising? For each area below your standard, identify one specific action you will take today. Then assess the ABC factors: What positive experience can you accumulate today? What mastery activity will you complete? What difficult situation should you cope ahead for? Small improvements in the foundation disproportionately improve emotional regulation.",
    tags: ["journal-matched"],
  },
  {
    id: "flow-state-cultivation",
    name: "Flow State Cultivation",
    modality: "somatic",
    originator: "Mihaly Csikszentmihalyi",
    primitive: "guided",
    whyNow: "You described either boredom or anxiety in your work — flow lives in the narrow channel between them, and this exercise helps you find and enter that channel deliberately.",
    science: "Csikszentmihalyi's flow state occurs when challenge and skill are balanced at a high level, producing a state of effortless concentration. Neurologically, flow involves transient hypofrontality — the prefrontal cortex's self-monitoring functions temporarily quiet, allowing the basal ganglia and motor cortex to run unimpeded. This produces time distortion, reduced self-consciousness, and intrinsic reward via a cocktail of dopamine, endorphins, norepinephrine, anandamide, and serotonin.",
    instruction: "Follow the guided assessment to map your current challenge-skill balance. Rate the challenge of your current task (1-10) and your skill level for it (1-10). If challenge exceeds skill by more than 2 points, you need to build skill or reduce scope. If skill exceeds challenge by more than 2 points, you need to increase challenge or complexity. The exercise helps you adjust one or both until they match — then provides environmental setup guidance (eliminate distractions, set a timer, define clear goals) to help you enter the flow channel.",
    tags: ["journal-matched"],
  },
  {
    id: "savoring-practice",
    name: "Savoring Practice",
    modality: "somatic",
    originator: "Fred Bryant / Positive Psychology",
    primitive: "guided",
    whyNow: "You have been focused on what is wrong — savoring trains you to absorb what is right, which is a skill your nervous system needs to counterbalance the negativity bias.",
    science: "Bryant's savoring research shows that the ability to attend to, appreciate, and enhance positive experiences is a distinct skill independent of the frequency of positive events. Savoring amplifies activity in the ventral striatum and orbitofrontal cortex, extending the duration of positive emotion from seconds to minutes. People who savor more show higher life satisfaction, lower depression, and greater resilience — not because they have better lives but because they extract more value from the good that already exists.",
    instruction: "Follow the guided savoring practice. First, recall a recent positive experience — it can be small. Recreate it in your mind with full sensory detail. Now apply the four savoring strategies: Sharing (tell someone about it), Memory building (take a mental photograph), Self-congratulation (acknowledge your role in it), and Sensory immersion (re-feel the physical sensations). Spend at least 30 seconds on each strategy. Notice how the positive feeling grows as you give it attention.",
    tags: ["journal-matched"],
  },
  {
    id: "walking-the-middle-path",
    name: "Walking the Middle Path",
    modality: "somatic",
    originator: "DBT / Marsha Linehan",
    primitive: "guided",
    whyNow: "Your journal showed all-or-nothing thinking — walking the middle path helps you find the dialectical balance between extremes, where wisdom usually lives.",
    science: "DBT's dialectical approach is rooted in the observation that truth is rarely found at extremes. The anterior cingulate cortex detects conflict between opposing positions, and the ventromedial PFC integrates them into a dialectical synthesis. All-or-nothing thinking reflects a failure of integration — one hemisphere's perspective dominates. Practicing the middle path strengthens the corpus callosum's interhemispheric connectivity, enabling both perspectives to be held simultaneously.",
    instruction: "Follow the guided exercise to identify a current either/or position you are holding: 'I should stay vs. I should leave,' 'I need to be strong vs. I need to fall apart,' 'This person is all good vs. all bad.' Now explore the middle: What would 'and' look like? What would a partial truth on each side look like? Where does the extreme position protect you, and what does it cost? The middle path is not a compromise — it is a larger truth that holds both sides.",
    tags: ["journal-matched"],
  },
  {
    id: "mbsr-stress-reactivity",
    name: "MBSR Stress Reactivity Awareness",
    modality: "somatic",
    originator: "Jon Kabat-Zinn / MBSR",
    primitive: "guided",
    whyNow: "You described being in reactive mode — this MBSR practice helps you see your stress reactivity pattern clearly so you can choose to respond instead of react.",
    science: "Kabat-Zinn distinguishes between stress reactivity (automatic, unconscious, habitual) and stress responsivity (mindful, intentional, chosen). Reactivity is mediated by the fast amygdala-brainstem pathway; responsivity requires the slower but more flexible prefrontal-amygdala regulatory pathway. MBSR's stress reactivity awareness practice strengthens the second pathway by making the first visible — you cannot change a pattern you cannot see.",
    instruction: "Follow the guided reflection to map your personal stress reactivity pattern. What are your early warning signs — the first body signals, thoughts, and behaviors that appear when stress activates? What is your habitual sequence — the chain from trigger to full reaction? Where in the chain are the choice points — the moments where a different response is still possible? Once you can see the whole chain, you can interrupt it earlier. The goal is not to eliminate reactivity but to notice it sooner.",
    tags: ["journal-matched"],
  },
  {
    id: "co-regulation-practice",
    name: "Co-regulation Practice",
    modality: "somatic",
    originator: "Stephen Porges / Polyvagal",
    primitive: "guided",
    whyNow: "You described feeling isolated in your distress — co-regulation recognizes that we are wired to regulate through connection, not just through individual techniques.",
    science: "Porges's polyvagal theory establishes that the ventral vagal social engagement system is the primary regulation pathway in mammals. Co-regulation — the mutual influence of two nervous systems in proximity — is not a luxury but a biological necessity. Secure attachment, attuned conversation, and even being in the presence of a calm person all reduce cortisol and increase oxytocin through vagal afferent pathways. Self-regulation capacity is built on a foundation of co-regulation experiences.",
    instruction: "Follow the guided exercise to explore co-regulation. First, identify who in your life helps your nervous system settle — whose presence makes you feel calmer? Then consider: What specifically do they do? (Tone of voice? Eye contact? Pacing?) Now practice receiving regulation: recall being with that person, feel the settling in your body. Finally, plan one concrete co-regulation action — a call, a visit, a walk together. Your nervous system heals fastest in safe connection.",
    tags: ["journal-matched"],
  },
  {
    id: "mentalization-practice",
    name: "Mentalization Practice",
    modality: "somatic",
    originator: "Peter Fonagy / MBT",
    primitive: "guided",
    whyNow: "You described a relationship difficulty where you are certain about the other person's motives — mentalization helps you hold those attributions more lightly by imagining multiple possible inner worlds.",
    science: "Mentalization — the capacity to understand behavior in terms of underlying mental states — depends on the medial prefrontal cortex, temporoparietal junction, and superior temporal sulcus. When stressed or triggered, mentalization capacity collapses (Fonagy calls this 'mentalizing failure'), and we revert to teleological thinking ('they did X because they are Y'). Practicing mentalization restores the capacity to generate multiple hypotheses about others' inner states, reducing interpersonal conflict and increasing empathy.",
    instruction: "Follow the guided exercise to practice mentalizing about a current interpersonal situation. First, describe the other person's behavior — just the observable actions. Then generate at least three possible explanations for their behavior, each based on a different internal state: 'They might be feeling... and therefore did...' Try to make each explanation genuinely plausible. Notice which one your mind gravitates toward and hold it lightly. Mentalization is not about being right about others' minds — it is about staying curious.",
    tags: ["journal-matched"],
  },
];
