import type { ExerciseDefinition } from "./exerciseData";

// ═══════════════════════════════════════════════════════════════
// 90 Core Daily Exercises — Parachute, Jetstream, Basecamp
// ═══════════════════════════════════════════════════════════════

export const CORE_EXERCISES: ExerciseDefinition[] = [
  // ─────────────────────────────────────────────────────────────
  // PARACHUTE (Layoff Recovery) — 30 Days
  // ─────────────────────────────────────────────────────────────

  {
    id: "parachute-day-1",
    name: "Seven Disruptions Inventory",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "wheelChart",
    tags: ["core-parachute"],
    dayNumber: 1,
    whyNow: "Losing a job disrupts more than income — it can shake your sense of identity, routine, confidence, belonging, and security all at once.",
    science: "Multi-domain disruption assessment activates metacognitive monitoring across life areas simultaneously. Rating each domain engages the prefrontal cortex in systematic self-evaluation, creating a baseline that prevents single-issue fixation.",
    instruction: "Use the wheel chart to rate each of the seven disruptions from 1 to 10. Tap or drag each segment to set your rating, then review the overall shape to see where disruption is hitting hardest.",
  },
  {
    id: "parachute-day-2",
    name: "Timeline Mapping",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "timelineRiver",
    tags: ["core-parachute"],
    dayNumber: 2,
    whyNow: "Think back over the last 6-12 months and map the key events, shifts, and decisions that led to where you are now.",
    science: "Constructing a chronological narrative engages episodic memory retrieval and the hippocampus, transforming fragmented emotional memories into a coherent sequence. This process reduces the emotional charge of individual events by embedding them in context.",
    instruction: "Plot key events along the timeline river, placing them in chronological order. Include not just facts but how you felt at each stage. Drag events to position them and add emotional annotations to reveal the subtext beneath the facts.",
  },
  {
    id: "parachute-day-3",
    name: "Somatic Mapping + Family Patterns",
    modality: "somatic",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "bodyMap",
    tags: ["core-parachute"],
    dayNumber: 3,
    whyNow: "Your body keeps a record of stress that your mind sometimes skips over. Scan from head to toe and notice where tension lives.",
    science: "Interoceptive awareness — attending to internal body sensations — activates the insula and anterior cingulate cortex. Research shows that people with higher interoceptive accuracy regulate emotions more effectively because they can detect stress signals before they escalate.",
    instruction: "Tap areas on the body map where you feel tension, heaviness, tightness, or numbness. Label each sensation with a description. Then use the annotation layer to connect each body sensation to family beliefs about work and worth.",
  },
  {
    id: "parachute-day-4",
    name: "Saboteur Identification",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "cardSort",
    tags: ["core-parachute"],
    dayNumber: 4,
    whyNow: "Under stress, we all develop automatic patterns that once helped us cope but now often work against us. These are called saboteurs.",
    science: "Externalizing automatic thought patterns into named entities leverages cognitive defusion, a core ACT technique. Naming the pattern activates the ventrolateral prefrontal cortex, creating psychological distance between the self and the habitual response.",
    instruction: "Sort the saboteur cards into categories: your top patterns, occasional patterns, and patterns that do not apply. For each one you select, add notes about what it says to you, when it gets loudest, and what it protects you from.",
  },
  {
    id: "parachute-day-5",
    name: "Financial Ground Truth",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "dotGrid",
    tags: ["core-parachute"],
    dayNumber: 5,
    whyNow: "Financial anxiety after a job loss often mixes facts with fear — and the fear can feel so loud that it is hard to tell which is which.",
    science: "Separating factual data from emotional projections engages dual-process thinking. The prefrontal cortex handles numerical reasoning while the amygdala drives catastrophic projection — making both visible simultaneously reduces the amygdala's distortive influence on financial decision-making.",
    instruction: "Use the dot grid to map your financial facts on one axis and financial fears on the other. Position each item as a dot, then review the cluster patterns to see where facts and fears overlap versus where fears are running ahead of evidence.",
  },
  {
    id: "parachute-day-6",
    name: "Minimal Structure Design",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-parachute"],
    dayNumber: 6,
    whyNow: "When you lose a job, you lose the structure that organized your entire day. Without it, days blur together and anxiety fills the space.",
    science: "Behavioral activation research shows that even minimal daily structure counteracts the withdrawal and passivity associated with loss. Three daily anchors provide predictability that regulates the hypothalamic-pituitary-adrenal axis, reducing cortisol output.",
    instruction: "Follow the guided prompts to design three daily anchors: one physical, one reflective, and one connective. Write each commitment and set a rough time of day for each one. This creates your minimum viable structure.",
  },
  {
    id: "parachute-day-7",
    name: "Acceptance Curve Placement",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "spectrumSlider",
    tags: ["core-parachute"],
    dayNumber: 7,
    whyNow: "After any significant loss, people naturally move through stages. The point is to notice where you are right now, honestly.",
    science: "Self-placement on a grief spectrum activates metacognitive monitoring without forcing premature resolution. Research on grief processing shows that honest self-assessment of emotional state predicts better adjustment outcomes than either denial or forced positivity.",
    instruction: "Use the spectrum slider to place yourself on the acceptance curve — from shock on the left to acceptance on the right. Then use the annotation fields to describe what pulls you backward and what creates forward movement.",
  },
  {
    id: "parachute-day-8",
    name: "Role Identity Transition",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "vennOverlap",
    tags: ["core-parachute"],
    dayNumber: 8,
    whyNow: "When you work somewhere long enough, your job title becomes part of how you see yourself. Losing that role can feel like losing a piece of who you are.",
    science: "Identity decoupling exercises engage the default mode network and self-referential processing regions. Separating role-based identity from core identity reduces identity foreclosure and opens exploration of alternative self-concepts.",
    instruction: "Use the Venn diagram to map identity elements that belonged to the job, identity elements that are yours regardless of any role, and the overlap zone where both exist. Drag items into each circle to visualize what you keep versus what belonged to the position.",
  },
  {
    id: "parachute-day-9",
    name: "Belonging Inventory",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "heatmap",
    tags: ["core-parachute"],
    dayNumber: 9,
    whyNow: "One of the hidden losses of a job is the community that came with it — the people, the Slack channels, the lunch conversations.",
    science: "Social connection directly regulates the autonomic nervous system through co-regulation mechanisms. Mapping belonging sources activates mentalizing networks and reveals which social bonds were context-dependent versus enduring.",
    instruction: "Rate each area of belonging on the heatmap — from family and friends to professional communities and neighborhoods. Use color intensity to show how strong the belonging feels right now. Identify the cold spots where belonging was lost with the job.",
  },
  {
    id: "parachute-day-10",
    name: "Belief Inventory",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "splitAnnotator",
    tags: ["core-parachute"],
    dayNumber: 10,
    whyNow: "We all carry beliefs about ourselves as professionals. Some were with you long before this job; others formed during or after the loss.",
    science: "Belief externalization engages cognitive reappraisal circuits by making implicit assumptions explicit. Tracing belief origins to family, culture, or specific experiences activates autobiographical memory networks and creates distance from beliefs experienced as self-evident truth.",
    instruction: "In the left column, list your professional beliefs. In the right column, annotate each with its origin, whether it predates the job loss, and whether it helps or hinders you. The split view keeps the belief and its analysis visually separated.",
  },
  {
    id: "parachute-day-11",
    name: "Family Patterns: Work and Worth",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "hierarchicalBranch",
    tags: ["core-parachute"],
    dayNumber: 11,
    whyNow: "Many of our deepest beliefs about work and self-worth were absorbed long before we entered the workforce — from how our families talked about success.",
    science: "Genogram-style exercises trace intergenerational belief transmission, engaging long-term memory consolidation systems. Making inherited beliefs explicit activates the prefrontal cortex's capacity to evaluate previously unconscious assumptions.",
    instruction: "Build a hierarchical branch from family messages at the root to corporate culture messages in the middle to your current beliefs at the leaves. Map how each layer influenced the next to see the full chain of inherited worth-work beliefs.",
  },
  {
    id: "parachute-day-12",
    name: "Saboteur Patterns in Action",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "heatmap",
    tags: ["core-parachute"],
    dayNumber: 12,
    whyNow: "On Day 4, you identified your saboteurs. Now it is time to watch them in action — when did each one show up this week?",
    science: "Real-time pattern tracking strengthens metacognitive monitoring by creating a feedback loop between automatic behavior and conscious awareness. Frequency tracking makes the gap between trigger and response more visible, which is the precondition for behavioral change.",
    instruction: "Use the heatmap to map saboteur activations across situations and times of day. Higher intensity indicates more frequent or stronger activations. Notice where clusters form to identify your most vulnerable triggers.",
  },
  {
    id: "parachute-day-13",
    name: "Values Excavation Part 1",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "wordCloud",
    tags: ["core-parachute"],
    dayNumber: 13,
    whyNow: "Values are not something you pick from a list — they are discovered by looking at what has already mattered to you in lived experience.",
    science: "Experience-based values identification activates episodic memory and the ventromedial prefrontal cortex, linking abstract values to concrete autobiographical events. This produces more stable values than checklist approaches because they are grounded in felt experience.",
    instruction: "Add words and phrases that describe moments when you felt fully yourself at work. The word cloud will grow as you add entries, with more frequently mentioned themes appearing larger. Look for the values hidden underneath each meaningful moment.",
  },
  {
    id: "parachute-day-14",
    name: "Values Stack Ranking",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "bubbleSort",
    tags: ["core-parachute"],
    dayNumber: 14,
    whyNow: "Yesterday you identified values from your career experiences. Today you have to rank them — and it will be uncomfortable on purpose.",
    science: "Forced-choice ranking activates conflict monitoring in the anterior cingulate cortex, revealing the true weight of competing values. When everything is a priority, nothing is — the discomfort of ranking is the mechanism that produces decision-making clarity.",
    instruction: "You will see pairs of values presented side by side. For each pair, choose which matters more. The bubble sort algorithm will use your comparisons to produce a ranked list. Let the discomfort of choosing be informative — it reveals where your values truly live.",
  },
  {
    id: "parachute-day-15",
    name: "Values Pressure Test",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "forcedChoice",
    tags: ["core-parachute"],
    dayNumber: 15,
    whyNow: "Knowing your values is one thing. Holding onto them when real life pushes back is another. This puts your top values under pressure.",
    science: "Scenario-based values testing engages prospective simulation networks in the hippocampus and prefrontal cortex. Imagining realistic pressure scenarios creates a form of mental rehearsal that strengthens values-based decision-making under actual stress.",
    instruction: "You will be presented with realistic scenarios that pit your values against each other — financial pressure versus creative freedom, status versus alignment. For each scenario, make your forced choice and then reflect on what the choice reveals about your actual priorities.",
  },
  {
    id: "parachute-day-16",
    name: "Structural Perspective",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-parachute"],
    dayNumber: 16,
    whyNow: "When you lose a job, it is natural to make it entirely personal. But job loss in tech often has very little to do with individual performance.",
    science: "Reattribution exercises shift causal explanations from internal-stable-global attributions to external-unstable-specific ones, reducing shame and learned helplessness. This engages the temporoparietal junction in perspective-taking about systemic factors.",
    instruction: "Follow the guided prompts to separate personal factors from structural ones. Write about market forces, organizational decisions, and systemic trends that contributed to your situation. Then identify what is genuinely personal — the structural reframe does not erase accountability, it makes it accurate.",
  },
  {
    id: "parachute-day-17",
    name: "Evidence Collection",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "splitAnnotator",
    tags: ["core-parachute"],
    dayNumber: 17,
    whyNow: "After a job loss, your brain tends to build a case against you — replaying mistakes and dismissing accomplishments. This builds a counter-record.",
    science: "Building a competence evidence base counteracts negativity bias by deliberately activating positive episodic memories. This engages the hippocampus in targeted retrieval and strengthens self-efficacy through Bandura's mastery experience pathway.",
    instruction: "In the left column, list specific accomplishments and things you did well. In the right column, add the evidence — who noticed, what the impact was, what it demonstrated about your capabilities. Build at least ten entries to create a robust counter-record.",
  },
  {
    id: "parachute-day-18",
    name: "Narrative Construction Part 1",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "narrativeTriptych",
    tags: ["core-parachute"],
    dayNumber: 18,
    whyNow: "You probably tell different versions of your job loss story to different people — and each version reveals something different.",
    science: "Writing multiple narrative versions engages the brain's story-making apparatus in the medial prefrontal cortex and temporal poles. Comparing versions reveals which emotional content is suppressed in public narratives and which is amplified in private ones.",
    instruction: "Write three versions of your story in the triptych panels: the polished version for acquaintances, the honest version for close friends, and the raw 3am version you tell yourself. Compare what you include and exclude across all three to find where the truth lives.",
  },
  {
    id: "parachute-day-19",
    name: "Structural Perspective: AI and Market",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-parachute"],
    dayNumber: 19,
    whyNow: "The tech industry is going through a massive structural shift. When you are in the middle of it, it is easy to take all of that personally.",
    science: "Contextualizing individual experience within systemic trends reduces personalization bias and shame. External attribution for genuinely systemic factors is not defensive — it is accurate, and accuracy supports healthier coping than misplaced self-blame.",
    instruction: "Follow the guided prompts to separate what is personal from what is systemic. Write about industry-wide changes, then identify which parts of your experience are shared by thousands of others, and which are genuinely about your individual performance.",
  },
  {
    id: "parachute-day-20",
    name: "Narrative Refinement",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-parachute"],
    dayNumber: 20,
    whyNow: "On Day 18, you wrote three versions of your story. Today you craft a version you can actually stand behind — true without punishing you.",
    science: "Narrative coherence is associated with better psychological adjustment post-trauma. Crafting an authentic account that integrates both personal agency and contextual factors engages the medial prefrontal cortex in self-referential processing that supports identity continuity.",
    instruction: "Follow the guided prompts to write your honest narrative. Test it by reading it back to yourself. Can you say it without apologizing, minimizing, or over-explaining? If it still costs energy to say, refine the parts that feel forced until the story is yours.",
  },
  {
    id: "parachute-day-21",
    name: "Skill Audit",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "wheelChart",
    tags: ["core-parachute"],
    dayNumber: 21,
    whyNow: "Job loss often triggers a crisis of confidence about your skills. But there is a difference between real skill gaps and fear-driven projections.",
    science: "Systematic skills assessment counteracts the global self-evaluation collapse that follows job loss. By disaggregating skills into categories — confident, atrophied, and feared-obsolete — the exercise engages analytical processing that overrides the amygdala's all-or-nothing threat response.",
    instruction: "Use the wheel chart to rate your confidence in different skill areas. Group skills into three rings: trusted capabilities in the center, atrophied skills in the middle, and feared-obsolete skills on the outer edge. For each outer-ring item, mark whether the fear is evidence-based or ambient anxiety.",
  },
  {
    id: "parachute-day-22",
    name: "Emergence Mapping",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "vennOverlap",
    tags: ["core-parachute"],
    dayNumber: 22,
    whyNow: "After weeks of processing, something new may be trying to get your attention — an interest or direction you have been dismissing as impractical.",
    science: "Emergence tracking engages the brain's default mode network in creative ideation and prospective thinking. Honoring dismissed interests activates intrinsic motivation circuits in the ventral striatum, which are often suppressed by fear-based career decision-making.",
    instruction: "Use the Venn diagram to map emerging interests, existing skills, and practical constraints. The overlap zones reveal where new directions are both authentic and feasible. Focus on the intersection where genuine curiosity meets transferable capability.",
  },
  {
    id: "parachute-day-23",
    name: "Integration Review",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "progressRiver",
    tags: ["core-parachute"],
    dayNumber: 23,
    whyNow: "You are three weeks in. Today is a day to pause and take stock — not to evaluate yourself, but to notice what has genuinely moved.",
    science: "Periodic self-assessment activates the brain's comparison circuits, enabling detection of gradual changes that are invisible day-to-day. Comparing current state to baseline strengthens metacognitive accuracy and counteracts change blindness.",
    instruction: "Use the progress river to trace your journey from Day 1 to now. Mark key shifts, surprises, and turning points along the flow. Note where the river widened (breakthroughs) and where it narrowed (stuck points) to see the full trajectory of your progress.",
  },
  {
    id: "parachute-day-24",
    name: "Seven Disruptions Reassessment",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "beforeAfter",
    tags: ["core-parachute"],
    dayNumber: 24,
    whyNow: "On Day 1, you rated each of the seven disruptions. Today, rate them again to see a concrete before-and-after comparison.",
    science: "Repeated-measures self-assessment provides the brain with concrete evidence of change, counteracting the tendency to discount gradual improvement. Side-by-side comparison activates spatial processing that makes abstract progress tangible.",
    instruction: "Use the before-and-after view to compare your Day 1 disruption ratings with today's ratings. Rate each disruption again on the same 1-10 scale, then review the side-by-side comparison to see where you moved the most and where disruption persists.",
  },
  {
    id: "parachute-day-25",
    name: "Saboteur Contingency Plan",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "saboteurCard",
    tags: ["core-parachute"],
    dayNumber: 25,
    whyNow: "By now you know your saboteurs. The challenge is that knowing about them does not stop them from showing up in high-pressure moments.",
    science: "Implementation intentions (if-then plans) leverage the brain's associative learning to create pre-programmed responses to anticipated triggers. Research shows if-then plans double follow-through rates by routing behavior through automatic associative pathways rather than effortful deliberation.",
    instruction: "For each saboteur card, write a specific if-then contingency plan: what the saboteur will say, what you will feel, and what you will do instead. Read each plan out loud to encode it through auditory rehearsal as well as visual processing.",
  },
  {
    id: "parachute-day-26",
    name: "Values Decision Framework",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "forcedChoice",
    tags: ["core-parachute"],
    dayNumber: 26,
    whyNow: "You have identified and ranked your values. Now it is time to turn them into a practical decision-making tool for real opportunities.",
    science: "Values-based decision frameworks reduce decision fatigue by pre-committing to evaluation criteria. When values are translated into concrete decision rules, the ventromedial prefrontal cortex can make faster, more consistent judgments under emotional pressure.",
    instruction: "Run your top values through realistic scenarios presented as forced choices. For each scenario, choose based on your values hierarchy and then reflect on whether the choice felt aligned or revealed a gap between stated and lived values.",
  },
  {
    id: "parachute-day-27",
    name: "Narrative Under Conditions",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "narrativeTriptych",
    tags: ["core-parachute"],
    dayNumber: 27,
    whyNow: "On Day 20, you wrote the version of your story you could stand behind. Today you test it under more realistic conditions.",
    science: "Narrative rehearsal under simulated pressure conditions activates the same neural circuits used in real performance. Practicing a story out loud engages motor speech areas and auditory feedback loops that strengthen the narrative's stability under stress.",
    instruction: "Write three versions in the triptych: the saboteur's version of your story, the centered version, and the repair version for when you lose your center mid-telling. Practice the centered version by speaking it aloud and noting where your body tenses or relaxes.",
  },
  {
    id: "parachute-day-28",
    name: "Open Threads Inventory",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "cardSort",
    tags: ["core-parachute"],
    dayNumber: 28,
    whyNow: "Not everything gets resolved in 30 days — and pretending it does would be dishonest. Take an honest inventory of what remains unfinished.",
    science: "Explicit acknowledgment of unresolved issues reduces cognitive load by converting rumination into organized awareness. Categorizing open threads by needed action engages executive function to triage rather than catastrophize about what remains undone.",
    instruction: "Sort your open threads into categories: needs more time, needs professional support, needs a specific action, and needs continued practice. For each card, note the concrete next step. The sort makes the invisible visible and converts vague worry into structured awareness.",
  },
  {
    id: "parachute-day-29",
    name: "Letter to Future Self",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-parachute"],
    dayNumber: 29,
    whyNow: "You will receive a summary of your 30-day journey. Read it, then write a letter to yourself 90 days from now anchoring what you learned.",
    science: "Future-self communication activates prospective memory systems and the medial prefrontal cortex's self-projection circuits. Letters to future selves increase commitment to behavior change by strengthening temporal self-continuity.",
    instruction: "Follow the guided prompts to review your 30-day summary, then write your letter. Address what you learned, what commitments you are making, and what you hope will be different. Be honest and specific — this letter becomes your anchor point when clarity fades.",
  },
  {
    id: "parachute-day-30",
    name: "One Sentence",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-parachute"],
    dayNumber: 30,
    whyNow: "This is the final exercise. Write one sentence that captures where you are today — not where you wish you were or think you should be.",
    science: "Compression exercises force the brain to distill complex emotional states into their essence, activating the ventromedial prefrontal cortex's integration function. The constraint of a single sentence bypasses narrative defenses and performance, producing radical honesty.",
    instruction: "Follow the guided prompt to write one sentence about where you actually are right now. Resist the urge to perform progress, minimize, or catastrophize. Read it back to yourself slowly and sit with how it feels to state the truth simply.",
  },

  // ─────────────────────────────────────────────────────────────
  // JETSTREAM (PIP Navigation) — 30 Days
  // ─────────────────────────────────────────────────────────────

  {
    id: "jetstream-day-1",
    name: "Seven Disruptions Inventory (PIP)",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "wheelChart",
    tags: ["core-jetstream"],
    dayNumber: 1,
    whyNow: "A performance improvement plan does not just affect your work — it disrupts multiple parts of your life at once. Rate the seven disruptions.",
    science: "Multi-domain disruption assessment activates metacognitive monitoring, creating a baseline that prevents single-issue fixation and reveals how threat at work cascades into psychological safety, competence, and relational stability.",
    instruction: "Use the wheel chart to rate each of the seven PIP-specific disruptions from 1 to 10: psychological safety, sense of competence, professional identity, financial security, trust in the system, relational stability, and future clarity.",
  },
  {
    id: "jetstream-day-2",
    name: "Saboteur Identification (PIP-Specific)",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "cardSort",
    tags: ["core-jetstream"],
    dayNumber: 2,
    whyNow: "Under stress, automatic protection strategies activate — patterns that once helped you cope but can now work against you during a PIP.",
    science: "Externalizing saboteur patterns creates cognitive defusion, allowing the prefrontal cortex to evaluate automatic stress responses rather than being fused with them. Identifying stress direction (toward, against, away) adds a second axis of self-awareness.",
    instruction: "Sort the saboteur cards into your top patterns, occasional patterns, and patterns that do not apply. For each one you select, add notes about your stress direction: do you move toward people, push against them, or pull away?",
  },
  {
    id: "jetstream-day-3",
    name: "The Saboteur Log",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "heatmap",
    tags: ["core-jetstream"],
    dayNumber: 3,
    whyNow: "Now that you know your saboteur patterns, the next step is catching them in real time. The tracking itself is the intervention.",
    science: "Self-monitoring creates a metacognitive feedback loop that gradually widens the gap between trigger and response. Research on habit change shows that awareness-based interventions produce more durable change than willpower-based approaches.",
    instruction: "Use the heatmap to log saboteur activations by situation and time. For each activation, note the trigger, which saboteur fired, what it said, and what you did. Over time the heatmap reveals your most vulnerable patterns and moments.",
  },
  {
    id: "jetstream-day-4",
    name: "Document vs. Story",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "splitAnnotator",
    tags: ["core-jetstream"],
    dayNumber: 4,
    whyNow: "When we are under threat, our brain automatically adds meaning to what we read — turning neutral words into verdicts. Separate document from story.",
    science: "The two-column technique leverages the distinction between observation and evaluation from NVC and cognitive therapy. By physically separating document text from interpretation, the exercise engages analytical processing to override threat-driven meaning-making.",
    instruction: "In the left column, copy the exact words from the PIP document. In the right column, write the story your mind has layered on top — the interpretations, worst-case assumptions, and mind-reading. Notice which saboteur wrote each story element.",
  },
  {
    id: "jetstream-day-5",
    name: "Three Columns (Valid / Political / Cannot Tell)",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "cardSort",
    tags: ["core-jetstream"],
    dayNumber: 5,
    whyNow: "Not all feedback on a PIP is equal. Some points to real growth areas. Some reflects politics. Some sits in uncomfortable ambiguity.",
    science: "Tripartite sorting resists the binary thinking that evaluation threat produces. The 'cannot tell' column is the key innovation — it engages tolerance of ambiguity, which research links to better decision-making under uncertainty.",
    instruction: "Sort each piece of PIP feedback into three columns: Valid (genuine development areas), Political (organizational dynamics, not your performance), and Cannot Tell (genuinely ambiguous). Sit with the Cannot Tell column — it is where the real work lives.",
  },
  {
    id: "jetstream-day-6",
    name: "Reading the Room",
    modality: "systems",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "stakeholderMap",
    tags: ["core-jetstream"],
    dayNumber: 6,
    whyNow: "A PIP does not happen in a vacuum. There are people, incentives, and organizational dynamics behind it. Map the political landscape strategically.",
    science: "Strategic stakeholder mapping activates the mentalizing network (medial prefrontal cortex, temporoparietal junction), enabling theory-of-mind about organizational actors. Understanding others' incentives reduces personalization of systemic decisions.",
    instruction: "Map the key players on the stakeholder map: who initiated the PIP, who are your advocates, what is HR's stance, and what signals is your manager sending. Rate the survivability of the PIP honestly, then check whether your saboteur is distorting the estimate.",
  },
  {
    id: "jetstream-day-7",
    name: "Building Your Workday Toolkit (PIP-Specific)",
    modality: "somatic",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "zonedSpectrum",
    tags: ["core-jetstream"],
    dayNumber: 7,
    whyNow: "When you are on a PIP, your nervous system is on high alert all day. Regulation means having quick tools to get back to a state where you can think clearly.",
    science: "Micro-regulation anchors leverage the polyvagal system's capacity for rapid state shifts. Slow exhales activate the vagus nerve's parasympathetic brake, shifting from sympathetic arousal to ventral vagal engagement in under 60 seconds.",
    instruction: "Use the zoned spectrum to design three regulation anchors matched to different stress zones: pre-meeting grounding, between-meetings reset, and end-of-day release. Position each anchor on the spectrum from high activation to calm, and write the specific steps for each.",
  },
  {
    id: "jetstream-day-8",
    name: "Weekend Integration (Week 1 Reflection)",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "narrativeTriptych",
    tags: ["core-jetstream"],
    dayNumber: 8,
    whyNow: "Review your saboteur log from the week. Notice any patterns you did not expect — which saboteur surprised you by being louder than you thought?",
    science: "Weekly reflection consolidates daily observations into pattern recognition. The spacing effect in memory research shows that reviewing material after a delay strengthens long-term retention and deeper encoding of behavioral patterns.",
    instruction: "Use the triptych to write about three dimensions of your week: what your saboteur log revealed, what surprised you, and what you want to carry into next week. The three-panel view helps you see the week from multiple angles simultaneously.",
  },
  {
    id: "jetstream-day-9",
    name: "Weekend Integration (Communication Preview)",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-jetstream"],
    dayNumber: 9,
    whyNow: "If you could tell your manager one thing with no consequences, what would it be? Notice which saboteur edits that statement before you finish.",
    science: "Unsent letter exercises provide emotional catharsis by engaging the brain's expressive writing circuits without the social consequences of actual disclosure. This process reduces inhibition and activates insight generation.",
    instruction: "Follow the guided prompts to write what you would say with no consequences, notice the saboteur edits, and then explore what the unedited version reveals about your actual needs in the manager relationship.",
  },
  {
    id: "jetstream-day-10",
    name: "Communication Under Pressure — Part 1: Observation",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-jetstream"],
    dayNumber: 10,
    whyNow: "When we feel evaluated or threatened, the way we communicate changes — often without us realizing it. Learn the four-part framework to see the gaps.",
    science: "The NVC framework (Observation, Feeling, Need, Request) forces disaggregation of automatic communication into component parts, engaging prefrontal analytical circuits to override amygdala-driven defensive or compliant communication patterns.",
    instruction: "Follow the guided prompts to analyze three recent PIP-related interactions using the four-part communication framework. For each interaction, separate what happened, how you felt, what you needed, and what you actually said or did.",
  },
  {
    id: "jetstream-day-11",
    name: "Communication Under Pressure — Part 2: The Check-In Plan",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "dialogueSequence",
    tags: ["core-jetstream"],
    dayNumber: 11,
    whyNow: "Today you prepare for your next PIP check-in using the four-part framework — so you walk in with something centered to say.",
    science: "Cognitive rehearsal of difficult conversations activates the same neural motor planning circuits used in actual communication. Writing saboteur-version and centered-version side by side engages comparative processing that strengthens the centered option.",
    instruction: "Follow the dialogue sequence to prepare your next check-in. Write the saboteur's version of what you would say, then write the centered version using observation-feeling-need-request. Practice the centered version out loud through the guided prompts.",
  },
  {
    id: "jetstream-day-12",
    name: "Stress Responses in Relationships",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "multiSpectrum",
    tags: ["core-jetstream"],
    dayNumber: 12,
    whyNow: "Work stress does not stay at work. It follows you home and shows up in how you interact with the people closest to you.",
    science: "Gottman's Four Horsemen framework identifies the four most destructive communication patterns in relationships. Under sustained work threat, these patterns activate more frequently because the nervous system does not distinguish between work and home contexts.",
    instruction: "Use the multi-spectrum sliders to rate how much each of the Four Horsemen shows up in your closest relationships: criticism, contempt, defensiveness, and stonewalling. For the highest-rated pattern, identify one specific antidote to practice this week.",
  },
  {
    id: "jetstream-day-13",
    name: "The Optionality Audit",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "wheelChart",
    tags: ["core-jetstream"],
    dayNumber: 13,
    whyNow: "When you feel trapped, you make fear-based decisions. When you know you have options, you make strategic ones. Map your leverage.",
    science: "Perceived optionality reduces cortisol output and shifts decision-making from the amygdala's threat response to the prefrontal cortex's strategic planning circuits. Knowing you have choices changes how you sit in every meeting.",
    instruction: "Use the wheel chart to rate four domains of optionality from 1 to 10: financial, legal, professional, and relational. For each domain, identify one concrete action to strengthen your position this week.",
  },
  {
    id: "jetstream-day-14",
    name: "The Fork",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "forceField",
    tags: ["core-jetstream"],
    dayNumber: 14,
    whyNow: "Most people on a PIP are quietly avoiding a decision — neither fully committing to meeting the PIP nor fully preparing to leave.",
    science: "Force field analysis makes competing motivations visible by separating driving and restraining forces for each option. This engages the dorsolateral prefrontal cortex in deliberative processing that overcomes decision avoidance maintained by emotional ambivalence.",
    instruction: "Map the forces driving you toward staying versus leaving. On one side, list everything pushing you to meet the PIP. On the other, everything pulling you toward preparing to leave. Note which forces are saboteur-driven versus evidence-based.",
  },
  {
    id: "jetstream-day-15",
    name: "Weekend Integration (Communication Reflection)",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "splitAnnotator",
    tags: ["core-jetstream"],
    dayNumber: 15,
    whyNow: "Notice how your communication changes over the weekend when you are not performing for anyone. What is different about how you talk and listen?",
    science: "Comparing communication patterns across contexts reveals the degree of threat-driven distortion at work. Weekend communication often represents the baseline that work communication has diverged from under PIP pressure.",
    instruction: "In the left column, describe how you communicate at work during the PIP. In the right column, describe how you communicate on the weekend with no evaluation pressure. The gap between the two columns shows the PIP's communication cost.",
  },
  {
    id: "jetstream-day-16",
    name: "Weekend Integration (Trust and Truth)",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-jetstream"],
    dayNumber: 16,
    whyNow: "If you trusted yourself completely right now, what would you do about this PIP? Not what is safe — what is true.",
    science: "Self-trust exercises activate the ventromedial prefrontal cortex's somatic marker system, accessing intuitive knowledge that strategic calculation often overrides. Separating intuitive knowing from fear-based calculation can reveal clarity that deliberation obscures.",
    instruction: "Follow the guided prompts to explore what you would do if fear were not a factor. Then examine what your saboteur says about that answer. The exercise surfaces the gap between what you know and what you allow yourself to act on.",
  },
  {
    id: "jetstream-day-17",
    name: "Cognitive Distortion Audit on the PIP's Competence Claims",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-jetstream"],
    dayNumber: 17,
    whyNow: "When we are under threat, our thinking becomes systematically distorted. This tests both the PIP's claims and your self-assessment against five cognitive distortions.",
    science: "Cognitive distortion identification engages the analytical prefrontal cortex to evaluate the accuracy of threat-driven self-assessments. Research shows that naming specific distortions (overgeneralization, mental filter, etc.) reduces their influence on subsequent judgment.",
    instruction: "Follow the guided prompts to test the PIP's competence claims and your own self-assessment against five cognitive distortions. For each distortion, write the distorted version and the accurate version. Accurate does not mean positive — it means honest and proportional.",
  },
  {
    id: "jetstream-day-18",
    name: "The Saboteur's Professional Cost",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "heatmap",
    tags: ["core-jetstream"],
    dayNumber: 18,
    whyNow: "You have been tracking saboteur patterns for over two weeks. Step back and look at the bigger picture — what has the pattern actually cost you?",
    science: "Quantifying the real-world cost of automatic patterns transforms abstract self-awareness into concrete motivation for change. Cost accounting activates the brain's loss aversion circuits, which are more motivating than gain-based framing.",
    instruction: "Use the heatmap to map the costs of your most persistent saboteur across four dimensions: frequency of activation, professional cost, relational cost, and the hidden payoff it provides. High-intensity areas reveal where the pattern is doing the most damage.",
  },
  {
    id: "jetstream-day-19",
    name: "Boundary Architecture (What You Will and Will Not Do)",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "cardSort",
    tags: ["core-jetstream"],
    dayNumber: 19,
    whyNow: "When you are on a PIP, there is enormous pressure to say yes to everything. But agreeing without limits leads to burnout that undermines performance.",
    science: "Explicit boundary-setting engages the dorsolateral prefrontal cortex in top-down regulation of compliance behavior. Categorizing demands into will do, will do with boundary, and will not do provides a decision structure that prevents reactive over-accommodation.",
    instruction: "Sort the PIP's expectations into three categories: Will Do (legitimate requirements), Will Do With a Boundary (vague items needing negotiation), and Will Not Do (items crossing your lines). For each boundary item, write a negotiation statement using observation-feeling-need-request.",
  },
  {
    id: "jetstream-day-20",
    name: "Perspective on Performance Culture and PIPs",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-jetstream"],
    dayNumber: 20,
    whyNow: "A PIP is not just a personal event. It exists within an organizational system that uses PIPs for two very different purposes. Zoom out and see the bigger picture.",
    science: "Structural reframing shifts attributions from internal-stable-global to external-unstable-specific, reducing shame while preserving accountability. Understanding organizational incentives activates the mentalizing network and depersonalizes systemic decisions.",
    instruction: "Follow the guided prompts to explore the structural context of your PIP. Write about what was happening in the organization before and during your PIP, and separate structural shame from personal shame. Understanding the system makes the shame more accurate.",
  },
  {
    id: "jetstream-day-21",
    name: "Dual-Track Status Check",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "forceField",
    tags: ["core-jetstream"],
    dayNumber: 21,
    whyNow: "Since Day 14, you have held two tracks — meeting the PIP and preparing for the possibility of leaving. Time for a status check on both.",
    science: "Dual-track monitoring prevents the cognitive narrowing that threat produces. Maintaining awareness of multiple options preserves prefrontal flexibility and prevents the tunnel vision that makes people either fully compliant or fully resistant.",
    instruction: "Use the force field to map your current status on both tracks. On one side, list your Track A progress (meeting the PIP). On the other, list Track B progress (optionality in financial, legal, professional, and relational domains). Decide where your energy goes this week.",
  },
  {
    id: "jetstream-day-22",
    name: "Weekend Integration (Communication Patterns)",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "beforeAfter",
    tags: ["core-jetstream"],
    dayNumber: 22,
    whyNow: "Notice your communication this weekend. Where are you centered? Where does the PIP version of you show up even when you are not at work?",
    science: "Comparing weekend communication to weekday communication reveals the extent of threat-driven behavioral contamination. Noticing PIP patterns leaking into personal life activates metacognitive awareness of context-inappropriate threat responses.",
    instruction: "Use the before-and-after view to compare your communication patterns at work versus at home. Map specific behaviors in each context and identify where the PIP version of you is showing up outside of work situations.",
  },
  {
    id: "jetstream-day-23",
    name: "Weekend Integration (Competence Reflection)",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-jetstream"],
    dayNumber: 23,
    whyNow: "One thing you know to be true about your professional capability that no PIP can change. If you cannot answer that yet, sit with that.",
    science: "Anchoring exercises that connect to stable self-knowledge activate the ventromedial prefrontal cortex's self-referential processing independent of external evaluation. This builds a competence foundation that is not contingent on one manager's assessment.",
    instruction: "Follow the guided prompts to identify core professional capabilities that exist independent of any PIP. Write about what you know to be true about your competence, and notice where the cognitive distortion work from Day 17 helps or where more work is needed.",
  },
  {
    id: "jetstream-day-24",
    name: "Reassessment",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-jetstream"],
    dayNumber: 24,
    whyNow: "On Day 1, you rated seven disruptions. Three weeks have passed. Rate each one again and compare to see what shifted and what persists.",
    science: "Repeated-measures assessment provides concrete evidence of change, counteracting the tendency to discount gradual improvement. The comparison activates spatial processing that makes abstract progress tangible and actionable.",
    instruction: "Follow the guided prompts to re-rate each of the seven PIP disruptions on the same 1-10 scale. Then compare your Day 1 ratings with today's ratings. Identify where the biggest shifts occurred and where your attention needs to go in the final week.",
  },
  {
    id: "jetstream-day-25",
    name: "The Older Pattern",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "hierarchicalBranch",
    tags: ["core-jetstream"],
    dayNumber: 25,
    whyNow: "A PIP hits hard not just because of the job threat, but because it activates older scripts about evaluation, authority, and failure.",
    science: "Tracing current patterns to early origins engages autobiographical memory networks and the hippocampus. Making the connection between present-tense reactions and historical patterns creates the cognitive distance needed to choose whether to keep running inherited programs.",
    instruction: "Build a hierarchical branch from family beliefs about failure at the root, through early authority experiences in the middle, to your current PIP response at the leaves. Map how each layer informed the next to see the full chain of inherited evaluation patterns.",
  },
  {
    id: "jetstream-day-26",
    name: "The Centered Conversation",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "narrativeTriptych",
    tags: ["core-jetstream"],
    dayNumber: 26,
    whyNow: "This brings together everything — clear communication, saboteur awareness, boundary setting, and relationship repair — into one conversation.",
    science: "Integrated skill rehearsal activates multiple neural networks simultaneously — communication planning, emotional regulation, boundary maintenance, and repair readiness — creating more robust performance under pressure than practicing any skill in isolation.",
    instruction: "Write three versions of your most important upcoming conversation in the triptych: the saboteur's version, the centered version using observation-feeling-need-request, and the repair version for when you lose your center. Practice the centered and repair versions out loud.",
  },
  {
    id: "jetstream-day-27",
    name: "Pattern Testing — The Full System",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "dialogueSequence",
    tags: ["core-jetstream"],
    dayNumber: 27,
    whyNow: "This is the capstone exercise — a full simulation that tests everything you have built over four weeks against a high-stakes scenario.",
    science: "Full-system simulation activates the brain's predictive processing networks, running the complete toolkit against a realistic scenario. Research on mental simulation shows that imagined practice produces measurable skill improvement through shared neural circuitry.",
    instruction: "Follow the dialogue sequence to simulate your highest-stakes scenario. First, write how it plays out with the saboteur running it. Then rewrite the same scene using every tool you have built. Notice which tools feel natural and which still feel forced — the natural ones are yours to keep.",
  },
  {
    id: "jetstream-day-28",
    name: "Honest Inventory of Open Threads",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "cardSort",
    tags: ["core-jetstream"],
    dayNumber: 28,
    whyNow: "This program does not tie everything up neatly in 30 days. Today, name what is still unresolved — clearly and without judgment.",
    science: "Explicit acknowledgment of unresolved issues reduces cognitive load by converting rumination into organized awareness. Categorizing open threads engages executive function to triage rather than catastrophize.",
    instruction: "Sort your open threads into categories: needs more time, needs a specific resource (therapist, lawyer, advisor), needs an avoided conversation, and needs continued practice. For each card, note the concrete next step.",
  },
  {
    id: "jetstream-day-29",
    name: "Letter to Future Self",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-jetstream"],
    dayNumber: 29,
    whyNow: "The system will generate a summary of your 30-day journey. Read it, then write a letter to yourself 90 days from now as an anchor for what you learned.",
    science: "Future-self communication activates prospective memory systems and strengthens temporal self-continuity. The letter serves as an external memory aid for insights that will fade as day-to-day pressures resume.",
    instruction: "Follow the guided prompts to review your 30-day summary. Then write a letter to the person you will be in 90 days — whether the PIP resolved well or not. Include which tools to carry forward and what to remember when the next high-pressure evaluation happens.",
  },
  {
    id: "jetstream-day-30",
    name: "One Sentence",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-jetstream"],
    dayNumber: 30,
    whyNow: "This is the final exercise. Where are you today? Not where you wish you were. Not where the PIP says you should be. Where you actually are.",
    science: "Single-sentence distillation forces cognitive integration across all program themes, activating the ventromedial prefrontal cortex's synthesis function. The constraint of one sentence bypasses narrative performance and produces radical honesty.",
    instruction: "Follow the guided prompt to revisit your disruption ratings and saboteur patterns, notice what shifted and what stayed the same, and then write one honest sentence about where you are. One sentence is worth more than a hundred aspirational ones.",
  },

  // ─────────────────────────────────────────────────────────────
  // BASECAMP (New Role) — 30 Days
  // ─────────────────────────────────────────────────────────────

  {
    id: "basecamp-day-1",
    name: "The Seven Disruptions Inventory (New Role Version)",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "wheelChart",
    tags: ["core-basecamp"],
    dayNumber: 1,
    whyNow: "Starting a new role disrupts more than just your calendar. Even when it is exciting, it can quietly shake your confidence and sense of belonging.",
    science: "Multi-domain disruption assessment for positive transitions reveals that even desired changes activate the brain's change-detection circuits. Rating each area engages systematic self-evaluation that prevents blind spots in transitions that feel like they should be purely positive.",
    instruction: "Use the wheel chart to rate seven new-role disruptions from 1 to 10: competence confidence, social belonging, cultural fluency, identity continuity, clarity of expectations, routine and rhythm, and authority and credibility.",
  },
  {
    id: "basecamp-day-2",
    name: "Operational Values",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "bubbleSort",
    tags: ["core-basecamp"],
    dayNumber: 2,
    whyNow: "This exercise defines how you want to behave in specific work situations — before the pressure hits. These are commitments, not aspirations.",
    science: "Pre-commitment to behavioral intentions (implementation intentions) leverages the brain's associative learning to create if-then responses. Research shows that pre-deciding behavior for anticipated scenarios doubles follow-through under pressure.",
    instruction: "You will see pairs of operational value commitments. For each pair, choose which matters more to you. The bubble sort produces a ranked list of your behavioral commitments that you will revisit throughout the program to check for drift.",
  },
  {
    id: "basecamp-day-3",
    name: "Saboteurs, Centers, and Reactive Tendencies (Integrated)",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "cardSort",
    tags: ["core-basecamp"],
    dayNumber: 3,
    whyNow: "When we are in unfamiliar territory, automatic patterns take over. This looks at yours from three angles: saboteurs, intelligence centers, and reactive tendencies.",
    science: "Triangulating self-awareness through three frameworks (saboteurs, centers of intelligence, reactive tendencies) provides a more robust pattern profile than any single framework alone. Multiple perspectives engage different self-referential processing networks.",
    instruction: "Sort cards across three dimensions: identify your top saboteurs, mark your dominant intelligence center (thinking, feeling, doing), and select your reactive tendency (comply, protect, control). Notice how the three connect into a single pattern.",
  },
  {
    id: "basecamp-day-4",
    name: "Cultural Dimensions Mapping",
    modality: "systems",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "multiSpectrum",
    tags: ["core-basecamp"],
    dayNumber: 4,
    whyNow: "Every workplace has an invisible operating system. When you start a new role, you are learning a new cultural language whether you realize it or not.",
    science: "Cultural dimension mapping engages the brain's social cognition networks to systematically compare implicit norms. Explicitly rating cultural dimensions reduces the likelihood of miscommunication caused by unconscious cultural assumptions.",
    instruction: "Use the multi-spectrum sliders to rate the new culture on six dimensions: directness, enthusiasm, formality, assertiveness, self-promotion, and personal disclosure. Then set a second marker for your own natural style. The gaps reveal where adaptation is most needed.",
  },
  {
    id: "basecamp-day-5",
    name: "Stakeholder Map — The Five Conversations",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "stakeholderMap",
    tags: ["core-basecamp"],
    dayNumber: 5,
    whyNow: "Your success depends partly on the relationships you build. A stakeholder map helps you see who matters and why — not to be political, but to be intentional.",
    science: "Stakeholder mapping activates the mentalizing network to systematically consider others' perspectives, roles, and influence. Categorizing contacts by function (historians, cultural interpreters, integrators, experts, pulse-readers) ensures comprehensive coverage.",
    instruction: "Place people on the stakeholder map by their type: historians, cultural interpreters, integrators, technical experts, and pulse-readers. For each person, write a specific question you want to ask them. Specific questions make it more likely these conversations actually happen.",
  },
  {
    id: "basecamp-day-6",
    name: "Week 1 Integration",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "progressRiver",
    tags: ["core-basecamp"],
    dayNumber: 6,
    whyNow: "This week you created five different assessments. Each tells part of the story. Look across all five and notice where they connect.",
    science: "Cross-assessment integration activates the brain's pattern recognition circuits by requiring synthesis across multiple self-assessments. Finding connections between independent data sources produces deeper insight than any single assessment alone.",
    instruction: "Use the progress river to trace your Week 1 journey across all five assessments. Mark where assessments connect (e.g., biggest disruption links to loudest saboteur). Note the patterns that emerge across your disruptions, values, saboteurs, cultural map, and stakeholder map.",
  },
  {
    id: "basecamp-day-7",
    name: "Values Test Review",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "beforeAfter",
    tags: ["core-basecamp"],
    dayNumber: 7,
    whyNow: "Have any of your Day 2 operational values been tested this week? This is your first real-world data on whether your commitments hold under pressure.",
    science: "Values-behavior comparison activates the anterior cingulate cortex's conflict monitoring system. Detecting discrepancies between intended and actual behavior is the mechanism through which values become actionable rather than aspirational.",
    instruction: "Use the before-and-after view to compare your Day 2 value commitments with this week's actual behavior. For each value, mark whether it was tested, whether you held the line or drifted, and what pulled you off course if you drifted.",
  },
  {
    id: "basecamp-day-8",
    name: "Three Levels of Listening",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "emotionalArc",
    tags: ["core-basecamp"],
    dayNumber: 8,
    whyNow: "Most of us think listening means hearing words. But there are three levels, and the deeper levels pick up information that words alone cannot carry.",
    science: "Level 3 (global) listening activates the right hemisphere's holistic processing, picking up emotional tone, body language, and systemic dynamics that left-hemisphere verbal processing misses. Deliberate listening practice strengthens neural pathways for social perception.",
    instruction: "Move through the emotional arc of a listening experience: start at Level 1 (internal processing), shift to Level 2 (focused attention), and reach Level 3 (global awareness). At each level, write what you notice. The arc tracks your progression from self-focused to other-focused to whole-room awareness.",
  },
  {
    id: "basecamp-day-9",
    name: "Power & Proximity Mapping",
    modality: "systems",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "stakeholderMap",
    tags: ["core-basecamp"],
    dayNumber: 9,
    whyNow: "In every organization, there is the official structure and the real structure. Understanding both is essential when you are new.",
    science: "Power mapping activates the brain's social hierarchy processing circuits in the anterior cingulate and medial prefrontal cortex. Understanding informal influence networks reduces the anxiety of navigating an unfamiliar organizational system.",
    instruction: "Map key players on the stakeholder map by their power sources: formal authority, resource control, information control, network position, and reputation. Then position them by relational proximity — how close or distant each relationship feels right now.",
  },
  {
    id: "basecamp-day-10",
    name: "Reading Your Manager (Implicit Contract + Communication Style)",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "multiSpectrum",
    tags: ["core-basecamp"],
    dayNumber: 10,
    whyNow: "Your relationship with your manager is probably the single most important relationship in your new role. Much of what they need is never stated explicitly.",
    science: "Implicit contract analysis activates theory-of-mind processing by requiring you to infer your manager's unstated needs, pressures, and preferences. Systematic inference reduces the social anxiety of managing up by making the relationship more predictable.",
    instruction: "Use the multi-spectrum sliders to map your manager's preferences across several dimensions: communication style, feedback approach, decision-making orientation, and what they value most. Set a second marker for your own defaults. The gaps show where to adapt your approach.",
  },
  {
    id: "basecamp-day-11",
    name: "Communication Style Map + Instinctual Priorities",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "multiSpectrum",
    tags: ["core-basecamp"],
    dayNumber: 11,
    whyNow: "You do not need to become a different person for every colleague. But small adjustments in how you communicate can dramatically improve how your ideas land.",
    science: "Communication style mapping activates social cognition circuits by requiring observation of others' preferences. Adapting communication delivery to the receiver's preferred style leverages the brain's mirroring systems to build rapport more efficiently.",
    instruction: "Use the multi-spectrum sliders to map 3-5 key colleagues on five communication dimensions: data-driven vs. intuitive, task-first vs. relationship-first, independent vs. collaborative, big-picture vs. detail-oriented, and harmony-seeking vs. direct. Note one adjustment per person.",
  },
  {
    id: "basecamp-day-12",
    name: "The Authenticity-Adaptation Map",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "cardSort",
    tags: ["core-basecamp"],
    dayNumber: 12,
    whyNow: "Every new role asks you to adapt. The key question is: which adaptations are fine, which need watching, and which cross a line you should not cross?",
    science: "Categorizing adaptations engages the prefrontal cortex's evaluation circuits to distinguish sustainable flexibility from identity-threatening accommodation. The three-category sort prevents the false binary of either fully adapting or fully resisting.",
    instruction: "Sort your cultural adaptations into three categories: Flex Comfortably (costs you nothing), Flex With Awareness (touches something that matters — needs monitoring), and Non-Negotiable (violates your Day 2 values). Check whether your saboteur is distorting the sorting.",
  },
  {
    id: "basecamp-day-13",
    name: "Week 2 Integration",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "progressRiver",
    tags: ["core-basecamp"],
    dayNumber: 13,
    whyNow: "This week you built several relationship and communication tools. Each gives a different view of the same system you are navigating.",
    science: "Weekly integration consolidates multiple data streams into coherent pattern recognition. The spacing effect ensures that reviewing material after a delay strengthens long-term encoding and produces deeper cross-assessment insight.",
    instruction: "Use the progress river to trace your Week 2 journey across all your relationship tools. Mark connections between your listening practice, power map, manager strategy, colleague communication map, and authenticity-adaptation map. Note what patterns emerge.",
  },
  {
    id: "basecamp-day-14",
    name: "Forward Positioning",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "timelineRiver",
    tags: ["core-basecamp"],
    dayNumber: 14,
    whyNow: "On Day 9 you drew a relational map. Pull it out and look at it with fresh eyes after a full week of relationship-building.",
    science: "Prospective relationship mapping activates the brain's simulation networks to envision future social positions. Setting specific relational intentions converts vague goals into actionable plans that engage the prefrontal planning circuits.",
    instruction: "Use the timeline river to map your relational trajectory from Day 1 through now and into the next 60 days. Plot where key relationships are today and where you want them to be. Set 2-3 specific, actionable intentions for Week 3.",
  },
  {
    id: "basecamp-day-15",
    name: "Selecting Your Early Wins",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "forcedChoice",
    tags: ["core-basecamp"],
    dayNumber: 15,
    whyNow: "The best early contributions are not about proving you belong. They are about delivering genuine value that builds trust and credibility.",
    science: "Structured early-win selection engages the prefrontal cortex's planning circuits to evaluate potential contributions against multiple criteria (visibility, alignment, achievability, values-consistency). This prevents the anxiety-driven over-delivery that undermines new-role transitions.",
    instruction: "For each pair of potential contributions, choose which better meets the four early-win criteria: visible to the right people, aligned with your manager's priorities, achievable with current access, and consistent with your values. The forced-choice process reveals your most strategic option.",
  },
  {
    id: "basecamp-day-16",
    name: "Creative vs. Reactive Contribution",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "spectrumSlider",
    tags: ["core-basecamp"],
    dayNumber: 16,
    whyNow: "There is an important difference between contributions from a grounded, authentic place and contributions driven by anxiety or self-protection.",
    science: "Distinguishing creative from reactive contributions activates the prefrontal cortex's self-monitoring circuits. Creative contributions (relating, self-awareness, authenticity) engage intrinsic motivation, while reactive ones (complying, protecting, controlling) are driven by threat avoidance.",
    instruction: "Use the spectrum slider to place each of your recent contributions on a scale from fully reactive to fully creative. For contributions closer to the reactive end, identify which protective pattern drove them. For creative ones, note what conditions made them possible.",
  },
  {
    id: "basecamp-day-17",
    name: "Communication Calibration",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "narrativeTriptych",
    tags: ["core-basecamp"],
    dayNumber: 17,
    whyNow: "How you communicate at work is not just about what you say — it is about how, when, and to whom. Every culture has different norms for the hardest moments.",
    science: "Communication calibration exercises engage the brain's social learning circuits by making implicit cultural norms explicit. Comparing your default communication style against cultural expectations activates the conflict monitoring system, enabling deliberate adaptation.",
    instruction: "Use the triptych to examine three communication acts: how you disagree, how you advocate for ideas, and how you say no. In each panel, write how the culture does it, how your default compares, and what adjustment you will make. Refer back to your Day 12 flex categories.",
  },
  {
    id: "basecamp-day-18",
    name: "Imposter Pattern Identification",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "splitAnnotator",
    tags: ["core-basecamp"],
    dayNumber: 18,
    whyNow: "Nearly everyone experiences imposter syndrome during a role transition, but not everyone experiences it the same way. Knowing your type helps you challenge it.",
    science: "Imposter syndrome typology (Perfectionist, Superwoman, Natural Genius, Soloist, Expert) provides targeted cognitive leverage. Naming the specific type activates the prefrontal cortex's categorization circuits, breaking the generalized feeling of fraudulence into a specific, addressable pattern.",
    instruction: "In the left column, write the specific claims your imposter is making. In the right column, test each claim against cognitive distortion categories: is it all-or-nothing, mind-reading, discounting evidence, or confusing a learning curve with a permanent limitation? The split view exposes the distortion.",
  },
  {
    id: "basecamp-day-19",
    name: "Navigating Friction From Values",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "vennOverlap",
    tags: ["core-basecamp"],
    dayNumber: 19,
    whyNow: "By the third week, some kind of friction usually shows up. Friction is not a sign that something is wrong — it is information.",
    science: "Multi-lens friction analysis (cultural, saboteur, values, communication) prevents the single-attribution error that makes friction feel personal when it may be systemic. Examining friction through four lenses engages multiple processing networks simultaneously.",
    instruction: "Use the Venn diagram to map the sources of your friction: cultural gap, saboteur reaction, values violation, and communication mismatch. The overlaps reveal where multiple factors converge, and the non-overlapping areas show which single lens best explains the friction.",
  },
  {
    id: "basecamp-day-20",
    name: "Week 3 Integration",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "progressRiver",
    tags: ["core-basecamp"],
    dayNumber: 20,
    whyNow: "Week 3 was about action — moving from observing into actually contributing and communicating in your new environment. Find the through-line.",
    science: "End-of-phase integration consolidates action-oriented experiences into narrative coherence. Synthesizing contributions, communication patterns, imposter responses, and friction navigation creates a comprehensive self-model for the new role.",
    instruction: "Use the progress river to trace your Week 3 journey across action themes: early wins, creative vs. reactive contributions, communication calibration, imposter patterns, and friction navigation. Mark the single most important insight to carry into Week 4.",
  },
  {
    id: "basecamp-day-21",
    name: "Progress Assessment",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "beforeAfter",
    tags: ["core-basecamp"],
    dayNumber: 21,
    whyNow: "After Day 3, the system generated goals for your transition. This is an honest check-in on how those goals are going.",
    science: "Goal progress assessment activates the brain's feedback processing circuits in the anterior cingulate cortex. Honest self-evaluation against pre-set criteria produces more accurate self-assessment than open-ended reflection because the criteria constrain self-serving bias.",
    instruction: "Use the before-and-after view to compare your original goals with your current progress. Rate each goal as strong progress, some movement, stalled, or not started. Then identify one focus for Week 4 — the single most important area to give your attention to.",
  },
  {
    id: "basecamp-day-22",
    name: "Seven Disruptions Reassessment",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "beforeAfter",
    tags: ["core-basecamp"],
    dayNumber: 22,
    whyNow: "On Day 1, you rated seven areas of disruption. Three weeks have passed. Rate each one again and compare the scores side by side.",
    science: "Repeated-measures self-assessment provides the brain with concrete evidence of change, counteracting the tendency to discount gradual improvement. Comparing three-week-old ratings with current ratings makes progress tangible and identifies persistent trouble spots.",
    instruction: "Use the before-and-after view to compare your Day 1 disruption ratings with today's ratings. Rate each of the seven disruptions again, then review the comparison. Notice which disruptions improved most, which are stickier than expected, and any new ones that emerged.",
  },
  {
    id: "basecamp-day-23",
    name: "Naming the Neutral Zone",
    modality: "somatic",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "emotionalArc",
    tags: ["core-basecamp"],
    dayNumber: 23,
    whyNow: "By Week 4, many people feel a strange in-between sensation — no longer the outsider, but not yet fully belonging. Bridges calls this the neutral zone.",
    science: "Normalizing the neutral zone reduces anxiety about inconsistent confidence by reframing it as a developmental phase. Mapping stress-security triggers activates metacognitive awareness that enables deliberate movement toward psychological safety.",
    instruction: "Move through the emotional arc from outsider to belonging, placing yourself honestly on the spectrum. Then map your stress-security triggers: what specific situations shift you into your secure self versus your stressed self? Name at least three triggers for each state.",
  },
  {
    id: "basecamp-day-24",
    name: "Map Revision",
    modality: "systems",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "beforeAfter",
    tags: ["core-basecamp"],
    dayNumber: 24,
    whyNow: "Your early maps of the culture, stakeholders, and power structure were based on limited information. Now update them with three weeks of lived data.",
    science: "Map revision exercises activate the brain's prediction error processing circuits, updating mental models with new data. This deliberate updating counteracts the anchoring bias that makes first impressions disproportionately influential.",
    instruction: "Use the before-and-after view to compare your original maps with revised versions. Update your cultural read, power map, and relationship positions based on what you now know. Mark where your initial reads were accurate and where they missed.",
  },
  {
    id: "basecamp-day-25",
    name: "Values Alignment Check + Relational Audit",
    modality: "relational",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "heatmap",
    tags: ["core-basecamp"],
    dayNumber: 25,
    whyNow: "This checks two things that often drift without you noticing: your values alignment and the impact of the transition on your closest relationships.",
    science: "Values-behavior drift detection activates the anterior cingulate cortex's error monitoring system. Combined with a Gottman-based relational check, this exercise prevents the common pattern where professional transitions erode personal relationships unnoticed.",
    instruction: "Use the heatmap to rate values alignment and relational health across multiple dimensions. Higher intensity areas indicate drift or strain. Check each Day 2 value for alignment, and check your closest relationships for signs of the Four Horsemen or missed bids for connection.",
  },
  {
    id: "basecamp-day-26",
    name: "Pattern Review",
    modality: "cognitive",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "saboteurCard",
    tags: ["core-basecamp"],
    dayNumber: 26,
    whyNow: "On Day 3, you identified your protective patterns. Now you have four weeks of real data. Review those patterns with the evidence of how they showed up.",
    science: "Evidence-based pattern review counteracts both over-identification with and dismissal of automatic patterns. Four weeks of behavioral data provides the minimum sample size needed for meaningful pattern recognition in naturalistic settings.",
    instruction: "Use the saboteur cards to review your patterns with four weeks of evidence. For each card, note activation frequency, professional and relational costs, moments you chose differently, and what made that possible. The gap between activation and awareness is the measure of your growth.",
  },
  {
    id: "basecamp-day-27",
    name: "Sustainable Practice Design (New Role Version)",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "timelineRiver",
    tags: ["core-basecamp"],
    dayNumber: 27,
    whyNow: "This program ends at Day 30, but your transition does not. Design a sustainable forward practice built around four key habits.",
    science: "Habit design leverages the brain's habit formation circuits in the basal ganglia by attaching new behaviors to existing contextual cues. The minimum viable practice approach prevents the common failure mode of over-ambitious post-program plans that collapse within weeks.",
    instruction: "Use the timeline river to map your forward practice across the next 90 days. Place four habit anchors along the timeline: weekly self-check-in, pre-meeting pause, monthly map update, and weekly Level 3 listening session. Set specific triggers and times for each habit.",
  },
  {
    id: "basecamp-day-28",
    name: "Honest Inventory of Open Threads",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "cardSort",
    tags: ["core-basecamp"],
    dayNumber: 28,
    whyNow: "Not everything resolves in 30 days. Transitions take 6 to 12 months. Honest acknowledgment of what is still unfinished is more useful than pretending.",
    science: "Explicit open-thread inventory reduces cognitive load by converting background rumination into organized, actionable awareness. Categorizing unresolved items by needed action prevents the accumulation of unnamed stress.",
    instruction: "Sort your open threads into categories: needs more time, needs a specific resource (coach, therapist, mentor), needs an avoided conversation, and needs continued practice. For each card, write the concrete next step. Naming what is open is the most honest thing you can do.",
  },
  {
    id: "basecamp-day-29",
    name: "Letter to Day 90",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-basecamp"],
    dayNumber: 29,
    whyNow: "The system generates a comprehensive 30-day summary. Read it, then write a letter to the person you will be at Day 90 — deeper in the role but further from this reflection.",
    science: "Future-self communication strengthens temporal self-continuity and commitment to behavior change. Writing from current awareness to a future self who may have lost that awareness creates an external memory anchor for insights that naturally fade.",
    instruction: "Follow the guided prompts to review your 30-day summary, then write your letter. Address your patterns, your tools, and what you want Day-90-you to remember when pressure increases. Write as if speaking to someone who will need a reminder of what you learned.",
  },
  {
    id: "basecamp-day-30",
    name: "One-Sentence Capture",
    modality: "integrative",
    originator: "Mindcraft / All Minds on Deck",
    primitive: "guided",
    tags: ["core-basecamp"],
    dayNumber: 30,
    whyNow: "This is the final exercise. Write one honest sentence about where you are in this transition right now. Then compare your disruption ratings across three time points.",
    science: "Final single-sentence distillation combined with triple-timepoint comparison (Day 1, Day 22, Day 30) activates both synthesis and analytical processing. The constraint of one sentence forces integration while the comparison provides concrete evidence of movement.",
    instruction: "Follow the guided prompts to write one sentence about where you actually are — not where you wish you were. Then re-rate the seven disruptions and compare Day 1, Day 22, and Day 30 ratings side by side. The trajectory is your record of movement.",
  },
];
