export interface ExerciseDefinition {
  id: string;
  name: string;
  modality: "cognitive" | "somatic" | "relational" | "integrative" | "systems";
  originator: string;
  primitive: string;
  scenario?: string;    // Journal excerpt / coaching context that triggered this exercise
  whyNow: string;
  science: string;
  instruction: string;
  tags?: ("core-parachute" | "core-jetstream" | "core-basecamp" | "journal-matched")[];
  dayNumber?: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  prePopulated?: Record<string, any>; // Seed data for the primitive based on the scenario
}

export const EXERCISES: ExerciseDefinition[] = [
  // ═══════════════════════════════════════════
  // RELATIONAL EXERCISES (1–33)
  // ═══════════════════════════════════════════

  {
    id: "ofnr-practice",
    name: "OFNR Practice",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "splitAnnotator",
    whyNow: "Your journal mentioned a conversation that left you frustrated — separating what happened from what you made it mean could untangle the knot.",
    science: "OFNR (Observation, Feeling, Need, Request) reduces amygdala hijack by forcing the prefrontal cortex to disaggregate sensory data from evaluation. fMRI studies show that labeling emotions while distinguishing them from triggering events decreases limbic reactivity by up to 30%.",
    instruction: "You will see two annotation columns side by side. On the left, paste or type what was actually said or done — raw observations only. On the right, annotate each observation with the feeling it triggered, the underlying need, and a concrete request. The split view keeps facts and interpretations visually separated so you can catch where evaluation slips into observation.",
  },
  {
    id: "self-connection-practice",
    name: "Self-Connection Practice",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "emotionWheel",
    whyNow: "You wrote about feeling 'off' today — this exercise helps you move from a vague sense of unease to a specific feeling connected to a specific need.",
    science: "Affect labeling — putting precise words to emotions — activates ventrolateral prefrontal cortex and dampens amygdala response. Granularity matters: people who distinguish between 'disappointed' and 'frustrated' regulate emotions more effectively than those who use broad labels like 'bad.'",
    instruction: "Explore the emotion wheel by tapping sectors that resonate with your current state. Start from the broad center categories and drill into more specific feelings at the outer rings. Once you land on the precise emotion, you will be prompted to identify the met or unmet need underneath it.",
  },
  {
    id: "four-communication-choices",
    name: "The 4 Communication Choices",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "forcedChoice",
    whyNow: "Your recent entry described blaming yourself after a difficult interaction — exploring all four directions of response could open up choices you didn't see in the moment.",
    science: "NVC identifies four responses to difficult messages: blame self, blame other, sense own feelings/needs, sense other's feelings/needs. Making these explicit engages cognitive reappraisal circuits, shifting processing from automatic defensive reactions to deliberate perspective-taking mediated by the temporoparietal junction.",
    instruction: "You will be presented with a difficult statement or scenario. For each round, you must choose between four response cards — Blame Self, Blame Other, Empathize Inward, Empathize Outward. After choosing, you will reflect on what that choice feels like in your body and what it costs or offers. There are no wrong answers — the exercise builds awareness of your default pattern.",
  },
  {
    id: "enemy-image-process",
    name: "Enemy Image Process",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "dialogueSequence",
    whyNow: "You mentioned someone you are struggling to see generously right now — this process can dissolve the fixed story without requiring you to condone their behavior.",
    science: "Enemy images are cognitive schemas maintained by confirmation bias and the fundamental attribution error. The Enemy Image Process works by activating mentalizing networks (medial prefrontal cortex, temporoparietal junction) to restore theory-of-mind for the 'enemy,' which down-regulates the threat response held in the amygdala and anterior insula.",
    instruction: "A guided dialogue will walk you through a sequence of prompts. First, you will voice the judgments you hold about this person without censoring. Then you will be guided to identify the feelings underneath those judgments, and finally the unmet needs driving those feelings. Each step builds on the previous one — respond to each prompt before moving to the next.",
  },
  {
    id: "mourn-celebrate-learn",
    name: "Mourn-Celebrate-Learn",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "emotionalArc",
    whyNow: "Your journal reflected on a choice you regret — this process lets you grieve what was lost, honor what was beautiful, and extract the lesson without self-punishment.",
    science: "Processing regret through structured mourning activates the brain's grief circuits (anterior cingulate, insula) in a contained way, preventing rumination loops. Following mourning with celebration engages reward circuits (ventral striatum), and the learning phase consolidates the experience into episodic memory via hippocampal encoding — transforming pain into wisdom.",
    instruction: "You will move through three emotional phases on an arc. In the Mourn phase, write about what needs went unmet and let yourself feel the loss. In the Celebrate phase, identify what needs were met or what beauty existed in the situation. In the Learn phase, name what you would do differently. The arc visualization tracks your emotional journey across these stages.",
  },
  {
    id: "chooser-evaluator-map",
    name: "Chooser-Evaluator Map",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "splitAnnotator",
    whyNow: "You wrote about something you 'should' be doing — mapping the Chooser and Evaluator voices can help you find the need behind the obligation.",
    science: "The Chooser-Evaluator distinction maps onto dual-process theory: the Evaluator voice uses moralistic judgments ('should,' 'have to') processed by default mode network rumination circuits, while the Chooser voice connects to intrinsic motivation via the autonomy circuits of self-determination theory, engaging ventromedial prefrontal cortex and increasing dopaminergic drive.",
    instruction: "In the left column, write out your Evaluator voice — the 'shoulds,' demands, and judgments about what you must do. In the right column, translate each into Chooser language by identifying the underlying need and reframing the action as a choice you make to meet that need. Notice how your body responds differently to each column.",
  },
  {
    id: "internal-mediation-map",
    name: "Internal Mediation Map",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "dialogueSequence",
    whyNow: "You described feeling torn between two directions — this mediation process gives both sides a voice so you can find the strategy that honors all your needs.",
    science: "Internal conflict creates sustained anterior cingulate cortex activation (conflict monitoring) and elevated cortisol. Giving each 'side' explicit voice reduces this conflict signal by engaging the same neural mediation processes used in interpersonal dispute resolution — mentalizing, perspective-taking, and integrative complexity — but directed inward.",
    instruction: "You will facilitate a dialogue between two conflicting parts of yourself. First, give each side a name or role. Then, in alternating turns, let each side express its feelings and needs. The dialogue sequence guides you through empathic reflection after each turn before the other side responds. Continue until both sides feel heard and a strategy emerges that honors both sets of needs.",
  },
  {
    id: "need-behind-the-no",
    name: "Need Behind the No",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "hierarchicalBranch",
    whyNow: "Your journal mentioned someone pushing back on a request — uncovering the need behind their 'no' could transform the impasse into a creative negotiation.",
    science: "When we hear 'no,' the brain's threat detection system (amygdala, anterior insula) activates, narrowing cognitive flexibility. Reframing 'no' as a 'yes' to something else engages perspective-taking circuits and broadens attentional scope via the broaden-and-build effect, enabling integrative solutions that satisfy multiple needs simultaneously.",
    instruction: "Start at the top of the branching tree with the 'no' you received (or gave). At each branch level, ask 'What need is this no protecting?' and add the possible needs as branches. Continue drilling down each branch — needs often nest inside other needs. The hierarchy reveals the root need driving the surface-level refusal.",
  },
  {
    id: "difficult-conversations-map",
    name: "Difficult Conversations Map",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "narrativeTriptych",
    whyNow: "You are preparing for a conversation you have been avoiding — mapping the three layers will help you enter it with clarity instead of reactivity.",
    science: "Difficult conversations operate on three simultaneous layers: content (what happened), feelings (emotional subtext), and identity (what this says about me). Research from the Harvard Negotiation Project shows that addressing all three layers reduces conversational breakdowns by engaging both cognitive processing (dorsolateral PFC) and emotional regulation (ventromedial PFC) simultaneously.",
    instruction: "You will write across three narrative panels. In the first panel, describe the factual content — what happened, what was said, what each person did. In the second panel, explore the emotional layer — what feelings are present for you and what you imagine for the other person. In the third panel, examine the identity layer — what is at stake for your sense of self. Review all three panels together before planning your approach.",
  },
  {
    id: "transforming-inner-critic",
    name: "Transforming Inner Critic",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "saboteurCard",
    whyNow: "Your writing carried a harsh inner voice today — meeting that critic with curiosity instead of combat can reveal the protective need it is trying to serve.",
    science: "The inner critic activates the same neural threat circuits (amygdala, dorsal ACC) as external criticism. Personifying and dialoguing with the critic engages mentalizing networks, shifting it from a diffuse threat to a discrete entity that can be reasoned with. This reduces the cortisol stress response and allows access to the underlying need the critic is trying to protect.",
    instruction: "A saboteur card will appear with space to name and characterize your inner critic. Give it a name, describe its voice and typical messages, and identify what it fears would happen if it stopped criticizing you. Then flip the card to reveal the hidden need — what is this critic trying to protect? Finally, write the message you wish it would deliver instead.",
  },
  {
    id: "faux-feelings-translation",
    name: "Faux Feelings Translation",
    modality: "relational",
    originator: "Marshall Rosenberg / NVC",
    primitive: "splitAnnotator",
    whyNow: "You used words like 'abandoned' and 'manipulated' in your journal — these are interpretations disguised as feelings. Translating them can free you from the story.",
    science: "Faux feelings ('abandoned,' 'betrayed,' 'manipulated') embed causal attributions inside emotional labels, keeping the brain locked in blame-oriented processing. Translating them to pure feelings ('scared,' 'hurt,' 'angry') and separate observations activates distinct neural circuits — interoceptive awareness (insula) rather than social judgment (lateral PFC) — enabling cleaner emotional processing.",
    instruction: "In the left column, list the 'faux feelings' — words that sound like emotions but actually contain judgments about others (e.g., 'rejected,' 'ignored,' 'used'). In the right column, translate each into a genuine feeling (what you actually feel in your body) and the observation that triggered it. Notice how the genuine feeling opens space while the faux feeling keeps you stuck.",
  },
  {
    id: "five-levels-communication",
    name: "Five Levels of Communication",
    modality: "relational",
    originator: "Stanford Interpersonal Dynamics",
    primitive: "spectrumSlider",
    whyNow: "Your entry stayed on the surface of what happened — this exercise invites you to notice what level of depth you are communicating at and whether going deeper would serve you.",
    science: "The five levels (ritual, extended ritual, surface, feelings about content, feelings about each other) map onto increasing activation of the social brain's mentalizing and interoceptive networks. Deeper disclosure activates oxytocin release and vagal tone regulation, strengthening relational bonds. Research shows that relationships deepen not through time spent but through reciprocal depth of disclosure.",
    instruction: "Use the spectrum slider to place your recent conversations on a depth continuum from Level 1 (ritual — 'How are you?' 'Fine.') to Level 5 (here-and-now feelings about each other). For each conversation you place, reflect on whether that depth matched what the relationship needed. Slide to explore what it would sound like to go one level deeper.",
  },
  {
    id: "vulnerability-loops",
    name: "Vulnerability Loops",
    modality: "relational",
    originator: "Stanford Interpersonal Dynamics",
    primitive: "guided",
    whyNow: "You mentioned wanting to be closer to someone but holding back — vulnerability loops are the mechanism through which closeness is actually built.",
    science: "Vulnerability loops follow a neurobiological sequence: disclosure activates the discloser's stress response (cortisol), the listener's empathic response triggers mirror neuron activation and oxytocin release, and the reciprocal disclosure completes the loop, establishing mutual vagal regulation. Research by Zak (2012) shows oxytocin increases trust and generosity in a positive feedback cycle.",
    instruction: "Follow the guided prompts step by step. First, identify something you have been withholding from someone. Then articulate the risk — what you fear would happen if you shared it. Next, craft the disclosure using 'I feel... because... and what I need is...' framing. Finally, plan the specific context in which you will share it. The guide will help you calibrate the level of risk to your current trust level.",
  },
  {
    id: "staying-on-your-side",
    name: "Staying on Your Side of the Net",
    modality: "relational",
    originator: "Stanford Interpersonal Dynamics",
    primitive: "splitAnnotator",
    whyNow: "Your journal made several statements about what the other person was thinking or feeling — this exercise helps you own your experience without crossing the net into their territory.",
    science: "Attributing motives to others ('You were trying to...') activates adversarial processing in the lateral prefrontal cortex and dorsal ACC. Staying on 'your side of the net' — speaking only about your own observations, feelings, and needs — reduces the listener's defensiveness by avoiding their amygdala threat response, making productive dialogue neurologically possible.",
    instruction: "In the left column, write statements that cross the net — things you said or thought about the other person's intentions, feelings, or character. In the right column, translate each into a 'my side of the net' statement that speaks only to your own experience: what you observed, what you felt, and what you need. The split view makes net-crossing immediately visible.",
  },
  {
    id: "pinch-crunch-model",
    name: "Pinch-Crunch Model",
    modality: "relational",
    originator: "Stanford Interpersonal Dynamics",
    primitive: "heatmap",
    whyNow: "You described a relationship that suddenly blew up — the pinch-crunch model suggests it was not sudden at all. Mapping the pinches you ignored can prevent the next crunch.",
    science: "Small relational violations ('pinches') accumulate as allostatic load in the stress-response system. Each unaddressed pinch lowers the threshold for amygdala activation, until a minor event triggers a disproportionate 'crunch' response. The heatmap visualization leverages pattern recognition (visual cortex + hippocampal spatial memory) to make the invisible accumulation visible.",
    instruction: "On the heatmap grid, the x-axis represents time and the y-axis represents different relationship areas (communication, respect, workload, etc.). Mark each 'pinch' — a small moment that bothered you but that you let go — in the appropriate cell. Use intensity to show how much it stung. The pattern of heat reveals where crunches are building before they explode.",
  },
  {
    id: "fifteen-percent-risk-zone",
    name: "15% Risk Zone",
    modality: "relational",
    originator: "Stanford Interpersonal Dynamics",
    primitive: "spectrumSlider",
    whyNow: "You seem to be choosing between playing it safe and going all-in — the 15% edge is where real growth happens without overwhelming your nervous system.",
    science: "Vygotsky's zone of proximal development applies to emotional risk: growth happens at the edge of current capacity. The 15% framework maps onto the Yerkes-Dodson curve — too little risk produces no learning (understimulated prefrontal cortex), too much triggers amygdala hijack and shutdown. The optimal zone produces manageable arousal that consolidates into new relational capacity.",
    instruction: "Use the spectrum slider to calibrate your risk level. The left end represents total safety (0% risk — saying nothing new), and the right end represents maximum vulnerability (100% risk — full disclosure). Position the slider where your next relational move would land. Then adjust it to the 15% zone — just enough to stretch without snapping. Write what that 15% risk would actually sound like.",
  },
  {
    id: "assertiveness-spectrum",
    name: "Assertiveness Spectrum",
    modality: "relational",
    originator: "Stanford Interpersonal Dynamics",
    primitive: "spectrumSlider",
    whyNow: "Your journal oscillated between accommodating and resenting — finding your assertiveness sweet spot could end the cycle.",
    science: "Assertiveness exists on a neurobiological spectrum: passivity correlates with dorsal vagal shutdown (freeze/submit), aggression with sympathetic dominance (fight), and healthy assertion with ventral vagal activation (social engagement). The polyvagal system predicts that assertiveness is only accessible from a state of felt safety, which this calibration exercise promotes.",
    instruction: "Place your recent interactions on the spectrum from Passive (left) through Assertive (center) to Aggressive (right). For each placement, notice what was happening in your body — collapsed and small, grounded and upright, or tight and forward-leaning. Then use the slider to find the assertive center for each situation and write what you would say from that position.",
  },
  {
    id: "four-horsemen-antidotes",
    name: "Four Horsemen and Antidotes",
    modality: "relational",
    originator: "John Gottman",
    primitive: "cardSort",
    whyNow: "The conflict you described in your journal shows patterns that relationship science has mapped precisely — identifying which horseman showed up gives you the specific antidote.",
    science: "Gottman's Four Horsemen (criticism, contempt, defensiveness, stonewalling) predict relationship dissolution with 93% accuracy. Each horseman has a distinct physiological signature: contempt elevates cortisol and suppresses immune function in the receiver, while stonewalling reflects diffuse physiological arousal (DPA) exceeding 100 bpm. The antidotes reverse these cascades by activating the ventral vagal social engagement system.",
    instruction: "Sort the cards into four categories: Criticism, Contempt, Defensiveness, and Stonewalling. Each card contains a real statement or behavior — drag it to the horseman it represents. Once sorted, flip each card to reveal the specific antidote: gentle startup for criticism, building a culture of appreciation for contempt, taking responsibility for defensiveness, and physiological self-soothing for stonewalling.",
  },
  {
    id: "softened-startup",
    name: "Softened Startup",
    modality: "relational",
    originator: "John Gottman",
    primitive: "narrativeTriptych",
    whyNow: "You are about to raise an issue with someone — Gottman's research shows that how a conversation starts predicts how it ends 96% of the time.",
    science: "The first three minutes of a conflict conversation predict the outcome with 96% accuracy (Gottman, 1999). Harsh startups trigger diffuse physiological arousal in the listener, flooding the prefrontal cortex and making collaborative problem-solving neurologically impossible. Softened startups keep arousal in the window of tolerance, preserving access to mentalizing and empathy circuits.",
    instruction: "Write across three panels to construct a softened startup. In the first panel, describe the specific situation without blame — just facts and timing. In the second panel, express your feeling using 'I feel...' language (not 'You make me feel...'). In the third panel, state your positive need — what you want, not what you do not want. Read all three panels together as your opening statement.",
  },
  {
    id: "bid-recognition-training",
    name: "Bid Recognition Training",
    modality: "relational",
    originator: "John Gottman",
    primitive: "heatmap",
    whyNow: "You mentioned feeling disconnected from someone close to you — Gottman's research shows that disconnection is usually not about big betrayals but about missed bids in small moments.",
    science: "Bids for connection are the fundamental unit of emotional communication. Gottman's research shows that masters of relationships turn toward bids 86% of the time vs. 33% for couples who divorce. Each turned-toward bid releases oxytocin and reinforces the neural pathway for future connection. Each missed bid activates the anterior insula (social pain) and weakens the bond incrementally.",
    instruction: "On the heatmap, the x-axis represents times of day and the y-axis represents types of bids (attention, affection, humor, support, shared activity). Mark each bid you noticed — whether you turned toward, turned away, or turned against it. Build the map over several days to reveal your bid patterns: where you are responsive and where bids go unnoticed.",
  },
  {
    id: "repair-attempts",
    name: "Repair Attempts",
    modality: "relational",
    originator: "John Gottman",
    primitive: "guided",
    whyNow: "The argument you described kept escalating — Gottman found that the success of a relationship depends not on avoiding conflict but on the effectiveness of repair attempts during conflict.",
    science: "Repair attempts are the secret weapon of emotionally intelligent relationships. They work by interrupting the diffuse physiological arousal (DPA) cascade — when heart rate exceeds 100 bpm, the prefrontal cortex goes offline and partners lose access to humor, empathy, and creativity. Successful repairs bring arousal back below the DPA threshold, restoring higher cognitive function.",
    instruction: "Follow the guided prompts to build your repair toolkit. First, identify the moment in your recent conflict when things escalated. Then select from a menu of repair categories: humor, affection, taking responsibility, expressing appreciation, or calling a timeout. For each repair type, craft specific language you could use. The guide helps you practice delivering repairs before you need them in the heat of the moment.",
  },
  {
    id: "xyz-formula",
    name: "XYZ Formula",
    modality: "relational",
    originator: "John Gottman",
    primitive: "splitAnnotator",
    whyNow: "Your journal contained a complaint that could easily land as criticism — the XYZ formula keeps it specific and actionable so the other person can actually hear it.",
    science: "The XYZ formula ('In situation X, when you did Y, I felt Z') constrains complaints to specific, behavioral, time-bound observations. This activates the listener's dorsolateral prefrontal cortex (problem-solving) rather than amygdala (threat detection), because behavioral feedback is processed as actionable data while character criticism triggers identity-threat cascades.",
    instruction: "In the left column, write your complaint as you would naturally say it — unfiltered, including any 'you always' or 'you never' language. In the right column, translate it into XYZ format: 'In [specific situation], when you [specific behavior], I felt [specific feeling].' The split view shows exactly how the translation removes the sting while keeping the substance.",
  },
  {
    id: "fondness-admiration-system",
    name: "Fondness & Admiration System",
    modality: "relational",
    originator: "John Gottman",
    primitive: "heatmap",
    whyNow: "You have been focused on what is going wrong in a relationship — Gottman's research shows that deliberately noticing what is going right rewires the scanning system toward appreciation.",
    science: "The fondness and admiration system is the antidote to contempt, the most corrosive of the Four Horsemen. Deliberately attending to positive qualities activates the brain's reward circuitry (ventral striatum, orbitofrontal cortex) and counters the negativity bias that makes threat-related information five times more salient than positive information. This ratio must reach 5:1 positive-to-negative for relationships to thrive.",
    instruction: "On the heatmap, the x-axis represents days of the week and the y-axis represents qualities you appreciate in your partner or close person (kindness, humor, reliability, courage, etc.). Each day, mark moments when you noticed that quality in action. Build intensity over time. The heatmap reveals which qualities you naturally notice and which you have been blind to, training your attentional system toward appreciation.",
  },
  {
    id: "dear-man",
    name: "DEAR MAN",
    modality: "relational",
    originator: "Marsha Linehan / DBT",
    primitive: "narrativeTriptych",
    whyNow: "You need to ask for something important and you are worried about how it will land — DEAR MAN gives you a research-backed script for assertive requests.",
    science: "DEAR MAN (Describe, Express, Assert, Reinforce / Mindful, Appear confident, Negotiate) is a behavioral activation protocol that systematically engages the prefrontal cortex's planning and sequencing functions. Each step reduces cognitive load during high-stakes interactions by pre-loading responses, preventing the working memory overload that leads to freezing or capitulating.",
    instruction: "Write across three panels to build your DEAR MAN script. In the first panel, write your Describe (the facts) and Express (your feelings about the facts). In the second panel, write your Assert (the specific ask) and Reinforce (why saying yes benefits them too). In the third panel, plan your MAN strategy: how you will stay Mindful of your goal, Appear confident in delivery, and Negotiate if they push back.",
  },
  {
    id: "fast-skill",
    name: "FAST",
    modality: "relational",
    originator: "Marsha Linehan / DBT",
    primitive: "forcedChoice",
    whyNow: "Your journal revealed a moment where you sacrificed your self-respect to keep the peace — FAST helps you maintain your values even when the pressure is on.",
    science: "FAST (Fair, no Apologies, Stick to values, Truthful) targets the self-respect effectiveness dimension of interpersonal functioning. Self-betrayal activates the anterior insula and dorsal ACC (moral distress signals) and erodes self-efficacy over time. Practicing FAST strengthens the ventromedial prefrontal cortex's value-congruence monitoring, making principled action more automatic under pressure.",
    instruction: "You will be presented with interpersonal scenarios. For each, choose between responses that prioritize relationship harmony vs. self-respect. There are no trick answers — the exercise builds awareness of when you abandon fairness, over-apologize, compromise your values, or shade the truth to avoid conflict. After each choice, you will see how it maps to the FAST framework.",
  },
  {
    id: "boundary-sentence",
    name: "Boundary Sentence",
    modality: "relational",
    originator: "Interpersonal Skills",
    primitive: "guided",
    whyNow: "You wrote about something you tolerated that you did not want to — crafting a clear boundary sentence turns resentment into a specific, speakable limit.",
    science: "Boundary-setting activates the prefrontal cortex's inhibitory control circuits (right inferior frontal gyrus), the same region responsible for impulse control and saying 'no.' Without a pre-formed verbal script, boundary-setting relies on real-time cognitive effort, which is depleted under stress. Having a rehearsed sentence reduces the cognitive cost of boundary enforcement by 40-60% (implementation intention research by Gollwitzer).",
    instruction: "Follow the guided prompts to construct your boundary sentence. First, name the specific behavior that crosses your boundary. Then complete the template: 'When [behavior], I need [boundary]. If [behavior continues], I will [consequence].' The guide helps you make each element concrete and enforceable — vague boundaries are unenforceable boundaries.",
  },
  {
    id: "mindful-boundary-setting",
    name: "Mindful Boundary Setting",
    modality: "relational",
    originator: "Nedra Glover Tawwab",
    primitive: "guided",
    whyNow: "You described giving more than you wanted to again — Tawwab's framework helps you recognize that boundaries are not walls but the foundation of sustainable relationships.",
    science: "Chronic boundary violation depletes the hypothalamic-pituitary-adrenal (HPA) axis, creating a state of allostatic overload that manifests as resentment, exhaustion, and eventual relational withdrawal. Mindful boundary-setting rebalances autonomic tone by pairing interoceptive awareness (noticing the body's 'no') with assertive communication, restoring the ventral vagal social engagement system.",
    instruction: "The guided process walks you through three stages. First, a body scan to identify where you feel the boundary violation physically (tight chest, clenched jaw, heavy stomach). Second, naming what you need and what you have been tolerating. Third, crafting the boundary statement using Tawwab's framework: clear, kind, and firm. The guide checks that your boundary is specific, not punitive, and focused on your own behavior change.",
  },
  {
    id: "cope-ahead",
    name: "Cope Ahead",
    modality: "relational",
    originator: "Marsha Linehan / DBT",
    primitive: "narrativeTriptych",
    whyNow: "You are dreading an upcoming interaction — mentally rehearsing your coping plan in advance means your prefrontal cortex has a script ready when your amygdala fires.",
    science: "Mental rehearsal activates the same premotor and prefrontal circuits used during actual behavior (Jeannerod, 2001). Cope Ahead leverages this motor simulation to pre-load adaptive responses, reducing the cognitive load at the moment of stress. Neuroimaging shows that imagined rehearsal of coping strategies strengthens the connectivity between prefrontal cortex and amygdala, improving real-time emotion regulation.",
    instruction: "Write across three narrative panels. In the first panel, describe the situation you are dreading in vivid sensory detail — where, when, who, what might happen. In the second panel, write the difficult moment itself and describe exactly how you will cope: what you will say, do, think, and how you will manage your body. In the third panel, write the outcome — how you will feel having navigated it skillfully. Read all three panels as a complete mental rehearsal.",
  },
  {
    id: "attachment-style-awareness",
    name: "Attachment Style Awareness",
    modality: "relational",
    originator: "Bowlby / Ainsworth / Levine & Heller",
    primitive: "stakeholderMap",
    whyNow: "The push-pull pattern you described in your journal maps directly onto attachment theory — understanding your style in different relationships can transform confusion into clarity.",
    science: "Attachment styles (secure, anxious-preoccupied, dismissive-avoidant, fearful-avoidant) are maintained by implicit relational schemas encoded in procedural memory and mediated by the oxytocin and vasopressin systems. Each style produces predictable activation patterns in the amygdala and prefrontal cortex during relational stress. Awareness does not change the style instantly but creates a metacognitive gap that enables conscious choice.",
    instruction: "Place the key people in your life on the stakeholder map. Position them by two axes: how much proximity you seek with them (closeness axis) and how much emotional safety you feel with them (security axis). For each person, note your typical attachment behavior — do you pursue, withdraw, oscillate, or feel grounded? The spatial map reveals your attachment landscape and where your patterns shift based on the relationship.",
  },
  {
    id: "braving-inventory",
    name: "BRAVING Inventory",
    modality: "relational",
    originator: "Brene Brown",
    primitive: "wheelChart",
    whyNow: "You wrote about trust being broken — BRAVING gives you a precise anatomy of trust so you can identify exactly which element was damaged and what repair looks like.",
    science: "Trust is not monolithic — it operates through seven distinct neurobiological channels: Boundaries, Reliability, Accountability, Vault (confidentiality), Integrity, Non-judgment, and Generosity. Each dimension activates different aspects of the social brain: reliability engages prediction circuits (cerebellum, basal ganglia), vault activates threat-safety evaluation (amygdala), and generosity engages the mentalizing network (TPJ, mPFC).",
    instruction: "Rate each of the seven BRAVING dimensions on the wheel chart, both for yourself and for the other person in this relationship. The seven sectors are: Boundaries, Reliability, Accountability, Vault, Integrity, Non-judgment, and Generosity. Drag each spoke outward to indicate strength in that dimension. The shape of the wheel reveals the trust profile — where it is strong and where it has gaps that need attention.",
  },
  {
    id: "heart-at-peace-war",
    name: "Heart at Peace / Heart at War",
    modality: "relational",
    originator: "The Arbinger Institute",
    primitive: "vennOverlap",
    whyNow: "You described a situation where you stopped seeing the other person as a full human — the Arbinger framework reveals how that shift happened and how to reverse it.",
    science: "The Arbinger Institute's framework maps onto dehumanization research: 'heart at war' correlates with reduced medial prefrontal cortex activity when perceiving the other (Harris & Fiske, 2006), treating them as an object rather than a mind. 'Heart at peace' restores mentalization, activating the full social brain network and enabling empathy, cooperation, and creative problem-solving.",
    instruction: "Explore the two overlapping circles. One circle represents 'Heart at Peace' — seeing the other person as a person with needs, fears, and hopes as real as your own. The other represents 'Heart at War' — seeing them as an obstacle, a vehicle, or irrelevant. Place your recent interactions in the appropriate zone, including the overlap where you fluctuated. For items in the 'war' zone, write what it would look like to see that person's humanity.",
  },
  {
    id: "global-dexterity",
    name: "Global Dexterity",
    modality: "relational",
    originator: "Andy Molinsky",
    primitive: "multiSpectrum",
    whyNow: "You mentioned navigating a cultural gap in communication style — mapping the dimensions of difference can turn awkwardness into intentional code-switching.",
    science: "Cultural code-switching engages the cognitive control network (dorsolateral PFC, anterior cingulate) and requires sustained executive function to inhibit default cultural scripts while activating alternative ones. Molinsky's research shows that mapping specific behavioral dimensions (directness, enthusiasm, formality, assertiveness, self-promotion) reduces the cognitive load of adaptation by making implicit norms explicit.",
    instruction: "You will see multiple parallel spectrums, each representing a cultural communication dimension: directness, enthusiasm, formality, assertiveness, self-promotion, and personal disclosure. For each spectrum, place two markers — one for your natural style and one for the style expected in the context you are navigating. The gap between markers shows where adaptation is needed. Write a specific behavioral adjustment for each dimension where the gap is largest.",
  },
  {
    id: "three-levels-listening",
    name: "Three Levels of Listening",
    modality: "relational",
    originator: "Co-Active Coaching (CTI)",
    primitive: "spectrumSlider",
    whyNow: "Your journal mentioned wanting to be a better listener for someone — this exercise calibrates the three levels so you can consciously choose your depth of attention.",
    science: "Level 1 (internal) listening activates the default mode network (self-referential processing). Level 2 (focused) listening engages the mentalizing network (mPFC, TPJ) and attenuates DMN activity. Level 3 (global) listening adds interoceptive awareness (insula) and environmental awareness (right hemisphere attention networks). Each level represents a measurably different neural configuration with distinct relational impacts.",
    instruction: "Use the spectrum slider to assess your listening in recent conversations. The left end represents Level 1 (internal — you are listening but mostly thinking about yourself), the center represents Level 2 (focused — your full attention is on the other person), and the right end represents Level 3 (global — you are sensing the energy, mood, and unspoken dynamics in the room). For each conversation you assess, note what pulled you to that level and what it would take to move one level deeper.",
  },

  // ═══════════════════════════════════════════
  // INTEGRATIVE EXERCISES (34–59)
  // ═══════════════════════════════════════════

  {
    id: "ifs-daily-checkin",
    name: "IFS Daily Check-in",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "emotionWheel",
    whyNow: "Your journal had multiple emotional threads running at once — checking in with your parts can help you understand who is driving the bus right now.",
    science: "IFS posits that the mind is naturally multiple, composed of sub-personalities ('parts') organized around core Self. Neuroscience supports this: different self-states show distinct patterns of brain activation (Lanius et al., 2014). The daily check-in leverages interoceptive awareness to identify which neural networks are currently dominant, creating the metacognitive distance needed to access Self-leadership.",
    instruction: "Explore the emotion wheel to identify which parts are active right now. Start from the broad center categories and drill into specifics. When you land on an emotion, pause and ask: 'Which part of me carries this feeling?' Name the part and notice where it lives in your body. You may find multiple parts active — that is normal. The goal is not to fix anything but to notice who is present.",
  },
  {
    id: "blending-check",
    name: "Blending Check",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "vennOverlap",
    whyNow: "You wrote with such intensity about one emotion that it seemed to consume everything — that is what IFS calls blending, and noticing it is the first step to unblending.",
    science: "Blending occurs when a part's emotional state overtakes the entire system, reducing access to Self-energy. Neurologically, this corresponds to amygdala hijack dominating prefrontal function. The blending check activates the observer function (medial PFC / default mode network in its constructive role), creating the metacognitive 'witnessing' capacity that Schwartz identifies as Self.",
    instruction: "The two overlapping circles represent Self and a Part. Move the circles to show how much they overlap right now — fully blended (one circle inside the other) means the part has taken over completely; fully separated means you can observe the part with curiosity. Place your current state in the overlap zone. Then identify what the blended part is feeling and what it needs you to know. Notice if naming it creates even a small separation.",
  },
  {
    id: "eight-cs-self-energy-scan",
    name: "8 C's Self-Energy Scan",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "wheelChart",
    whyNow: "You seemed disconnected from your usual groundedness today — scanning the 8 C's reveals which qualities of Self are available and which are being blocked by protective parts.",
    science: "The 8 C's (Calm, Curiosity, Clarity, Compassion, Confidence, Courage, Creativity, Connectedness) describe the phenomenology of Self-leadership. Each maps to specific neural correlates: calm to parasympathetic dominance, curiosity to dopaminergic exploration circuits, clarity to dorsolateral PFC, compassion to anterior insula and mPFC. The scan functions as a systems diagnostic, revealing where parts are blocking Self-energy flow.",
    instruction: "Rate each of the 8 C's on the wheel chart by dragging the spoke outward to indicate how present that quality feels right now. The eight sectors are: Calm, Curiosity, Clarity, Compassion, Confidence, Courage, Creativity, and Connectedness. Low scores indicate a part may be blocking that quality. For each low-scoring C, pause and ask: 'What part is making it hard to access this quality right now?'",
  },
  {
    id: "unblending-step-back",
    name: "Unblending: Ask the Part to Step Back",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "guided",
    whyNow: "A part of you has taken the wheel and is driving hard — this guided unblending practice helps you ask it to step back just enough for Self to come forward.",
    science: "Unblending is the IFS term for restoring metacognitive distance between Self and a part. Neurologically, it corresponds to re-engaging the prefrontal cortex's supervisory attentional system after an amygdala hijack. The 'ask' rather than 'force' approach respects the part's protective function, which paradoxically makes it more willing to step back — coercion activates further defensive circuits.",
    instruction: "Follow the guided prompts step by step. First, notice the strongest emotion present and locate it in your body. Then, ask the part carrying that emotion: 'Would you be willing to step back just a little, so I can get to know you better?' Notice if any space opens. If the part steps back, notice what qualities emerge (curiosity, calm, compassion). If it refuses, ask what it is afraid would happen if it stepped back. Continue the dialogue at the part's pace.",
  },
  {
    id: "six-fs-parts-work",
    name: "The 6 F's: Parts Work Protocol",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "hierarchicalBranch",
    whyNow: "You identified a recurring pattern in your journal — the 6 F's protocol provides a systematic path to understand the part driving it and what it ultimately needs.",
    science: "The 6 F's (Find, Focus, Flesh out, Feel toward, beFriend, Fear) provide a structured protocol that progressively deepens engagement with a part. Each step activates increasingly deeper neural circuits: Find uses attentional scanning, Focus engages sustained attention, Flesh out recruits interoception, Feel toward activates compassion circuits, beFriend establishes internal attachment, and Fear explores the part's protective function and exile it guards.",
    instruction: "Start at the top of the branching hierarchy with Find — locate a part you want to work with. At each branch level, follow the next F: Focus (turn your attention fully to it), Flesh out (describe its appearance, age, location in body), Feel toward (notice your attitude toward it — if anything other than curiosity, that is another part), beFriend (let it know you are interested in its experience), and Fear (ask what it fears would happen if it stopped its role). Each branch deepens the inquiry.",
  },
  {
    id: "parts-mapping",
    name: "Parts Mapping",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "saboteurCard",
    whyNow: "Your journal revealed several competing voices — mapping them as distinct parts with their own roles and fears creates the internal clarity needed to lead from Self.",
    science: "Parts mapping externalizes the internal system, engaging the brain's capacity for spatial reasoning and narrative construction. Personifying sub-personalities activates the mentalizing network (mPFC, TPJ), allowing the same empathy circuits used for understanding others to be directed inward. Research on narrative therapy shows that externalization reduces shame and increases self-compassion by creating distance between the person and the pattern.",
    instruction: "Create a card for each part you can identify in your system. Give each part a name, describe its role (what it does to protect you), its typical voice (what it says), and its core fear (what it is afraid would happen if it stopped). You can add multiple cards. Arrange them to see your inner system — notice which parts work together, which are in conflict, and which operate in the shadows.",
  },
  {
    id: "protective-parts-appreciation",
    name: "Protective Parts Appreciation",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "dialogueSequence",
    whyNow: "You have been fighting against a part of yourself that keeps showing up — what if instead of battling it, you thanked it for trying to protect you?",
    science: "Protective parts (managers and firefighters in IFS) developed their strategies during times of genuine threat. Appreciating rather than suppressing them follows the principle of reciprocal inhibition — gratitude and compassion activate the ventral vagal system, which physiologically inhibits the defensive circuits the part was activating. This paradoxically allows the part to relax its grip, creating space for Self-leadership.",
    instruction: "Enter a dialogue with one of your protective parts. Start by acknowledging what it does for you and thanking it for its efforts. Then ask it how long it has been doing this job and what prompted it to take on this role. Listen for its response and reflect it back. The dialogue sequence guides you through appreciation, understanding, and finally asking the part what it would rather do if it did not have to protect you.",
  },
  {
    id: "self-vs-self-like-parts",
    name: "Self vs. Self-Like Parts",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "vennOverlap",
    whyNow: "You sounded very calm and 'together' in your journal, but sometimes that composure is a part performing Self rather than actual Self-energy — this exercise helps you distinguish the two.",
    science: "Self-like parts are managers that mimic Self qualities — appearing calm, wise, or detached — while actually protecting the system from vulnerability. Distinguishing true Self (characterized by all 8 C's simultaneously) from Self-like parts (which show some C's but lack others, especially vulnerability and compassion) engages fine-grained self-monitoring in the medial prefrontal cortex and insula.",
    instruction: "The two overlapping circles represent true Self-energy and a Self-like part. Explore the qualities in each circle: Self carries all 8 C's (Calm, Curiosity, Clarity, Compassion, Confidence, Courage, Creativity, Connectedness), while a Self-like part carries some but not all. Place your current state in the overlap and identify which C's are present and which are missing. The missing C's point to which part is performing composure rather than embodying it.",
  },
  {
    id: "self-led-journaling",
    name: "Self-Led Journaling",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "dialogueSequence",
    whyNow: "Your journal entries have been coming from one dominant voice — Self-led journaling lets multiple parts speak and be witnessed, with Self as the compassionate listener.",
    science: "Self-led journaling activates the brain's internal dialogue circuits (left inferior frontal gyrus for production, bilateral temporal regions for comprehension) while maintaining metacognitive oversight (dorsomedial PFC). Writing from Self to a part engages the attachment system internally, creating a secure base within the psyche. Research shows that expressive writing from a compassionate self-perspective reduces inflammatory biomarkers more than standard journaling.",
    instruction: "Begin a dialogue where Self writes to a part. Start with: 'I notice you are here. What do you want me to know?' Let the part respond, then write back from Self with curiosity and compassion. Alternate turns, going deeper each time. The dialogue sequence structures the exchange so that Self always responds before the part speaks again, maintaining the compassionate witnessing posture.",
  },
  {
    id: "polarization-mapping",
    name: "Polarization Mapping",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "dialogueSequence",
    whyNow: "You described feeling stuck between two extremes — in IFS, that usually means two parts are polarized against each other, each convinced the other is dangerous.",
    science: "Polarization occurs when two parts hold opposing strategies, each escalating in response to the other — similar to arms races in game theory. Neurally, polarized parts activate competing neural networks simultaneously, creating the anterior cingulate conflict signal experienced as being 'stuck' or 'torn.' Mediation through Self de-escalates by activating the mentalizing network to hold both perspectives simultaneously.",
    instruction: "Facilitate a dialogue between two polarized parts. First, let Part A fully express its position, fears, and needs. Then let Part B respond. Self mediates by reflecting each part's core concern back before the other speaks. Continue the structured dialogue until each part can acknowledge the other's valid concern. The sequence ensures neither part dominates and both feel heard before any resolution is attempted.",
  },
  {
    id: "manager-parts-inventory",
    name: "Manager Parts Inventory",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "cardSort",
    whyNow: "Your journal revealed a lot of controlling, planning, and preventing — these are your manager parts working overtime. Naming them can help you appreciate their effort while loosening their grip.",
    science: "Manager parts in IFS correspond to proactive protective strategies mediated by the prefrontal cortex's executive control networks. They include inner critics, planners, perfectionists, and caretakers. Sorting and categorizing them engages taxonomic thinking (lateral temporal cortex), which creates psychological distance from the manager's urgency and enables Self to see the system architecture rather than being driven by it.",
    instruction: "Sort the cards into manager categories: Inner Critic, Perfectionist, Planner, People-Pleaser, Controller, Intellectual, Caretaker, and others you identify. Each card describes a managerial behavior or voice. After sorting, review each category to understand which managers are most active, which ones work together, and which exile they are protecting. Flip cards to explore what each manager fears would happen if it relaxed.",
  },
  {
    id: "firefighter-parts-inventory",
    name: "Firefighter Parts Inventory",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "cardSort",
    whyNow: "You described a reactive behavior that you felt out of control with — in IFS terms, that is a firefighter part trying to extinguish emotional pain as fast as possible.",
    science: "Firefighter parts correspond to reactive protective strategies — they activate when managers fail to contain emotional pain from exiles. Neurologically, they engage impulsive circuits (ventral striatum, orbitofrontal cortex) that prioritize immediate relief over long-term consequences. Common firefighters include bingeing, numbing, rage, dissociation, and self-harm. Identifying them without shame activates the compassion circuits that allow the firefighter to stand down.",
    instruction: "Sort the cards into firefighter categories: Numbing, Distraction, Rage, Self-criticism, Substance use, Overwork, Dissociation, and others you recognize. Each card describes a reactive behavior or impulse. After sorting, notice patterns: when do these firefighters activate? What emotion are they trying to extinguish? Flip each card to explore the exile (wounded part) the firefighter is protecting and what that exile needs to feel safe.",
  },
  {
    id: "the-path-exercise",
    name: "The Path Exercise",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "guided",
    whyNow: "You encountered a part carrying deep pain — the Path exercise provides a structured way to safely witness an exile's story and begin to unburden it.",
    science: "The Path exercise accesses exile parts — the wounded sub-personalities carrying pain from the past. Witnessing an exile's story from Self activates the brain's memory reconsolidation process (Ecker, Ticic, & Hulley, 2012): when old emotional memories are reactivated in the presence of a contradictory experience (compassion from Self), the memory can be reconsolidated with the new emotional tone, permanently transforming the felt sense of the experience.",
    instruction: "Follow the guided prompts carefully — this is deep work. First, ask your protectors for permission to approach the exile. If permission is granted, turn your attention to the exile and ask it to show you what it carries. Witness its story without trying to fix it. Then ask: 'What do you need from me right now?' Offer whatever the part needs — presence, comfort, acknowledgment. Finally, ask if it is ready to release any of what it has been carrying. Only proceed at the part's pace.",
  },
  {
    id: "courageous-love-checkin",
    name: "Courageous Love Check-in",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "dialogueSequence",
    whyNow: "You wrote about a relationship where parts keep hijacking the connection — this check-in helps you show up from Self in your most important relationships.",
    science: "Schwartz's 'courageous love' framework extends IFS to interpersonal dynamics: when two people's parts are triggering each other, the relationship becomes a system of interacting protectors. Accessing Self in relational contexts activates the ventral vagal social engagement system, which signals safety to the other person's nervous system via facial expression, prosody, and body language — co-regulating both systems simultaneously.",
    instruction: "Enter a dialogue structured around your relationship. First, identify which of your parts gets activated by this person. Then speak from Self to that part, helping it step back. Next, imagine what part the other person might be leading with, and speak to that part with compassion (in your imagination — not to the actual person). The dialogue sequence helps you practice showing up from Self before, during, and after relational interactions.",
  },
  {
    id: "parts-work-in-relationship",
    name: "Parts Work in Relationship",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "dialogueSequence",
    whyNow: "A conflict in your journal revealed the classic IFS pattern — your protector activated their protector, which activated another of yours. Mapping the parts dance is the first step to changing it.",
    science: "Relational IFS maps the mutual activation of protective parts between people. When Person A's manager criticizes, it triggers Person B's firefighter to withdraw, which triggers Person A's exile to feel abandoned, activating another protector. This cascade follows predictable neural pathways: one person's threat display (amygdala output) is detected by the other's threat detection (amygdala input), creating a limbic feedback loop. Breaking the loop requires one person to access Self.",
    instruction: "Map the dialogue between parts in your relationship. Start by identifying the part of you that showed up in the conflict. Then identify the part of the other person that responded. Continue mapping the sequence: your part reacted to their part, which triggered another part, and so on. The dialogue sequence makes the parts dance visible. End by identifying where Self could have entered the sequence to interrupt the cascade.",
  },
  {
    id: "emotional-differentiation",
    name: "Emotional Differentiation",
    modality: "integrative",
    originator: "Richard Schwartz / IFS",
    primitive: "vennOverlap",
    whyNow: "You described absorbing someone else's emotions as if they were your own — differentiating your feelings from theirs is essential for empathy without fusion.",
    science: "Emotional differentiation engages the self-other distinction circuits in the right temporoparietal junction and inferior parietal lobule. Without differentiation, empathy becomes emotional contagion — the mirror neuron system activates but the self-other boundary is not maintained, leading to personal distress rather than empathic concern. Differentiation preserves the boundary, enabling compassion without burnout.",
    instruction: "The two overlapping circles represent your emotions and the other person's emotions. Place specific feelings in the appropriate zone: feelings that are clearly yours in your circle, feelings that are clearly theirs in their circle, and feelings you have absorbed or cannot distinguish in the overlap. The goal is to shrink the overlap — for each shared feeling, ask: 'Is this mine, theirs, or both?' Move feelings to their rightful circle as clarity emerges.",
  },
  {
    id: "fulfillment-values-vision",
    name: "Fulfillment: Values, Vision, Life Purpose",
    modality: "integrative",
    originator: "Co-Active Coaching (CTI)",
    primitive: "hierarchicalBranch",
    whyNow: "Your journal hinted at a gap between how you spend your days and what actually matters to you — this exercise builds the hierarchy from values to vision to purpose.",
    science: "Values clarification activates the ventromedial prefrontal cortex, which integrates emotional significance with abstract concepts. When values are clearly articulated, they function as top-down priors that bias decision-making toward congruence, reducing the cognitive load of daily choices. Research by Schwartz & Bilsky shows that values form a hierarchical structure — surfacing this hierarchy improves goal-consistent behavior by 23% (Cohen et al., 2006 self-affirmation studies).",
    instruction: "Build a hierarchy from the top down. At the top level, name your core values — the 3-5 things that matter most to you. At the next branch level, describe the vision each value points toward — what does a life fully expressing this value look like? At the deepest level, articulate the life purpose that integrates your values and vision. The branching structure reveals how your values connect and where they converge into a unified direction.",
  },
  {
    id: "balance-coactive",
    name: "Balance",
    modality: "integrative",
    originator: "Co-Active Coaching (CTI)",
    primitive: "forceField",
    whyNow: "You described being pulled in opposite directions — the Balance exercise does not resolve the tension but helps you stand in the center of it with both eyes open.",
    science: "The force field diagram leverages Kurt Lewin's field theory: behavior is a function of driving and restraining forces in the life space. Mapping opposing forces externalizes the conflict, engaging spatial reasoning (posterior parietal cortex) to complement the emotional processing (limbic system). Research shows that explicitly naming restraining forces reduces their perceived power by bringing them from implicit to explicit processing.",
    instruction: "Place the issue you are trying to balance in the center. On the left, add the driving forces — everything pulling you toward one direction. On the right, add the restraining forces — everything pulling you the other way. Adjust the strength of each force by dragging the arrows longer or shorter. The diagram reveals which forces are strongest, where you have leverage, and what it would take to shift the equilibrium without forcing a premature resolution.",
  },
  {
    id: "process-coaching",
    name: "Process Coaching",
    modality: "integrative",
    originator: "Co-Active Coaching (CTI)",
    primitive: "emotionalArc",
    whyNow: "Your journal entry carried a strong emotional charge that was begging to be fully felt rather than analyzed — process coaching meets the emotion where it lives.",
    science: "Process coaching engages the brain's emotional processing at the somatic level, bypassing cognitive interpretation. This activates interoceptive circuits (anterior insula, somatosensory cortex) and allows emotional energy to complete its natural arc — the same principle underlying Levine's somatic experiencing. Emotions that are fully felt follow a predictable arc: activation, peak, and natural resolution. Interrupting this arc creates stuck emotional energy.",
    instruction: "Track your emotional experience on the arc as it moves through phases. Start by naming the emotion and rating its intensity. As you sit with it — without analyzing or fixing — notice how it shifts. Mark each shift on the arc: rising, peaking, transforming, settling. The emotional arc visualization shows you that feelings have a natural trajectory and that staying present with them leads to resolution without requiring cognitive intervention.",
  },
  {
    id: "wheel-of-life",
    name: "Wheel of Life Assessment",
    modality: "integrative",
    originator: "Co-Active Coaching (CTI)",
    primitive: "wheelChart",
    whyNow: "You have been focused intensely on one area of life and the rest has faded into the background — the Wheel of Life reveals the shape of your whole life, not just the crisis.",
    science: "The Wheel of Life leverages the brain's capacity for holistic pattern recognition through spatial visualization. Rating multiple life domains simultaneously activates the dorsolateral PFC's comparative evaluation function, overriding the attentional tunneling that stress creates. Research shows that multi-domain self-assessment increases self-concordance (Sheldon & Elliot, 1999) and reduces the goal neglect associated with narrow focus.",
    instruction: "Rate each life domain on the wheel by dragging the spoke outward to indicate your satisfaction level. The domains are: Career, Finance, Health, Relationships, Fun & Recreation, Personal Growth, Physical Environment, and Family & Friends. The resulting shape reveals your life balance — a round wheel rolls smoothly, while a jagged one creates a bumpy ride. Identify the one domain where a small improvement would have the biggest ripple effect.",
  },
  {
    id: "inner-boardroom",
    name: "Inner Boardroom / Allies",
    modality: "integrative",
    originator: "Co-Active Coaching (CTI)",
    primitive: "dialogueSequence",
    whyNow: "You are facing a decision and could use multiple perspectives — your inner boardroom brings together the wisest voices within you to deliberate.",
    science: "The inner boardroom technique leverages the brain's capacity for simulated social cognition. Imagining different advisors activates the mentalizing network (mPFC, TPJ, posterior cingulate) in distinct configurations, effectively running multiple perspective-taking simulations. Research on 'self-distancing' (Kross & Ayduk, 2011) shows that taking a third-person perspective reduces emotional reactivity and improves decision quality.",
    instruction: "Convene your inner boardroom by naming the advisors who sit at your table — these can be aspects of yourself (The Pragmatist, The Dreamer, The Warrior), real people you admire, or archetypal figures. Present your question or dilemma to the boardroom. Then let each advisor speak in turn through the dialogue sequence. Listen for the wisdom each offers and notice where they agree and disagree. End with a synthesis that honors the strongest counsel.",
  },
  {
    id: "leader-within",
    name: "Leader Within",
    modality: "integrative",
    originator: "Co-Active Coaching (CTI)",
    primitive: "guided",
    whyNow: "You described waiting for permission or direction from outside yourself — this exercise connects you to the leader within who already knows the next step.",
    science: "The Leader Within concept maps onto the neuroscience of intrinsic motivation and self-determination. Accessing internal leadership activates the ventromedial prefrontal cortex (value-based decision-making) and the default mode network in its constructive role (self-referential processing, future simulation). Research shows that self-determined motivation produces more sustained behavior change than externally directed motivation, mediated by greater dopaminergic engagement.",
    instruction: "Follow the guided prompts to connect with your inner leader. First, recall a moment when you led from your deepest values — not a title or role, but a moment of genuine leadership. Describe what that felt like in your body. Then bring that felt sense into your current challenge: what does this leader see? What would this leader do next? Write the specific next step that your inner leader would take. The guide helps you anchor this leadership energy so you can access it outside the exercise.",
  },
  {
    id: "radical-acceptance",
    name: "Radical Acceptance",
    modality: "integrative",
    originator: "Marsha Linehan / DBT",
    primitive: "guided",
    whyNow: "Your journal was wrestling against a reality you cannot change — radical acceptance is not approval but the decision to stop fighting what is already true.",
    science: "Radical acceptance targets the suffering equation: Pain x Resistance = Suffering. Resistance activates the dorsal anterior cingulate cortex's conflict monitoring loop, creating perseverative rumination. Acceptance deactivates this loop by engaging the ventromedial PFC's reality-monitoring function. Neuroimaging of long-term meditators shows that acceptance practice reduces dACC reactivity and strengthens prefrontal-amygdala connectivity, enabling equanimity without numbness.",
    instruction: "Follow the guided prompts through four stages. First, state the reality you are resisting — write it as a plain fact, without editorializing. Second, notice what happens in your body when you say it out loud. Third, use the half-smile and willing hands technique: soften your face and turn your palms upward while repeating the fact. Fourth, complete the statement: 'I cannot change that [fact], AND I can [action].' Radical acceptance makes space for action by ending the war with reality.",
  },
  {
    id: "wise-mind",
    name: "Wise Mind",
    modality: "integrative",
    originator: "Marsha Linehan / DBT",
    primitive: "guided",
    whyNow: "Your journal swung between cold analysis and hot emotion — Wise Mind is the place where knowing and feeling meet, and it is where your best decisions live.",
    science: "Wise Mind integrates the 'reasonable mind' (dorsolateral prefrontal cortex, logical processing) and 'emotion mind' (limbic system, affective processing) through the ventromedial prefrontal cortex, which bridges cognitive appraisal and emotional valuation. Linehan's concept aligns with Damasio's somatic marker hypothesis: optimal decisions require both logical analysis and emotional signals. Wise Mind is the neural state where both systems inform each other.",
    instruction: "Follow the guided visualization. First, connect with your reasonable mind — what do the facts and logic say about your situation? Write that perspective. Then connect with your emotion mind — what are your feelings telling you? Write that perspective. Now settle into the overlap: take three slow breaths and ask your Wise Mind, 'What do I know to be true?' Write whatever comes up without censoring. Wise Mind often speaks in simple, quiet certainty rather than loud argument.",
  },
  {
    id: "immunity-to-change",
    name: "Immunity to Change",
    modality: "integrative",
    originator: "Robert Kegan & Lisa Lahey",
    primitive: "hierarchicalBranch",
    whyNow: "You named a change you want to make but keep not making — Kegan and Lahey's framework reveals the hidden commitment that is competing with your stated goal.",
    science: "The Immunity to Change framework maps onto approach-avoidance conflict theory: a stated commitment activates approach motivation (nucleus accumbens, ventral striatum) while a hidden competing commitment activates avoidance circuits (amygdala, anterior insula). The big assumption underlying the competing commitment functions as a cognitive schema maintained by confirmation bias. Making it explicit engages the prefrontal cortex's hypothesis-testing capacity, breaking the automatic avoidance loop.",
    instruction: "Build the hierarchy in four levels. At the top, state your improvement goal — the change you genuinely want to make. At the second level, list what you are doing (or not doing) that works against that goal. At the third level, identify the hidden competing commitment — the thing you are also committed to that contradicts your goal. At the deepest level, name the big assumption — the belief that makes your competing commitment feel necessary. The hierarchy reveals why willpower alone has not worked.",
  },
  {
    id: "designed-alliance-solo",
    name: "Designed Alliance: Solo",
    modality: "integrative",
    originator: "ORSC (Organization & Relationship Systems Coaching)",
    primitive: "guided",
    whyNow: "You are about to begin a new chapter — designing an alliance with yourself sets the terms of engagement for how you will show up, especially when it gets hard.",
    science: "The Designed Alliance is an explicit relational contract. Neuroscience of commitment shows that verbalized intentions activate the prefrontal cortex's prospective memory system (Brodmann area 10), which monitors for future opportunities to fulfill the commitment. Making agreements explicit — rather than implicit — reduces the cognitive load of ongoing negotiation and activates the consistency principle (Cialdini), creating intrinsic motivation to honor the agreement.",
    instruction: "Follow the guided prompts to design an alliance with yourself. First, describe the context — what project, transition, or challenge is this alliance for? Then answer: How do I want to show up? What do I need from myself? What will I do when I feel like giving up? What does success look like, and what does 'good enough' look like? Write the final alliance as a compact statement you can return to. The guide ensures the alliance is specific, compassionate, and actionable.",
  },
];
