import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const enrollmentId = searchParams.get("enrollmentId");

    const cookieStore = await cookies();
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() { return cookieStore.getAll(); },
          setAll(cookiesToSet) {
            try {
              cookiesToSet.forEach(({ name, value, options }) =>
                cookieStore.set(name, value, options)
              );
            } catch { /* Server Component context */ }
          },
        },
      }
    );

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
    }

    // Fetch completed exercises with session day numbers
    let query = supabase
      .from("exercise_completions")
      .select("framework_name, exercise_type, modality, custom_framing, completed_at, daily_sessions(day_number)")
      .eq("client_id", user.id)
      .order("completed_at", { ascending: true });

    if (enrollmentId) {
      query = query.eq("enrollment_id", enrollmentId);
    }

    const { data: exercises, error } = await query;

    if (error) {
      console.error("Error fetching exercises:", error);
      return NextResponse.json({ error: "Failed to fetch exercises" }, { status: 500 });
    }

    if (!exercises || exercises.length === 0) {
      return new NextResponse("No exercises completed yet.", {
        status: 200,
        headers: { "Content-Type": "text/plain" },
      });
    }

    // Group by week
    const byWeek: Record<number, typeof exercises> = {};
    for (const ex of exercises) {
      const session = ex.daily_sessions as unknown as { day_number: number } | null;
      const dayNum = session?.day_number || 0;
      const week = Math.ceil(dayNum / 7) || 1;
      if (!byWeek[week]) byWeek[week] = [];
      byWeek[week].push(ex);
    }

    // Build markdown
    let md = "# Exercise Reference Guide\n\n";
    md += `Generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}\n`;
    md += `${exercises.length} exercises completed\n\n`;
    md += "---\n\n";

    for (const week of Object.keys(byWeek).map(Number).sort()) {
      md += `## Week ${week}\n\n`;
      for (const ex of byWeek[week]) {
        const session = ex.daily_sessions as unknown as { day_number: number } | null;
        const dayNum = session?.day_number || 0;
        const typeLabel = ex.exercise_type === "coaching_plan" ? "From Your Coaching Plan"
          : ex.exercise_type === "framework_analysis" ? "Framework Analysis"
          : "Matched to Your Journal";

        md += `### Day ${dayNum}: ${ex.framework_name}\n`;
        md += `*${typeLabel}* | *${ex.modality || "mixed"}*\n\n`;
        if (ex.custom_framing) {
          md += `${ex.custom_framing}\n\n`;
        }
        md += "---\n\n";
      }
    }

    md += "\n*Generated by Mindcraft — mindcraft.ing*\n";

    return new NextResponse(md, {
      status: 200,
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="mindcraft-exercise-guide.md"`,
      },
    });
  } catch (error: unknown) {
    console.error("Error in exercises/download:", error);
    return NextResponse.json({ error: "Download failed" }, { status: 500 });
  }
}
